### PR TITLE
9019 conch remove diffie hellman group1 sha1

### PR DESCRIPTION
**Pull request by markrwilliams**
https://twistedmatrix.com/trac/ticket/9019

### CODE REVIEW

**Comment by markrwilliams** [comment]
Hiya @alex!

**Comment by alex** [comment]
We had also discussed removing the smaller, and more obscure, EC curves, I take it you want to handle that as a separate PR?

**Review by alex — APPROVED** [review]

**Comment by rodrigc** [comment]
Does this code need to go through the Twisted deprecation procedure before being removed:
https://twistedmatrix.com/documents/current/core/development/policy/compatibility-policy.html
?

**Comment by alex** [comment]
Security is a documented exception to the backwards compatibility policy, and no public APIs are removed.

**Pull request merged**
