### PR TITLE
Correct twisted.internet._win32serialport hComPort to _port_handle

### PR DESCRIPTION
**Pull request by altendky**
https://twistedmatrix.com/trac/ticket/9252

### CODE REVIEW

**Comment by altendky** [comment]
I'm not sure where the coverage results are but I know there's 0% coverage since this is the one line that seems to require actual hardware to execute.  That is why it was isolated in a method that the tests override and also, of course, why it has the first bug I found...

**Review by rodrigc — COMMENTED** [review]
In this commit https://github.com/pyserial/pyserial/commit/3ad62fbc111369cbee0b6aadc88e699c39826cb2 `hComPort` was renamed to `_port_handle`

**Comment by rodrigc** [comment]
You can see the code coverage results by installing the codecov web browser plugin: https://github.com/codecov/browser-extension and then view the files at https://github.com/twisted/twisted/pull/863/files

**Review by rodrigc — APPROVED** [review]

**Comment by rodrigc** [comment]
OK

**Pull request merged**
