### PR TITLE
Use the undeprecated API in iosim

### PR DESCRIPTION
**Pull request by exarkun**
## Contributor Checklist:

* [x] There is an associated ticket in Trac. https://twistedmatrix.com/trac/ticket/9684
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )

I have not updated the automated tests because none seem to cover deprecation warning.  I want to believe there used to be CI for deprecations but this might not really be true.  In any case, I see no such thing now.  If there is one, I'd be happy to be pointed at it.

### CODE REVIEW

**Comment by Julian** [comment]
Looks like a flaky Windows test... Which seems unlikely to be the result of this...

**Review by twm — APPROVED** [review]
:+1: Looks like a reasonable change.

The failing test [is known to be flaky](https://twistedmatrix.com/trac/ticket/8879#comment:34).

**Comment by glyph** [comment]
Thanks for doing the update, @exarkun !  Unfortunately I don't think we've ever made CI for warnings (including deprecations, both our own and upstream) work.  It would be great to have that.

**Comment by exarkun** [comment]
FWIW Tahoe-LAFS has some CI for deprecations.  Unfortunately, it has an extremely high false positive rate (else why would I have submitted this PR ...).  Given the way the warnings module works I can't see a way to reliably deal with this.  Determining where the responsibility for correcting a warning falls seems to require human-level intelligence.

**Comment by twm** [comment]
@exarkun Could you file a ticket requesting that Twisted test for deprecation warnings that describes what Tahoe-LAFS does? I would compare with what I'm doing at work, where this warning is going to cause some annoyance.

**Comment by exarkun** [comment]
@twm I filed https://twistedmatrix.com/trac/ticket/9697

**Pull request merged**
