### PR TITLE
#12191: Speed up HTTP header processing even more

### LINKED ISSUE #12191: Speed up HTTP header processing even more
Currently every get and set of headers re-encodes the header name, and handles both strings and bytes. This is good for user code, but adds overhead. For built-in Twisted interactions with fixed header names, we can do better.

### PR DESCRIPTION
**Pull request by itamarst**
## Scope and purpose

Fixes #12191 

WIP, want to see codspeed results.

### CODE REVIEW

**Comment by itamarst** [comment]
Looks like the default codspeed threshold for considering it a change is 10%, I lowered it to 4%.

**Comment by itamarst** [comment]
Looks worth doing, will re-open once I've cleaned it up.

**Comment by adiroiban** [comment]
Thanks for looking into this.

Is there a way configure the threashold for codspeed ?

10% seems like a huge threashold for me... I was expecting to codespeet to raise an alert for something like 0.01 % ..

with 9.99% being unoticed with 7 such changes you end up with an 100% slowdown.

**Comment by itamarst** [comment]
Yeah I lowered it to 4%. There's a 1% noise from looking at past PRs, so could probably down to 2% and still be OK.

**Comment by adiroiban** [comment]
> On the settings page of a project, you can set a threshold for a regression to be considered a regression. By default, this value is set to 10% (which is equivalent to 0.1). The value can be set from 0% to 50% by an admin of the project

I think that we can try to go 2% and see what level of noise we get.


----------

From what I can read at https://docs.codspeed.io/features/understanding-the-metrics/#pull-request

I guess that the diff comparison is alwasy with `trunk`

I think that it would be nice to also allow comparison of a PR agains the last stable release.

This should help detect a series of PR that all have below threshold impact, but overall have a big impact.

**Pull request closed without merging**
