### PR TITLE
#12392 Add benchmark for overheads of trial test runner.

### LINKED ISSUE #12392: twisted.trial.unittest.TestCase should have a benchmark
The performance of twisted.trial.unittest.TestCase is important for developer experience, thus it should have a benchmark.

### PR DESCRIPTION
**Pull request by p12tic**
## Scope and purpose

Fixes #12392

### CODE REVIEW

**Comment by p12tic** [comment]
please review

**Review by adiroiban — APPROVED** [review]
Thanks. I think that this is a good start and we can merge it.

We will see later if these tests are flaky or not.

**Comment by p12tic** [comment]
@adiroiban I fixed a static check problem, should be ready to merge.

**Comment by adiroiban** [comment]
It looks like the `test_tcp_throughput` test is flaky ... but this is not related to the changes from this PR.


image

I triggerred a re-run of the `benchmarks` tests and it looks ok.


-------

There is this new warning ... looks like `pytest` bug.

Maybe we should just add the `__test__ = False` class member to `TestResult` to make `pytest` happy.

```
    /opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/twisted/trial/reporter.py:83: PytestCollectionWarning: cannot collect test class 'TestResult' because it has a __init__ constructor (from: benchmarks/test_trial.py)
      @implementer(itrial.IReporter)
```

**Comment by adiroiban** [comment]
Thanks again for the update. I have enabled the auto-merge. I hope it will land soon.

**Review by Ameerjb1993 — APPROVED** [review]

**Pull request merged**
