### PR TITLE
DNS names are case insensitive

### PR DESCRIPTION
**Pull request by zaheerm**

### CODE REVIEW

**Comment by rodrigc** [comment]
@zaheerm 
This pull request will not be reviewed or accepted unless you follow the process at
https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch
and file a ticket.

**Comment by zaheerm** [comment]
Thanks @rodrigc I have now filed: https://twistedmatrix.com/trac/ticket/8343

**Comment by rodrigc** [comment]
@zaheerm thanks for following the process

**Comment by adiroiban** [comment]
copy paste from https://twistedmatrix.com/trac/ticket/8343#comment:1 

Many thanks for you contribution.
1. All new changes require updated test to make sure we don't end up with regression and the test should document the intended behaviour.
2. Also, since this is an ugly bug, it would be nice if this will be advertised in the release notes of the next release. To prevent merge conflict release notes are broken into fragments. For more details see ​http://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles

Please update your branch and resubmit for review.

Many thanks again!

**Comment by zaheerm** [comment]
Updated and resubmitted for review. Thanks @adiroiban

**Pull request merged**
