### PR TITLE
Removed dubious usage of pyOpenSSL's NETSCAPE

### PR DESCRIPTION
**Pull request by alex**
Instead use the normal and idiomatic `dump_publickey` method.

https://twistedmatrix.com/trac/ticket/8441

### CODE REVIEW

**Comment by adiroiban** [comment]
Thanks for the PR.

Is there a ticket for this PR?

Please note that we now (should) have a functional travis test suite and PR are supposed to pass those tests.

**Comment by alex** [comment]
Tests green.

**Comment by adiroiban** [comment]
this patch is also updated pyopenssl dependency to 16.0.0 . 

I think that dropping support for pyopenssl 0.13.0 should be discussed over the mailing list.

while pyopenssl 16.0.0 did a lot of great things it also has a few regressions (ex https://github.com/pyca/pyopenssl/issues/456) ... and this is scary :) https://github.com/pyca/pyopenssl/issues/447

**Comment by adiroiban** [comment]
@alex please coordinate with @glyph on the Trac ticket page to see how and when to merge this branch https://twistedmatrix.com/trac/ticket/8441

Thanks!

**Comment by glyph** [comment]
Thanks @adiroiban, @alex !

**Pull request merged**
