### PR TITLE
Revert "Merge pull request #1430 from twisted/10002-mypy-internet"

### PR DESCRIPTION
**Pull request by wsanchez**
This reverts commit 73599317da1a1120ec5f8faa054704fa3f05918f, reversing
changes made to 95ebd691bc966cc897d560776940f60ead75590d.

The merge is causing trunk to fail. As yet unclear as to why.

## Contributor Checklist:

* [ ] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10002
* [ ] I ran `tox -e black-reformat` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [ ] I ran additional checks listed at [Getting Your Patch Accepted](https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted)
* [ ] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [ ] I have updated the automated tests.
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Comment by rodrigc** [comment]
This reversion doesn't fix the problem where tests are failing on Azure.

I'm not sure if the recent changes done by @graingert which changed the behavior of trial are related to these failures:
https://github.com/twisted/twisted/pulls?q=is%3Apr+author%3Agraingert+is%3Aclosed

**Comment by wsanchez** [comment]
Yeah, it doesn't look like this is going to fix anything.

**Comment by wsanchez** [comment]
FYI @graingert opened a [blank PR for debugging the issue](https://github.com/twisted/twisted/pull/1435), but I'm feeling a bit stuck, since I don't know what the cause of the error is.

**Comment by adiroiban** [comment]
I think that instead of reverting, is best to just skip the failing tests and create a new ticket in which they can be fixed and re-enabled

```
twisted.test.test_process.ProcessTests.test_manyProcesses
twisted.test.test_process.ProcessTests.test_process
```

**Pull request closed without merging**
