### PR TITLE
Fix exceptions.AttributeError: 'str' object has no attribute 'path'

### PR DESCRIPTION
**Pull request by hbjoylee**
Ticket link: https://twistedmatrix.com/trac/ticket/9056
Python version: 2.7.12
OS: Ubuntu 16.04.2 LTS
twisted: 17.1.0
When use twisted to implement SFTP server, it raises AttributeError exception due to string variable home doesn't have path attribute. 
SFTP server code as below, save as sftp.tac and run /usr/local/bin/twistd -ny sftp.tac.

```
from twisted.application import service, internet
from twisted.conch.ssh import keys
from twisted.conch.ssh.keys import Key
from twisted.conch.ssh.factory import SSHFactory
from twisted.conch.unix import UnixSSHRealm
from twisted.conch.checkers import SSHPublicKeyChecker, InMemorySSHKeyDB
from twisted.cred.credentials import IUsernamePassword
from twisted.cred.portal import Portal
from twisted.protocols import ftp

# Path to RSA SSH keys used by the server.
SERVER_RSA_PRIVATE = '/root/twisted/ssh-keys/ssh_host_rsa_key'
SERVER_RSA_PUBLIC = '/root/twisted/ssh-keys/ssh_host_rsa_key.pub'

# Path to RSA SSH keys accepted by the server.
CLIENT_RSA_PUBLIC = '/root/twisted/ssh-keys/client_rsa.pub'

with open(SERVER_RSA_PRIVATE) as privateBlobFile:
    privateBlob = privateBlobFile.read()
    privateKey = Key.fromString(data=privateBlob)

with open(SERVER_RSA_PUBLIC) as publicBlobFile:
    publicBlob = publicBlobFile.read()
    publicKey = Key.fromString(data=publicBlob)


def makeService():
    factory = SSHFactory()
    factory.privateKeys = {'ssh-rsa': privateKey}
    factory.publicKeys = {'ssh-rsa': publicKey}
    factory.portal = Portal(UnixSSHRealm())
    sshDB = SSHPublicKeyChecker(InMemorySSHKeyDB(
                {b'root': [keys.Key.fromFile(CLIENT_RSA_PUBLIC)]}))
    factory.portal.registerChecker(sshDB)

    return internet.TCPServer(2200, factory)


application = service.Application("sftp server")
sftp_server = makeService()
sftp_server.setServiceParent(application)
```

### CODE REVIEW

**Comment by rodrigc** [comment]
Thanks for the submission for Twisted.  Please follow all the steps at:
https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

You need a few things:

- need a ticket, with review keyword set
- need a topfile news fragment

Also your patch is breaking existing tests:
https://travis-ci.org/twisted/twisted/jobs/205642864

**Review by hbjoylee — COMMENTED** [review]
Add topfiles

**Comment by rodrigc** [comment]
@hbjoylee tests are still failing after your change: https://travis-ci.org/twisted/twisted/builds/205664781

**Review by hbjoylee — COMMENTED** [review]
Update home variable type to match test case

**Comment by rodrigc** [comment]
Hmm, tests are still failing.  You should try running the tests locally before pushing to GitHub.
See:
https://github.com/twisted/twisted/blob/trunk/README.rst#unit-tests

**Comment by exarkun** [comment]
Also, all changes require test coverage.  Please add a new test (or, *possibly*, fix a bug in an existing test) demonstrating the bug has been fixed.

**Comment by exarkun** [comment]
Please see https://twistedmatrix.com/trac/ticket/9056#comment:5 @rodrigc @hbjoylee

**Comment by hawkowl** [comment]
Closing per request

**Pull request closed without merging**
