### PR TITLE
Add the prepath and postpath attributes to IRequest; fix other docstrings.

### PR DESCRIPTION
**Pull request by wiml**
* [X] There are associated tickets in Trac: [5533](https://twistedmatrix.com/trac/ticket/5533), [9091](https://twistedmatrix.com/trac/ticket/9091), [9458](https://twistedmatrix.com/trac/ticket/9458)
* [X] The changes pass minimal style checks
* [X] I have created a newsfragment in src/twisted/web/newsfragments/ 
* (No automated tests needed updating)

### CODE REVIEW

**Comment by wiml** [comment]
I'm not sure why circleci failed, but I don't think it's related to these changes.

**Comment by twm** [comment]
@wiml Is this ready for review yet? I'd like to get this in so I can deal with the merge conflicts on #1109 before putting that back into review.

I kicked CircleCI.

**Comment by wiml** [comment]
This is ready for review, though I was originally planning to hold off on this until #1109 landed to avoid merge conflicts, I decided to make a PR so I wouldn't lose track of it.

I might just rebase it after #1109 lands to simplify things. Alternatively, I'd be fine with rebasing this on top of your changes and committing it along with them in the other PR; we'd just have to make sure whoever merges it notes all four trac identifiers in the merge note.

Thanks for kicking CircleCI! The macos-py37 test seems to be failing a lot right now.

**Review by glyph — APPROVED** [review]
Unless the conflicts are really substantial, please, please just land this.  We need it so bad :).

**Pull request merged**
