### PR TITLE
build reliability placeholder — https://twistedmatrix.com/trac/ticket/8879

### PR DESCRIPTION
**Pull request by glyph**

### CODE REVIEW

**Comment by glyph** [comment]
The one time I _want_ a build to fail...

**Comment by hawkowl** [comment]
Here's one for you glyph:

```

[FAIL]
Traceback (most recent call last):
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\internet\task.py", line 865, in <lambda>
    d.addCallback(lambda ignored: callable(*args, **kw))
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\trial\_dist\test\test_disttrial.py", line 323, in check
    self.assertTrue(localLock.lock())
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 388, in assertTrue
    super(_Assertions, self).assertTrue(condition, msg)
  File "c:\python27\Lib\unittest\case.py", line 422, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: False is not true

twisted.trial._dist.test.test_disttrial.DistTrialRunnerTests.test_runStopAfterTests
```

**Comment by glyph** [comment]
```
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<DTP #0 on 55301>

twisted.test.test_ftp.FTPServerAdvancedClientTests.test_STORunknownTransferErrorBecomesAbort
```

**Comment by glyph** [comment]
```
[FAIL]
Traceback (most recent call last):
  File "/buildslave/ubuntu16.04-py2.7/Twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/python/test/test_release.py", line 542, in test_buildWithDeprecated
    self.assertEqual(stdout.getvalue(), '')
  File "/buildslave/ubuntu16.04-py2.7/Twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 'Failed to get object inventory from https://hawkowl.github.io/incremental/docs/objects.inv\n' != ''

twisted.python.test.test_release.APIBuilderTests.test_buildWithDeprecated
```

**Comment by hawkowl** [comment]
test_ftp tackled here: https://github.com/twisted/twisted/pull/629

**Comment by glyph** [comment]
a couple more intermittent failures

```
[ERROR]
Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_tcp.ListeningTests testMethod=test_directConnectionLostCall> (test_directConnectionLostCall) still running at 120.0 secs

twisted.test.test_tcp.ListeningTests.test_directConnectionLostCall
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<<class 'twisted.internet.tcp.Client'> to ('127.0.0.1', 36074) at 7f7094d92410>

twisted.test.test_tcp.ListeningTests.test_directConnectionLostCall
-------------------------------------------------------------------------------
```
over on https://github.com/twisted/twisted/pull/706

https://buildbot.twistedmatrix.com/builders/ubuntu16.04-py2.7-nodeps/builds/95/steps/epoll/logs/problems

**Comment by glyph** [comment]
some failing tests from other runs, which should probably have separate issues filed:

https://github.com/twisted/twisted/actions/runs/4547941918/jobs/8018444606
```

Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/test_process.py", line 888, in test_pauseAndResumeProducing
    self.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/reactormixins.py", line 337, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_process.ProcessTestsBuilder_CFReactorTests.test_pauseAndResumeProducing
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/base.py", line 1088, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/reactormixins.py", line 332, in stop
    reactor.stop()
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/cfreactor.py", line 535, in stop
    PosixReactorBase.stop(self)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/base.py", line 792, in stop
    raise error.ReactorNotRunning("Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

twisted.internet.test.test_process.ProcessTestsBuilder_CFReactorTests.test_pauseAndResumeProducing





```
https://github.com/twisted/twisted/actions/runs/4547941918/jobs/8018444205
```

[FAIL]
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/test/test_twistd.py", line 1021, in test_setUidSameAsCurrentUid
    self.assertEqual(1, len(warningsShown))
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 441, in assertEqual
    super().assertEqual(first, second, msg)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 2

twisted.test.test_twistd.UnixApplicationRunnerStartApplicationTests.test_setUidSameAsCurrentUid


```
https://github.com/twisted/twisted/actions/runs/4547941918/jobs/8018445221
```
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-gtk-withcov-posix/lib/python3.7/site-packages/twisted/internet/test/test_posixprocess.py", line 337, in test_expectedFDs
    "Expected duplicate file descriptor to be greater than original",
  File "/home/runner/work/twisted/twisted/.tox/alldeps-gtk-withcov-posix/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 399, in assertTrue
    super().assertTrue(condition, msg)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/unittest/case.py", line 705, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: False is not true : Expected duplicate file descriptor to be greater than original

twisted.internet.test.test_posixprocess.FileDescriptorTests.test_expectedFDs
```

**Comment by adiroiban** [comment]
I think that this is safe to close this.
For macos CFReactor tests we have a separate ticket https://github.com/twisted/twisted/issues/11771 and a separate PR.

I am closing this.  Please reopen if you think this is still useful.

**Comment by adiroiban** [comment]
@glyph have you seen the other tests failing recently?

I remember the file description tests were fixed and also UnixApplicationRunnerStartApplicationTests

**Comment by adiroiban** [comment]
There is this ticket https://github.com/twisted/twisted/issues/10332 for  test_setUidSameAsCurrentUid and I think it's already fixed

**Comment by glyph** [comment]
> @glyph have you seen the other tests failing recently?
> 
> I remember the file description tests were fixed and also UnixApplicationRunnerStartApplicationTests

Fantastic. I was dumping these out of my personal task-tracking system, so if they've already been addressed, so much the better.

**Comment by adiroiban** [comment]
I think they are fixed. I remember working on those things.

I don't remember seeing those error recently.

The only flaky tests is the macOS CFRector ... and there is a set of test that fail in random order.

**Pull request closed without merging**
