### PR TITLE
Use twistedchecker 0.7.4

### PR DESCRIPTION
**Pull request by rodrigc**
https://twistedmatrix.com/trac/ticket/9802

With this change, I can do this in the top-level twisted directory with Python 3.5, 3.6, 3.7, or 3.8:

```
pip install tox
export TOXENV=lint
tox
```

### CODE REVIEW

**Review by adiroiban — APPROVED** [review]
Great work. Thanks :).
This can be merged.

**Comment by rodrigc** [comment]
@adiroiban Can you explain how `.travis/twistedchecker-trunk-diff.sh` works?

I see that `build/twistedchecker-branch.report` is generated, but I don't understand
how it is supposed to fail under CI?
I don't understand how this part:

```
diff-quality \
    --violations=pylint \
    --fail-under=100 \
    --compare-branch=origin/trunk \
    build/twistedchecker-branch.report;
```

is supposed to flag an error.

I experimented by removing the copyright in one file and running `.travis/twistedchecker-trunk-diff.sh`

**Comment by adiroiban** [comment]
It should work in theory like this:

twistedchecker runs a report on all the files from the repo and generates the report using the same format as pylint.

It can't run a report on a subset of the files (like flake8 does).
This is a technical limitation for pylint, as it needs to import the target source code.

`diff-quality` will then read the report file generated by twistedchecker and raise errors only if the reported pylint errors are for the files and code chunks that were modified in the local repository, in comparison to the trunk repo.

Does it make sense?

-----------

one point of failure is twistedchecker not producing a valid pylint report.
In this case diff-quality will not know what to do.

**Comment by rodrigc** [comment]
@adiroiban I did the following experiment on trunk:

1.  edit `src/twisted/words/tap.py` and remove the copyright
2.  `pip install diff-cover twistedchecker pycodestyle`
3.  `./.travis/twistedchecker-trunk-diff.sh twisted`

No errors were reported.

If I look in `build/twistedchecker-branch.report` I see:

```
************* Module twisted.words.tap
src/twisted/words/tap.py:31: [C0301(line-too-long), ] Line too long (89/79)
src/twisted/words/tap.py:62: [C0301(line-too-long), ] Line too long (90/79)
src/twisted/words/tap.py:1: [W9001(Used when a module of Twisted has no copyright header.), ] Missing copyright header
src/twisted/words/tap.py:1: [W9002(Used when a module does not contain a reference to test module.), ] Missing a reference to test module in header
src/twisted/words/tap.py:15: [W9208(Used when a module, function, class or method has no docstring.), Options] Missing docstring
src/twisted/words/tap.py:39: [W9201(Check the opening/closing of a docstring.), Options.opt_group] The opening/closing of docstring should be on a line by themselves
src/twisted/words/tap.py:51: [W9208(Used when a module, function, class or method has no docstring.), makeService] Missing docstring
```

So it looks like twistedchecker is doing the right thing and detects that the copyright is missing, but diff-cover doesn't report an error.  Any ideas?

**Comment by rodrigc** [comment]
@adiroiban OK, I figured it out by running diff_cover from inside the pudb debugger.
diff_cover does not report errors for lines which have been deleted.

I ran a test where I created a new file, and was able to trigger errors with twistedchecker:

```
./.travis/twistedchecker-trunk-diff.sh twisted
Failure. Quality is below 100.0%.
-------------
Diff Quality
Quality Report: pylint
Diff: origin/trunk...HEAD, staged and unstaged changes
-------------
src/twisted/words/tap2.py (91.5%):
src/twisted/words/tap2.py:1: W9001: (Used when a module of Twisted has no copyright header.), : Missing copyright header
src/twisted/words/tap2.py:1: W9002: (Used when a module does not contain a reference to test module.), : Missing a reference to test module in header
src/twisted/words/tap2.py:15: W9208: (Used when a module, function, class or method has no docstring.), KOptions: Missing docstring
src/twisted/words/tap2.py:31: C0301: (line-too-long), : Line too long (89/79)
src/twisted/words/tap2.py:39: W9201: (Check the opening/closing of a docstring.), KOptions.opt_group: The opening/closing of docstring should be on a line by themselves
src/twisted/words/tap2.py:51: C0103: (invalid-name), KmakeService: Function name "KmakeService" doesn't conform to '((([a-z])|([a-z]+_[a-z]))[a-zA-Z0-9]+)$|(__[a-z]+__)$|(\\_.+)$|(test\\_.+)$|((soap_|response_|_stat_|xmlrpc_|search_|render_|ssh_|telnet_|linemode_|opt_|async_|auth_|removeTrigger_|class_|func_|_unjelly_|agentc_|_dataReceived_|handleStatus_|_toString_|observe_|ctcpQuery_|do_|cmd_|perspective_|global_|spew_|ctcpReply_|remote_|irc_|type_|parse_|ext_|ssh_USERAUTH_PK_OK_|_process_|sync_|request_|get_|view_|ftp_|handle_|_fromString_|state_|dcc_).+)$' pattern
src/twisted/words/tap2.py:51: W9208: (Used when a module, function, class or method has no docstring.), KmakeService: Missing docstring
src/twisted/words/tap2.py:62: C0301: (line-too-long), : Line too long (90/79)
-------------
Total:   71 lines
Violations: 6 lines
% Quality: 91%
```

So I think this works.

**Pull request merged**
