### PR TITLE
Default reactor to None, which makes class Server compatibile with old…

### PR DESCRIPTION
**Pull request by barry-scott-forcepoint**
…er version of twisted,

like 2.0.

https://twistedmatrix.com/trac/ticket/9503#ticket

### CODE REVIEW

**Review by wiml — COMMENTED** [review]
This seems reasonable to me as far as it goes (though the same change should probably be made to `twisted.internet.unix.Server` as well; they both gained the extra argument in the same commit).

However, the comment at the top of `tcp.py` suggests that these interfaces should be thought of as kind of internal (which is presumably why an incompatible change was made). Why do you need to invoke `Server(...)` directly? Is there an enhancement that could be made to a higher level, more-public API instead?

**Comment by barry-scott-forcepoint** [comment]
We are a MITM engine. The high level APIs do not allow us to get at the details of the HTTP requests that is necessary to build our application.

**Comment by glyph** [comment]
> We are a MITM engine. The high level APIs do not allow us to get at the details of the HTTP requests that is necessary to build our application.

Hi @barry-scott-forcepoint,

In a general sense, I understand that you might need some deeper integration than might be available via the public API.  But, more specifically to `tcp.py`, what parameters do you need that aren't exposed publicly?

**Comment by glyph** [comment]
(My personal feeling on this is that compatibility with Twisted 2.0, in APIs that specifically describe themselves as "internal", is an explicit non-goal.  We will fix stuff like this pre-release, since technically `tcp.Server` is in a "public" namespace with respect to our compatibility policy, but this change has been out there way too long to revert on its own.  I really hope that we have the bandwidth sometime soon to simply underscore-prefix `tcp.py`, `udp.py`, and friends.)

**Comment by barry-scott-forcepoint** [comment]
I no longer need this patch merged. We refactored the code that needed this.

**Comment by glyph** [comment]
> I no longer need this patch merged. We refactored the code that needed this.

Thanks for letting us know.  Hopefully using new public interfaces!  I am sorry that Twisted didn't provide a great experience in this regard, but thanks for your contribution nonetheless.

**Pull request closed without merging**
