### PR TITLE
#11771 make cfreactor less flaky

### LINKED ISSUE #11771: Sometimes cfreactor fails twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addReader with 120 second TimeoutError
```
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/test_fdset.py", line 91, in test_addReader
    self.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/reactormixins.py", line 337, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addReader
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/base.py", line 1049, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/reactormixins.py", line 332, in stop
    reactor.stop()
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/cfreactor.py", line 538, in stop
    PosixReactorBase.stop(self)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/base.py", line 757, in stop
    raise error.ReactorNotRunning("Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addReader
-------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by glyph**
## Scope and purpose

Fixes #11771 

This is the change that appeared to have made a difference isolated and extracted from #12150 .

### CODE REVIEW

**Comment by glyph** [comment]
Both of the failures are in `twisted.internet.test.test_tcp.AbortConnectionTests_CFReactorTests.test_fullWriteBuffer`, which *also* fails sometimes in the `asyncioreactor` too: https://github.com/twisted/twisted/issues/12151

so I think this fix actually resolves the issue

**Comment by glyph** [comment]
please review

**Review by adiroiban — COMMENTED** [review]
Thanks.  Many, many thanks for working on this.

Were you able to reproduce the errors on your local system?

I was trying to reproduce them on a macmini m1, without luck.

--------

I think that we should just merge it and see if works.

**Review by adiroiban — APPROVED** [review]
Previous comment was an "approve".

**Comment by glyph** [comment]
> Were you able to reproduce the errors on your local system?

I was not. But in every other case I managed to reproduce the error in CI after a minimum of 5 tries.

The race condition here is extremely subtle, and I couldn't even think of a white-box test to reproduce it, but basically if something were to call `_scheduleSimulate` without `force` *after* calling it *with* `force`, so logically I think I see how this hang *could* happen.

**Pull request merged**
