### PR TITLE
#11575 Move development related docs into a single folder inside docs root.

### LINKED ISSUE #11575: Move development docs into the tree root
I think that having dev docs inside /core/development and /core/development/policy is complicated.

We should have them inside /development

### PR DESCRIPTION
**Pull request by adiroiban**
## Scope and purpose

Fixes #11575

This moves all the dev docs into a separate folder.
It keeps redirection pages.

Right now we have docs:

* Here - https://docs.twisted.org/en/stable/core/development/index.html
* and here - https://docs.twisted.org/en/stable/core/development/policy/index.html

I think that `/core/development/policy/` too deep, and has sub-documented, and we have sub-documetns also at `/core/development/`
This PR moves all the dev docs into a single place at `/development` 

And keeps redirection pages for the old URL.

## How to test

This PR is only about moving existing content.
No changes were done to the content itslef.
It's just an re-organization

* New pages at https://twisted--11577.org.readthedocs.build/en/11577/development/index.html
* Some redirection pages https://twisted--11577.org.readthedocs.build/en/11577/core/development/index.html
* And policy redirection https://twisted--11577.org.readthedocs.build/en/11577/core/development/policy/index.html
* A leaf redirection https://twisted--11577.org.readthedocs.build/en/11577/core/development/philosophy.html

## Contributor Checklist:

* [x] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://docs.twistedmatrix.com/en/stable/core/development/policy/coding-standard.html)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://github.com/twisted/trac-wiki-archive/blob/trunk//ReviewProcess.mediawiki#News_files))
* [x] The title of the PR starts with the associated issue number (without the `#` character).
* [NA] I have updated the automated tests and checked that all checks for the PR are green.
* [X] The merge commit will use the below format
  The first line is automatically generated by GitHub based on PR ID and branch name.
  The other lines generated by GitHub should be replaced.

```
Merge pull request #123 from twisted/4356-branch-name-with-issue-id

Author: adiroiban
Reviewer: 
Fixes #11575

Move all dev docs into the root of the docs project.
```

### CODE REVIEW

**Comment by adiroiban** [comment]
this is ready for review 

needs-review

**Comment by adiroiban** [comment]
this is ready for review.

please review

**Review by graingert — APPROVED** [review]

**Comment by adiroiban** [comment]
thanks for the review. I will merge this.

**Comment by graingert** [comment]
Thanks for the redirects here, sometimes I Google something and get to a page that has a "go to latest" the top and it 404s
Is there a way to crawl all the old docs and find all these broken links so I can go and fix them?

**Pull request merged**
