### PR TITLE
Brand: Qt

### PR DESCRIPTION
**Pull request by jsoref**
**Qt** is spelled as such, see [doc.Qt.io](http://doc.qt.io/)
Not to be confused with **QT** [QuickTime](https://support.apple.com/quicktime)
## Contributor Checklist:

* [x] There is an associated ticket in Trac. Create a new one at https://twistedmatrix.com/trac/newticket
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests.

### CODE REVIEW

**Comment by altendky** [comment]
@jsoref, I totally agree it is correct to change this.  Going to need the formalities though I suspect.  Empty misc news fragment would be fine and a ticket in trac.

Cheers,
-kyle

**Comment by jsoref** [comment]
@altendky: Trac thinks I'm a spammer (it's also fairly misconfigured, it includes a link to a non-existent login page). I'm happy to do the other bits, but can you possibly help out w/ the Trac side?

**Comment by altendky** [comment]
@jsoref, it rated my last two tickets as spammy enough to warrant a captcha.  It totally blocked you?  What username did you use for Trac?  I did a quick look (hopefully not too quick) and didn't see one that seemed to be you.  I can't do anything about this but I'll bump someone who can when we've got the username to check.

**Comment by jsoref** [comment]
> logged in as jsoref (GitHub login)

It offered a captcha (the click the box simple one) which I passed and then it still rejected my submission...

**Comment by altendky** [comment]
Yeah, I looked way too quick, sorry.  @glyph, you said to mention Trac spam issues.  Looks like `Josh Soref` got blocked.

**Comment by glyph** [comment]
> Yeah, I looked way too quick, sorry. @glyph, you said to mention Trac spam issues. Looks like Josh Soref got blocked

Thanks for bringing this to my attention; I’ve informed the spam filter that those attempts at comments were not spam.

**Comment by altendky** [comment]
https://twistedmatrix.com/trac/ticket/9536

**Comment by altendky** [comment]
@jsoref, adding the newsfragment (empty `src/twisted/newsfragments/9536.misc` I believe) should fix the build.

https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles

(good deal, the link to the newsfragments directory on GitHub is broken there...)

Now I have to admit that I forgot something.  I do not have commit access so I won't be able to finalize the change for you.  But, I can still make sure we get the details worked out so it's a quick review etc for someone with permissions.  Sorry about that.

**Comment by jsoref** [comment]
Indeed, they're missing a `src/` after `trunk/` (and it looks like they may have discontinued the distinct newsfragment directories??)

**Comment by altendky** [comment]
Alrighty, build looks good.  IIRC the coverage loss is because it hasn't been sent to buildbot yet so some corner cases for particular platforms haven't been hit.  Obviously this change wouldn't actually affect coverage...  It looks good to me so go ahead and add the review keyword to the ticket to put it on the review list.  Hopefully someone has a few minutes soon'ish to take care of this.

Thanks for your patience with the details and hangups.  Oh, I'm working through getting permissions so I can fix the wiki page up.

**Comment by jsoref** [comment]
afaict it won't let me add labels.

**Comment by altendky** [comment]
It's the 'keywords' field in the Trac ticket.  Since you said labels I'm guessing you tried to do it here in github instead.

**Comment by altendky** [comment]
@jsoref and that's that...  now we wait.  :]  I saw the notification in IRC so you got it submitted for review.  Thanks, I'll see if I can get this simple change reviewed sooner rather than later.

**Review by twm — APPROVED** [review]
Thanks for pointing out the broken links on https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles. I fixed them and added web.

Will pr_as_branch this now. It looks good to go, just need to satisfy CI.

**Pull request merged**
