### PR TITLE
IRC constant fixes

### PR DESCRIPTION
**Pull request by scop**
https://twistedmatrix.com/trac/ticket/8585

### CODE REVIEW

**Comment by rodrigc** [comment]
If you do the following:

```
pip install coverage tox
```

Go to the root of your twisted checkout and do:

```
coverage erase
tox -e py27-coverage
coverage combine
ls -l .coverage
coverage report
coverage html
```

Are your changes under coverage?

If not the Twisted devs will probably not allow this patch in.  If you modify one of the IRC tests to cover this code, then it will be OK.

**Comment by scop** [comment]
Yes, if I can read the report correctly, the changes are under coverage.

**Comment by rodrigc** [comment]
If you use the Google Chrome browser (it only works with Chrome) and go to: https://github.com/twisted/twisted/blob/trunk/twisted/words/protocols/irc.py

do you see a button to the left of *\* Raw | Blame | History *\* with a number?

That is another way to see the coverage of a file.  The https://coverage.io web site integrates the
info with GitHub.

**Comment by scop** [comment]
No such button is shown to me.

screenshot from 2016-07-11 12-53-32

**Comment by Lukasa** [comment]
That option requires installing [the codecov browser extension](https://github.com/codecov/browser-extension).

**Comment by rodrigc** [comment]
Ah, OK.  I forgot, I installed the codecov browser extension for Chrome.  That way when I open that link, I see something like this screenshot: https://github.com/codecov/browser-extension#codecov-extension

**Comment by scop** [comment]
Nifty. Seems that it doesn't show coverage for changes in pull requests though, at least it doesn't for this one -- but maybe because the coverage check is still "Waiting for status to be reported" (it's been like that for a long time already, maybe there's a problem?). And anyway if it works for PR's it's a bit after the fact thing; I'd like to check coverage _before_ submitting one. I guess local coverage is the only thing making that possible.

**Comment by rodrigc** [comment]
So the way that codecov works is this.
- someone pushes a branch to the Twisted repo GitHub
- the buildots at https://buildbot.twistedmatrix.com build the change, and then run the tests under codecov
- the buildbots then upload the coverage report to https://codecov.io
- codecov.io then updates the PR with the coverage statistics

The only thing missing from this workflow is that the buildbots only build branches
at https://github.com/twisted/twisted .  The buildbots do not build branches from forked repositories,
such as your https://github.com/scop/twisted repository.  That is why coverage reports in your
PR is not there, but it is there in this one: https://github.com/twisted/twisted/pull/308/files

It's a minor detail, due to a limitation in the resources that the Twisted project has.

**Comment by adiroiban** [comment]
We now have coverage reported from travis.
merging trunk and pushing the merge should trigger a new build and publish the coverage

for the review see https://twistedmatrix.com/trac/ticket/8585#comment:3

feel free to put it back for review is my comments don't make sense :)

**Comment by rodrigc** [comment]
Moved to https://github.com/twisted/twisted/pull/355

**Pull request closed without merging**
