### PR TITLE
Fix postfix on Python 3

### PR DESCRIPTION
**Pull request by rodrigc**
http://twistedmatrix.com/trac/ticket/9335

### CODE REVIEW

**Comment by rodrigc** [comment]
@albertkoch can you try this patch?  I incorporated your sample code as a test case

**Comment by albertkoch** [comment]
This patch worked perfectly for me. Thank you.

**Comment by rodrigc** [comment]
Thanks @albertkoch!  Can you go to https://github.com/twisted/twisted/pull/930/files , click on the green *Review changes* button, and approve the changes?  That way I can merge the code.
You can double check the Twisted code review guidelines here: https://twistedmatrix.com/trac/wiki/ReviewProcess#Reviewers:Howtoreviewachange

**Review by albertkoch — APPROVED** [review]
Looks good. This solves the issue in my environment.

**Pull request merged**
