### PR TITLE
New twisted application runner: twist

### PR DESCRIPTION
**Pull request by wsanchez**
Eventual replacement for `twistd`

See https://twistedmatrix.com/trac/ticket/5705

### CODE REVIEW

**Comment by rodrigc** [comment]
Are you additions Python 3 clean?  I think you need to add these modules to twisted/python/dist3.py:

```
A twisted/application/runner/__init__.py (7)
A twisted/application/runner/_exit.py (138)
A twisted/application/runner/_runner.py (244)
A twisted/application/runner/test/__init__.py (7)
A twisted/application/runner/test/test_exit.py (104)
A twisted/application/runner/test/test_runner.py (460)
A twisted/application/twist/__init__.py (13)
A twisted/application/twist/_options.py (194)
A twisted/application/twist/_twist.py (141)
A twisted/application/twist/test/__init__.py (7)
A twisted/application/twist/test/test_options.py (370)
A twisted/application/twist/test/test_twist.py (201) 
```

If you have Python 3.5 on your system you can do:

```
tox -e py35-tests-posix
tox -e py35-tests-posix twisted.application.twist.test.test_twist
tox -e py35-tests-posix twisted.application.twist.test.test_options
tox -e py35-tests-posix  twisted.application.runner.test.test_exit
tox -e py35-tests-posix   twisted.application.runner.test.test_runner
```

to verify after adding those to dist3.py

**Comment by wsanchez** [comment]
OK got some py3 errors, should fix that before merging.

**Comment by rodrigc** [comment]
Thanks, the dist3.py thing is a bit confusing, so I thought I would point it out.
Hopefully we will soon get to the point in Twisted where everything works under Python3 and we can get rid of dist3.py

**Comment by wsanchez** [comment]
0d33bc7a02d40a4313f47eedade8f8f9456ba452 fixed the py3 stuff. (strings, of course)

**Comment by rodrigc** [comment]
I like this.  Please merge it.

**Pull request merged**
