### PR TITLE
[9744] Clean up pywin32-related apidocs errors

### PR DESCRIPTION
**Pull request by twm**
Remove the logic to generate links to pywin32's API docs as they have been a 404 for over a year and I cannot find a replacement.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9744
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Comment by glyph** [comment]
> ... links to pydoctor's API docs ...

links to… pywin32’s API docs?

**Comment by glyph** [comment]
Should we just change the base URL to http://timgolden.me.uk/pywin32-docs/index.html ?  This seems to be the new quasi-official location.

**Comment by twm** [comment]
I'd say no. There is literally a single public link to win32api in Twisted:

```
twisted$ rg win32api
...

src/twisted/python/win32.py
80:        L{win32api.FormatMessage}).
100:            from win32api import FormatMessage

...
```

There is a second reference in a test. That's all.

Making these links isn't worth the code I deleted here, nor the four (?!) HTTP requests to verify the links while building the API docs. I will just make the public one a direct link. Thanks for finding a target!

**Comment by twm** [comment]
...actually even the one I listed above is part of a private class, `twisted.python.win32._ErrorFormatter`. Oh well, it's a link now.

**Review by rodrigc — APPROVED** [review]
It's not worth trying to figure out where these pywin32 docs are so that we can put a link to them.
This is fine.

**Pull request merged**
