### PR TITLE
[8831] Make Conch use `cryptography` for DH

### PR DESCRIPTION
**Pull request by wiml**
Not exactly a frequently used algorithm any more, but this moves the DH implementation and (more importantly from a security standpoint, I think) the key generation into `cryptography` (and therefore into openssl).

## Contributor Checklist:

* [X] There is an associated ticket in Trac: https://twistedmatrix.com/trac/ticket/8831
* [X] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [X] I have created a newsfragment in src/twisted/newsfragments/
* [X] I have updated the automated tests.

### CODE REVIEW

**Comment by wiml** [comment]
One of the buildbot tests failed, but I believe it's spurious or at least unrelated to this code (some tests timed out in t.w.cgi, and only for the epoll reactor not the others).

**Comment by twm** [comment]
I kicked the buildbot failure. It does seem to have been spurious.

**Review by lvh — APPROVED** [review]
Thanks!

**Comment by twm** [comment]
I kicked Appveyor and reported the failure to https://twistedmatrix.com/trac/ticket/8879#comment:16

**Pull request merged**
