### PR TITLE
#12146 Remove support for SOAP.

### LINKED ISSUE #3283: twisted.web.soap's client API should be updated to use ZSI 2.0
|[radix's avatar](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#3283|
|Type|enhancement|
|Created|2008-06-06 22:26:15Z|

Maybe it's impossible to do that in a backwards compatible way, but twisted.web's SOAP support is really horrible, mostly because SOAPpy is really really terrible. ZSI 2.0 is apparently much better.

<details><summary>Searchable metadata</summary>

```
trac-id__3283 3283
type__enhancement enhancement
reporter__radix radix
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__reopened reopened
resolution__ 
component__web web
keywords__ 
time__1212791175000000 1212791175000000
changetime__1248351491000000 1248351491000000
version__None None
owner__jknight jknight

```
</details>

### LINKED ISSUE #3284: twisted.web.soap's server API should be updated to use ZSI 2.0
|[radix's avatar](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#3284|
|Type|enhancement|
|Created|2008-06-06 22:27:05Z|

Maybe it's impossible to do that in a backwards compatible way, but twisted.web's SOAP support is really horrible, mostly because SOAPpy is really really terrible. ZSI 2.0 is apparently much better.

See http://pywebsvcs.sourceforge.net/zsi.html for documentation.

<details><summary>Searchable metadata</summary>

```
trac-id__3284 3284
type__enhancement enhancement
reporter__radix radix
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1212791225000000 1212791225000000
changetime__1215632028000000 1215632028000000
version__None None
owner__ 
cc__thijs
```
</details>

### LINKED ISSUE #4729: Add a withRequest decorator for SOAP methods
|wam's avatar| wam reported|
|-|-|
|Trac ID|trac#4729|
|Type|enhancement|
|Created|2010-11-05 12:56:26Z|

As stated in [#3073](https://github.com/twisted/twisted/issues/3073) it's very useful to have the request inside a soap method. So here is the patch for twisted/web/soap.py.

Attachments:

* [withRequest-soap.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/541/541f66976e0f98189884f38b6f907def43c6c2cf/0dfb020335f9b5e14fe05a9c7c28d36ff388678f.patch) (2698 bytes) - added by wam on 2010-11-05 12:56:35Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__4729 4729
type__enhancement enhancement
reporter__wam wam
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1288961786000000 1288961786000000
changetime__1289231181000000 1289231181000000
version__None None
owner__jknight jknight
cc__wam
```
</details>

### LINKED ISSUE #12146: Remove the soap code
Thanks for the feedback.

I think that is safe to just remove the SOAP code

It is already broken.

It looks like we still have code that was not ported to py3 ... or for which we don't execute the tests.

If anyone want to have SOAP support in Twisted, they can send a PR

```
$ pip install soappy
$ python
Python 3.12.2 (main, Feb 25 2024, 16:35:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.web.soap import SOAPPublisher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adi/chevah/twisted/src/twisted/web/soap.py", line 19, in <module>
    import SOAPpy
  File "/home/adi/chevah/twisted/venv-3.12/lib/python3.12/site-packages/SOAPpy/__init__.py", line 3, in <module>
    from version import __version__
ModuleNotFoundError: No module named 'version'
>>> 
```

_Originally posted by @adiroiban in https://github.com/twisted/twisted/issues/12145#issuecomment-2088413289_

### PR DESCRIPTION
**Pull request by adiroiban**
## Scope and purpose

Fixes #12146

Also all the existing SOAP tickets.

Fixes #3284
Fixes #3283
Fixes #4729

This removes the SOAP code.

It looks like the SOAP code was broken for many releases and nobody complained.

The automated tests were alwasy skipped... as SOAPPY was never installed as part of the CI process.

Also, we don't have a mantainer for the SOAP code.

I think that if anyone want to add support for SOAP in twisted, is best to create a separate independent twisted/txsoap repo

### CODE REVIEW

**Review by glyph — APPROVED** [review]
let's juice those coverage metrics!

**Comment by adiroiban** [comment]
Mailing list announcement set , as requested by our [compatiblity policy](https://docs.twisted.org/en/latest/development/compatibility-policy.html#procedure-for-exceptions-to-this-policy):

https://mail.python.org/archives/list/twisted@python.org/thread/ZRJNWJY6XBMBICHF2TCEVECASWKWS6PT/


needs-review

**Comment by adiroiban** [comment]
The current codecov.io reports are "optional" and they will not block a merge.

When a log of code is removed, it is expected to see a drop in overal project coverage.

------

the macOS tests are requried, and they will block the merge :(

**Comment by glyph** [comment]
Let's see how macOS does with the fix on trunk :)

**Review by glyph — APPROVED** [review]
It's broken, let's get rid of it.

**Comment by adiroiban** [comment]
Thanks for the review.

I am waiting 1 week, as requested by the procees, and then will merge.

The process requires the approval of 3 contributors ... but given that the Twisted project was not very actively lately, I guess that it's ok to merge with the aproval of a single contributor.

I hope that I will not forget about it

**Review by gudnimg — APPROVED** [review]
If it helps, you have my approval :)

**Comment by glyph** [comment]
> If it helps, you have my approval :)

It does! External reviews are always appreciated; obviously you can't merge stuff, but we take it into account.

**Comment by adiroiban** [comment]
Thanks for your reviews.
I have enabled auto-merge on this PR.

I hope it will land soon.

**Pull request merged**
