### PR TITLE
Run twisted.words.test.test_domish on Python 3

### PR DESCRIPTION
**Pull request by rodrigc**
https://twistedmatrix.com/trac/ticket/9246

This works on Python 3, after https://github.com/twisted/twisted/pull/839

### CODE REVIEW

**Comment by rodrigc** [comment]
@tehasdf can you review this?
There is one travis build failing which I have a separate fix for in https://github.com/twisted/twisted/pull/854

**Review by tehasdf — APPROVED** [review]
Green - gotta enable the tests so that porting can be done :)

**Comment by rodrigc** [comment]
@tehasdf thanks for the review.  Can you do me one favor and modify this ticket https://twistedmatrix.com/trac/ticket/9246 by removing the *review* keyword, and also by assigning that ticket to me so that I can proceed with the merge?

Thanks!!

**Comment by tehasdf** [comment]
@rodrigc done (the trac thing)

**Comment by rodrigc** [comment]
@teasdf Thanks!!

**Pull request merged**
