### PR TITLE
10235  accept non-function callables in LoopingCall and DeferLater

### PR DESCRIPTION
**Pull request by graingert**
## Scope and purpose

Add a few words about why this PR is needed and what is its scope.

Add any comments about trade-offs (if any) made in this PR and the reasoning behind them.

Add mentions of things that are not covered here and are planed to be done in separate PRs.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10235
* [ ] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [x] The title of the PR starts with the associated Trac ticket number (without the `#` character).
* [ ] I have updated the automated tests and checked that all checks for the PR are green.
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.
* [ ] The merge commit will use the below format
  The first line is automatically generated by GitHub based on PR ID and branch name.
  The other lines generated by GitHub should be replaced.

```
Merge pull request #123 from twisted/4356-branch-name-with-trac-id

Author: <github_username>, <github_usernames_if_more_authors>
Reviewer: <github_username>, <github_username_if_more_reviewers>
Fixes: ticket:<trac_ticket_number>, ticket:<another_if_more_in_one_PR>

Long description providing a summary of these changes.
(as long as you wish)
```

### CODE REVIEW

**Review by ShadowJonathan — CHANGES_REQUESTED** [review]
This revert is unnecessary, it should only need the following lines in `base.py` and `task.py` as a replacement;

```py
            try:
                name = self.func.__qualname__
            except AttributeError:
                name = type(self.func).__qualname__
```

**Review by adiroiban — APPROVED** [review]
Thanks for the quick reply. Feel free to merge as soon a the tests are green :)

**Comment by wsanchez** [comment]
@graingert, @adiroiban: It looks like we didn't respond to @ShadowJonathan above.

Since this fix was cleanup as part of the original PR, and only reverts a small part of it, I think we can close the original ticket again, but perhaps I should open a new PR to put the change back in with @ShadowJonathan's suggested fix.  That said… are there other ways to create a callable than functions and classes with `__call__`?  Don't want to get bitten by this twice.

**Comment by graingert** [comment]
@wsanchez I think extension modules can create callable objects in unconventional ways. I think removing the unsatisfiable "im_class" branch and the counterexamples found in the ticket would be enough here.

Here's how anyio does a similar task: https://github.com/agronholm/anyio/blob/af2b13880ca5785af9a9f98bcc20865c779ec9c1/src/anyio/_backends/_asyncio.py#L166

**Comment by graingert** [comment]
And there's this as well https://bugs.python.org/issue4113

**Pull request merged**
