### PR TITLE
Call sys.exc_clear() on Python 2, in few key tests 

### PR DESCRIPTION
**Pull request by rodrigc**
See: https://twistedmatrix.com/trac/ticket/8496

### CODE REVIEW

**Comment by Lukasa** [comment]
@glyph So codecov seems to be losing its mind here, and claiming that the patch isn't covered in the Python 3 case, even though I can _see_ the buildbots running the test. Want to investigate a bit here, or at least merge, because I cannot merge this with codecov claiming the patch is uncovered.

**Comment by Lukasa** [comment]
@adiroiban will probably care about this too.

**Comment by rodrigc** [comment]
@glyph @adiroiban @Lukasa this test is not showing coverage on Python3, but if I look at https://buildbot.twistedmatrix.com/boxes-supported?branch=8496-rodrigc-sys.exc_clear , I see that 
there are fedora22-py3.4-coverage and fedora23-py3.4-coverage buildbots which are running this test.

Do you know what is wrong?

**Comment by rodrigc** [comment]
@adiroiban @glyph @Lukasa codecov seems happy now

**Pull request merged**
