### PR TITLE
Fix docstring syntax errors

### PR DESCRIPTION
**Pull request by mthuurne**
This removes some noise from the pydoctor logging, so actual problems will stand out more.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9868
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] ~~I have updated the automated tests.~~ Only docstrings are changed.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Comment by mthuurne** [comment]
CircleCI refuses to let me view the details of the test failure unless I hand it read/write access to all my repositories, which I'm obviously not going to agree to. Is this a bug? If not, I think it's a completely unacceptable policy, both in terms of privacy and security.

_Update:_ exarkun was kind enough to copy-paste the error message on IRC; it was about the missing news fragment. I still think it's a problem though that CircleCI won't show details unless you hand it a bunch of permissions it doesn't need.

**Comment by mthuurne** [comment]
~~The problem identified by Travis is the one I mentioned in the initial comment: lint errors near, but not caused by, the changed lines. Should I fix those even though they have nothing to do with the actual purpose of the PR?~~

I fixed the unrelated lint errors in a separate commit.

**Review by rodrigc — APPROVED** [review]
This looks OK

**Comment by rodrigc** [comment]
@mthuurne in future when you merge your PR to Twisted's trunk, you need to manually add these three lines to the merge commit message:

```
Author:
Reviewer:
Fixes: ticket:
```

This auto-closes the Trac ticket, and updates https://twistedmatrix.com/highscores

See: https://twistedmatrix.com/trac/wiki/ReviewProcess#Authors:Howtomergethechangetotrunk

You can also look at some other merge commits in Twisted for examples.

**Comment by mthuurne** [comment]
Sorry, this was my first time merging a commit for Twisted; I'll do that next time.

**Comment by rodrigc** [comment]
It's OK, the Twisted dev process is a bit complicated for newcomers, but once you get the hang of it, it is OK.

**Pull request merged**
