### PR TITLE
8638 einarfd ssh transport

### PR DESCRIPTION
**Pull request by einarfd**
Pull request for bug https://twistedmatrix.com/trac/ticket/8638

### CODE REVIEW

**Comment by einarfd** [comment]
I've had a look at the error from travis, and I don't really think they can be fixed from my side. 
The pyflakes is missing on Py2.7 must be a missing install, I can not see any way my changes should be able to have any impact on that. 
The _kex import error on the Py3.\* tests is a bit mysterious, the _kex.py file is there on my branch, and test_transport works when I run trial locally. Could it be that the tests are picking up a different twisted installation? _kex was introduced in October so it hasn't been in twisted that long.

**Comment by rodrigc** [comment]
@einarfd Your build is failing because you need to add the modules you ported to twisted/python/dist3.py

To reproduce the problem, you need to run the tests under tox.

For example, if you have Python 3.5 installed on your system, you can do:

```
tox -e py35-tests
```

**Comment by rodrigc** [comment]
pyflakes is failing on your build right here: https://travis-ci.org/twisted/twisted/jobs/146122115#L244

```
twisted/conch/test/test_transport.py:48: 'twisted.python.compat.networkString' imported but unused
```

**Comment by einarfd** [comment]
This is the middle of the vacation season at work, so I have some time to spend on getting last bit of Twisted we need ported to Python 3. Internally we have a half finished port of SSH on an old version of Twisted, so I'm massaging it and trying to get into acceptable bit pieces, and get those ready as merge requests.
I hope to at least get twisted.conch.endpoints and it dependencies Python 3 compliant.

**Comment by rodrigc** [comment]
Nice!  Great you are working on it!  I will try to review and get your patches in.

**Comment by rodrigc** [comment]
Moved to:
https://github.com/twisted/twisted/pull/376

**Pull request closed without merging**
