### PR TITLE
Python 3 port of conch.ssh.address

### PR DESCRIPTION
**Pull request by einarfd**
This is pull requests fixes https://twistedmatrix.com/trac/ticket/8495

### CODE REVIEW

**Comment by rodrigc** [comment]
You need a topfile: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles

**Comment by adiroiban** [comment]
This branch comes with a topfile but instead of twisted/conch/8495.feature it should be twisted/conch/topfile/8495.feature

Otherwise, it looks good.

Many thanks!

**Comment by adiroiban** [comment]
I will create a branch in Twisted and will rename the topfile.

**Comment by adiroiban** [comment]
@einarfd for new, we are still testing GitHub PR integration, so all "official" comments and work is done in Trac and Twisted repo . See https://twistedmatrix.com/trac/ticket/8495

For example the current infrastructure only allows OSX, BSD, Fedora and Debian test to be executed from branches inside the Twisted main repo.

**Comment by adiroiban** [comment]
It was merged... as I have renamed the file before merge... so not this branch is left without being fully merged

**Pull request closed without merging**
