### PR TITLE
#11683 migrate sponsor doc page rst

### LINKED ISSUE #11683: Migrate twisted sponsors doc pages to RST/RTD
Describe any issue with the documentation or typos in the code:

- Currently the Sponsor pages is hosted on the Trac wiki archive. https://github.com/twisted/trac-wiki-archive/blob/trunk/TwistedSponsors.mediawiki
- We can move the relevant bits to RTD and migrate it to RST.

Note that our changes for our website are handled in the [twisted/twisted.github.io](https://github.com/twisted/twisted.github.io) repository.

- Once we've decided if the Sponsoring stuff is still relevant, we can modify the links on the twisted.org page.

### PR DESCRIPTION
**Pull request by JudgeGregg**
## Scope and purpose

Fixes #11683

Add a few words about why this PR is needed and what is its scope.
- Migrate Twisted Sponsors page to RST from old Trac Wiki.

Add any comments about trade-offs (if any) made in this PR and the reasoning behind them.
- So far I only added the founding sponsors. If we want to add "current" sponsors that's easy to do but I'm not sure they're relevant anymore.

Add mentions of things that are not covered here and are planed to be done in separate PRs.
- Still need to update the twisted.org site to link to the new RTD page.

## Contributor Checklist:

Below is a non-exhaustive list (as a reminder):

- [x] The title of the PR should describe the changes and starts with the associated issue number, like “#1234 Brief description”.
- [x] A release notes news fragment file was create in src/twisted/newsfragments/ (see: [Release notes fragments docs.](https://docs.twisted.org/en/latest/core/development/dev-process.html#release-notes-management))
* The automated tests were updated.
* Once all checks are green, request a review by leaving a comment that contains exactly the string `please review`.
  Our bot will trigger the review process, by applying the pending review label
  and requesting a review from the Twisted dev

### CODE REVIEW

**Comment by JudgeGregg** [comment]
please review

**Comment by adiroiban** [comment]
Thanks for the PR.

Just a helper for people reviewing this

The main page (kind of empty) is at https://twisted--11684.org.readthedocs.build/en/11684/sponsors/index.html

An extra "old sponsors" page is at https://twisted--11684.org.readthedocs.build/en/11684/sponsors/foundingsponsors.html

---------

I am -1 for this change in twisted/twisted.

It looks less like documentation and more like something that we should have on the main website https://github.com/twisted/twisted.github.io

---------

I hope that @glyph can help and provide feedback on whether we want to keep "archeological"  information in our documentation.

-----

Now it doesn't mean that this should not be part of the documentation, and if other Twisted devs want to have this info in the docs, I would not oppose it.

Regards

**Comment by JudgeGregg** [comment]
Thank you for the review.

Fair enough, it makes sense :)
I'm also migrating the success stories and projects pages. I imagine it should be considered "archeological" docs too ?
There is a "historical documents" section in the current doc. Would it be possible to host all those pages there ?

**Comment by adiroiban** [comment]
I don't know what is the policy for "Historical document"

The page starts with "Here are documents which contain no pertinent information or documentation."

--------

I am kind of -1 for adding any historical info the docs.

I think that we can leave this info archived inside https://github.com/twisted/trac-wiki-archive , as it already is.

We don't have/need to migrate the whole wiki to the documentation.

--------

it can just pop in the searches, and confuse people.

I would rather just create a https://github.com/twisted/historic repo and place all the fiels there...

Which we should do, since the links are broken

**Comment by glyph** [comment]
> I don't know what is the policy for "Historical document"

Yeah I don't think we have any particular policy.

**Comment by glyph** [comment]
> I am kind of -1 for adding any historical info the docs.

At one point in the past I believed almost religiously in never breaking links for any reason and keeping every document available forever, but many years of experience later I think that having outdated information available and easily searchable mostly just confuses people. We can keep historical documents for historical interest on the internet archive's wayback machine, no need to keep them online on our site and repo forever.

**Comment by JudgeGregg** [comment]
Thank you for your review :)

I've just opened:
https://github.com/twisted/twisted/pull/11714
to remove the historical docs from RTD.

Only one question remaining: the current website has links to outdated docs, e.g. sponsors. Should we remove these too ?
I'm thinking especially about: Wiki, Sponsors and Twisted Matrix Laboratories categories.
(at first I opened this PR because I found a bit weird that the main site was linking to trac wiki archives for these pages)

**Comment by adiroiban** [comment]
> (at first I opened this PR because I found a bit weird that the main site was linking to trac wiki archives for these pages)

the twisted.org website was created during the transition period.
It was created while the trac wiki was still up and running... as placeholder content.

For the long term, I think that website should be updated to only link to itself or to documentation pages.

We should no longer link to the wiki archives.

The links to the  wiki archive are for the transition.

-----------

I would say that this PR should be closed and not merged.

We still want to have a sponsors page, but I think that we want that sponsor page on the main website.

But first, we need to find sponsors, and before that we need to find an organization that we can use to collect the money from our sponsors.

-----------

and @glyph maybe we can relax the sponsorship criteria, and also consider sponsors the companies that are sponsoring development time or other resources

**Comment by glyph** [comment]
> and @glyph maybe we can relax the sponsorship criteria, and also consider sponsors the companies that are sponsoring development time or other resources

I'm open to this but it will require participation from the SFC, or migration to a different fiscal sponsor (ideally the PSF)

**Comment by adiroiban** [comment]
I have checked the [PSF website](https://www.python.org/psf/) and Wikipedia page  but it doesn't look like PSF offers the same service as SFC.

Regarding SFC, or requests with SFC are not answered in ears.

**Comment by glyph** [comment]
> I have checked the [PSF website](https://www.python.org/psf/) and Wikipedia page  but it doesn't look like PSF offers the same service as SFC.

Here's the relevant page: https://www.python.org/psf/fiscal-sponsorees/

**Pull request closed without merging**
