### PR TITLE
[WIP] Add python_requires to static package metadata

### PR DESCRIPTION
**Pull request by altendky**
https://twistedmatrix.com/trac/ticket/9701

## Contributor Checklist:

* [x] There is an associated ticket in Trac. Create a new one at https://twistedmatrix.com/trac/newticket
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [ ] ~~I have updated the automated tests.~~
  * Not planning on adding a job for an unsupported Python version to test this

### CODE REVIEW

**Comment by altendky** [comment]
I assume we don't want to add jobs to our CI for Python versions we don't support just to check this...  so no tests added.  I did locally try excluding 3.5, building an sdist `.tar.gz`, then installing that into a 3.5 virtualenv and got the following.

```
altendky@lt:~/twisted$ venv35/bin/pip install dist/Twisted-19.7.0.dev0.tar.gz 
Processing ./dist/Twisted-19.7.0.dev0.tar.gz
ERROR: Package 'Twisted' requires a different Python: 3.5.5 not in '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*'
```

Installing the same `.tar.gz` into a Python 3.7 virtualenv did work.

**Comment by rodrigc** [comment]
This looks OK.  What happens if you run this inside a Python 3.3 or 3.4 docker container:

https://hub.docker.com/_/python?tab=tags&page=1&name=3.4
https://hub.docker.com/_/python?tab=tags&page=1&name=3.3

**Comment by altendky** [comment]
@rodrigc, well, this isn't what I wanted to see.  I think when I did the above check I only adjusted the `python_requires` to be >=3.5 not the manual check function.  My apologies, that was a very poor test.  So, the manual check function is still being called.  Maybe the question is "do we need to support [setuptools<24.2.0](https://setuptools.readthedocs.io/en/latest/history.html#v24-2-0) from July 2016?"  If not then we can bank on the `python_requires` blocking appropriately and remove the manual check.

```
altendky@lt:~$ sudo docker run --rm -it python:3.3 python -m pip install https://5493-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.7.0.dev0.tar.gz
Collecting https://5493-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.7.0.dev0.tar.gz
  Downloading https://5493-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.7.0.dev0.tar.gz
     - 4.7MB 17.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-cbu4hv-build/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "<string>", line 259, in getSetupArgs
      File "<string>", line 210, in _checkPythonVersion
    ImportError: Twisted on Python 3 requires Python 3.5 or later.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-cbu4hv-build/
You are using pip version 9.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
```
altendky@lt:~$ sudo docker run --rm -it python:3.4 python -m pip install https://5493-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.7.0.dev0.tar.gz
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting https://5493-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.7.0.dev0.tar.gz
  Downloading https://5493-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.7.0.dev0.tar.gz
     | 4.5MB 9.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-icrgrr1u/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "<string>", line 259, in getSetupArgs
      File "<string>", line 210, in _checkPythonVersion
    ImportError: Twisted on Python 3 requires Python 3.5 or later.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-icrgrr1u/
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by altendky** [comment]
```
altendky@p1:/epc/twisted$ sudo docker run --rm -it python:2.7 python -m pip install https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
  Downloading https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
     / 4.5MB 2.7MB/s
Collecting zope.interface>=4.4.2
  Downloading https://files.pythonhosted.org/packages/d3/f0/521019b86fadc15272fd1229fbad811c4af5ad8f63a2ec604e0b50e7b473/zope.interface-4.7.1-cp27-cp27mu-manylinux2010_x86_64.whl (164kB)
     |████████████████████████████████| 174kB 1.1MB/s 
Collecting constantly>=15.1
  Downloading https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1
  Downloading https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0
  Downloading https://files.pythonhosted.org/packages/e5/11/756922e977bb296a79ccf38e8d45cafee446733157d59bcd751d3aee57f5/Automat-0.8.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1
  Downloading https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0
  Downloading https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl (52kB)
     |████████████████████████████████| 61kB 10.8MB/s 
Collecting attrs>=17.4.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from zope.interface>=4.4.2->Twisted==19.10.0.dev0) (41.6.0)
Collecting six
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting idna>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 10.8MB/s 
Building wheels for collected packages: Twisted
  Building wheel for Twisted (setup.py) ... done
  Created wheel for Twisted: filename=Twisted-19.10.0.dev0-cp27-cp27mu-linux_x86_64.whl size=3182406 sha256=14025c09a66cdc5b77591adcc314cc81f51572a8564143e98b7acbbe68451825
  Stored in directory: /root/.cache/pip/wheels/c1/bf/41/689a70bf3eac47e45b76cadd2089f8e4e31080da753e61ef8f
Successfully built Twisted
Installing collected packages: zope.interface, constantly, incremental, six, attrs, Automat, idna, hyperlink, PyHamcrest, Twisted
Successfully installed Automat-0.8.0 PyHamcrest-1.9.0 Twisted-19.10.0.dev0 attrs-19.3.0 constantly-15.1.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 six-1.13.0 zope.interface-4.7.1
```
```
altendky@p1:/epc/twisted$ sudo docker run --rm -it python:3.3 python -m pip install https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
Collecting https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
  Downloading https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
     | 4.8MB 9.7MB/s
Twisted requires Python '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*' but the running Python is 3.3.7
You are using pip version 9.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
```
altendky@p1:/epc/twisted$ sudo docker run --rm -it python:3.4 python -m pip install https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
  Downloading https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
     \ 4.8MB 24.7MB/s
Twisted requires Python '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*' but the running Python is 3.4.10
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
```
altendky@p1:/epc/twisted$ sudo docker run --rm -it python:3.5 python -m pip install https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
Collecting https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
  Downloading https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
     \ 4.4MB 1.2MB/s
Collecting zope.interface>=4.4.2
  Downloading https://files.pythonhosted.org/packages/8e/7f/f3fc9b32c107c6056594a36e430f0844a133e422083ad3b9f98f9fe3b8b3/zope.interface-4.7.1-cp35-cp35m-manylinux2010_x86_64.whl (168kB)
     |████████████████████████████████| 174kB 1.1MB/s 
Collecting constantly>=15.1
  Downloading https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1
  Downloading https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0
  Downloading https://files.pythonhosted.org/packages/e5/11/756922e977bb296a79ccf38e8d45cafee446733157d59bcd751d3aee57f5/Automat-0.8.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1
  Downloading https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0
  Downloading https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl (52kB)
     |████████████████████████████████| 61kB 13.1MB/s 
Collecting attrs>=17.4.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/site-packages (from zope.interface>=4.4.2->Twisted==19.10.0.dev0) (41.6.0)
Collecting six
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting idna>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 6.7MB/s 
Building wheels for collected packages: Twisted
  Building wheel for Twisted (setup.py) ... done
  Created wheel for Twisted: filename=Twisted-19.10.0.dev0-cp35-cp35m-linux_x86_64.whl size=3077147 sha256=dd5518e24ea6b4e3511a7a74306dd14ec354bd5fdec6823ee03da410bb47b2c0
  Stored in directory: /root/.cache/pip/wheels/c1/bf/41/689a70bf3eac47e45b76cadd2089f8e4e31080da753e61ef8f
Successfully built Twisted
Installing collected packages: zope.interface, constantly, incremental, six, attrs, Automat, idna, hyperlink, PyHamcrest, Twisted
Successfully installed Automat-0.8.0 PyHamcrest-1.9.0 Twisted-19.10.0.dev0 attrs-19.3.0 constantly-15.1.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 six-1.13.0 zope.interface-4.7.1
```
```
altendky@p1:/epc/twisted$ sudo docker run --rm -it python:3.6 python -m pip install https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
Collecting https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
  Downloading https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
     \ 4.8MB 2.9MB/s
Collecting zope.interface>=4.4.2
  Downloading https://files.pythonhosted.org/packages/05/16/79fe71428c91673194a21fedcc46f7f1349db799bc2a65da4ffdbe570343/zope.interface-4.7.1-cp36-cp36m-manylinux2010_x86_64.whl (168kB)
     |████████████████████████████████| 174kB 1.1MB/s 
Collecting constantly>=15.1
  Downloading https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1
  Downloading https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0
  Downloading https://files.pythonhosted.org/packages/e5/11/756922e977bb296a79ccf38e8d45cafee446733157d59bcd751d3aee57f5/Automat-0.8.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1
  Downloading https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0
  Downloading https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl (52kB)
     |████████████████████████████████| 61kB 17.0MB/s 
Collecting attrs>=17.4.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from zope.interface>=4.4.2->Twisted==19.10.0.dev0) (41.6.0)
Collecting six
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting idna>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 10.2MB/s 
Building wheels for collected packages: Twisted
  Building wheel for Twisted (setup.py) ... done
  Created wheel for Twisted: filename=Twisted-19.10.0.dev0-cp36-cp36m-linux_x86_64.whl size=3078333 sha256=12e5a90ef67ed242dd42109cebc8947acbfd120caee509bd180bacc59d6ddc3c
  Stored in directory: /root/.cache/pip/wheels/c1/bf/41/689a70bf3eac47e45b76cadd2089f8e4e31080da753e61ef8f
Successfully built Twisted
Installing collected packages: zope.interface, constantly, incremental, attrs, six, Automat, idna, hyperlink, PyHamcrest, Twisted
Successfully installed Automat-0.8.0 PyHamcrest-1.9.0 Twisted-19.10.0.dev0 attrs-19.3.0 constantly-15.1.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 six-1.13.0 zope.interface-4.7.1
```
```
altendky@p1:/epc/twisted$ sudo docker run --rm -it python:3.7 python -m pip install https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
Collecting https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
  Downloading https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
     | 4.5MB 1.7MB/s
Collecting zope.interface>=4.4.2
  Downloading https://files.pythonhosted.org/packages/40/e7/7e1060c2826d6b8c25bebbd1c96177f4b85ecfe3e2478d31acf9eaca3a11/zope.interface-4.7.1-cp37-cp37m-manylinux2010_x86_64.whl (169kB)
     |████████████████████████████████| 174kB 1.2MB/s 
Collecting constantly>=15.1
  Downloading https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1
  Downloading https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0
  Downloading https://files.pythonhosted.org/packages/e5/11/756922e977bb296a79ccf38e8d45cafee446733157d59bcd751d3aee57f5/Automat-0.8.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1
  Downloading https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0
  Downloading https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl (52kB)
     |████████████████████████████████| 61kB 18.3MB/s 
Collecting attrs>=17.4.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from zope.interface>=4.4.2->Twisted==19.10.0.dev0) (41.6.0)
Collecting six
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting idna>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 17.6MB/s 
Building wheels for collected packages: Twisted
  Building wheel for Twisted (setup.py) ... done
  Created wheel for Twisted: filename=Twisted-19.10.0.dev0-cp37-cp37m-linux_x86_64.whl size=3081566 sha256=f027d32d702a3193731c5c7d1c69a8bcaefa946bfbd73a2ffb0dcdc857ea701c
  Stored in directory: /root/.cache/pip/wheels/c1/bf/41/689a70bf3eac47e45b76cadd2089f8e4e31080da753e61ef8f
Successfully built Twisted
Installing collected packages: zope.interface, constantly, incremental, six, attrs, Automat, idna, hyperlink, PyHamcrest, Twisted
Successfully installed Automat-0.8.0 PyHamcrest-1.9.0 Twisted-19.10.0.dev0 attrs-19.3.0 constantly-15.1.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 six-1.13.0 zope.interface-4.7.1
```
```
altendky@p1:/epc/twisted$ sudo docker run --rm -it python:3.8 python -m pip install https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
Collecting https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
  Downloading https://5875-1985358-gh.circle-artifacts.com/0/home/circleci/linux-wheels/wheelhouse/Twisted-19.10.0.dev0.tar.gz
     - 4.7MB 3.0MB/s
Collecting zope.interface>=4.4.2
  Downloading https://files.pythonhosted.org/packages/c9/10/23dcfa9ce5c15cf898a64cba9b2153b546a2cf2f0adfe7b2890e8857268f/zope.interface-4.7.1-cp38-cp38-manylinux2010_x86_64.whl (174kB)
     |████████████████████████████████| 184kB 1.2MB/s 
Collecting constantly>=15.1
  Downloading https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1
  Downloading https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0
  Downloading https://files.pythonhosted.org/packages/e5/11/756922e977bb296a79ccf38e8d45cafee446733157d59bcd751d3aee57f5/Automat-0.8.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1
  Downloading https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0
  Downloading https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl (52kB)
     |████████████████████████████████| 61kB 22.8MB/s 
Collecting attrs>=17.4.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from zope.interface>=4.4.2->Twisted==19.10.0.dev0) (41.6.0)
Collecting six
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting idna>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 10.2MB/s 
Building wheels for collected packages: Twisted
  Building wheel for Twisted (setup.py) ... done
  Created wheel for Twisted: filename=Twisted-19.10.0.dev0-cp38-cp38-linux_x86_64.whl size=3081944 sha256=4087314bc62ef34fe515414b89e88f4947f2ef564c6ee6e0716bc4223099c0a2
  Stored in directory: /root/.cache/pip/wheels/c1/bf/41/689a70bf3eac47e45b76cadd2089f8e4e31080da753e61ef8f
Successfully built Twisted
Installing collected packages: zope.interface, constantly, incremental, attrs, six, Automat, idna, hyperlink, PyHamcrest, Twisted
Successfully installed Automat-0.8.0 PyHamcrest-1.9.0 Twisted-19.10.0.dev0 attrs-19.3.0 constantly-15.1.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 six-1.13.0 zope.interface-4.7.1
```

**Comment by wsanchez** [comment]
The Azure build errors look unrelated, but I don't know how to restart them.

**Review by wsanchez — APPROVED** [review]
Looks good.

**Comment by altendky** [comment]
Kick CI

**Pull request merged**
