### PR TITLE
[#9679] Adapt cancel exception type in Deferred.fromFuture 

### PR DESCRIPTION
**Pull request by Wiezzel**
Caller of `Deferred.cancel()` expects the cancelled deferred object to return `twisted.internet.defer.CancelledError`. On the other hand, calling `Future.cancel()` results in `asyncio.CancelledError`. This causes problems with deferred objects created with `Deferred.fromFuture()`. E.g. setting timeout for such objects won't work because `_cancelledToTimedOutError` only traps `twisted.internet.defer.CancelledError` and not `asyncio.CancelledError`. In order to resolve this issue exception type should be changed in `Deferred.fromFuture()`.

Issue: [9679](https://twistedmatrix.com/trac/ticket/9679)

## Contributor Checklist:

* [x] There is an associated ticket in Trac. Create a new one at https://twistedmatrix.com/trac/newticket
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests.

### CODE REVIEW

**Comment by Wiezzel** [comment]
Pylint fails **on a line I didn't even modify** and I don't know how to silence the error.

**Comment by glyph** [comment]
@Wiezzel I've submitted this for review over in Trac, since it seems to me you would like someone to look at it? 😄

**Comment by Wiezzel** [comment]
@glyph Yes, thank you very much.

**Comment by glyph** [comment]
@Wiezzel Sorry for the lack of clear documentation around that; I've submitted https://twistedmatrix.com/trac/ticket/9687 to try to address this gap in our PR template.

**Comment by Wiezzel** [comment]
@glyph Looks like the tests failed for unrelated reason. How do I re-schedule them to run again?

**Comment by glyph** [comment]
@Wiezzel Restarting the build on Azure unfortunately requires project membership, so I pushed the button for you. Looks like it passed!

**Comment by Wiezzel** [comment]
@glyph Great, thank you.

**Review by glyph — CHANGES_REQUESTED** [review]
See the review over on Trac: https://twistedmatrix.com/trac/ticket/9679#comment:3

**Pull request closed without merging**
