### PR TITLE
8700 einarfd py3 conch client default

### PR DESCRIPTION
**Pull request by einarfd**
This fixes https://twistedmatrix.com/trac/ticket/8700 and is a port of conch.client.default to Python 3, with some added tests and a very minor bug fix thrown in for good measure. 

Unfortunately stdin/stdout is marked different on the Python versions, so there are a couple of lines that are Python 3 specific, and the coverage of the patch will therefore not be a 100%.

### CODE REVIEW

**Comment by glyph** [comment]
Hi @einarfd ! Were you meaning to commit these with your Cisco email address?  If so you should really add it to your Github account.

**Comment by rodrigc** [comment]
@einarfd Thanks for doing this work.  I took your patch, and in a Python 3.5 virtual environment,
I enabled more warnings by doing:

```
python -bb -Wall bin/trial twisted.conch.test.test_default
```

I got these warnings:

```
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
Name
Instruction
    test_getGenericAnswers ...                                             [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
/Users/crodrigues/twisted_14/twisted/conch/client/default.py:274: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/tty' encoding='UTF-8'>
    test_getPassword ...                                                   [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
/Users/crodrigues/twisted_14/twisted/conch/client/default.py:172: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/tty' encoding='UTF-8'>

    test_getPasswordConchError ...                                         [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
/Users/crodrigues/twisted_14/twisted/conch/client/default.py:172: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/tty' encoding='UTF-8'>
    test_getPasswordPrompt ...                                             [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
/Users/crodrigues/twisted_14/twisted/conch/client/default.py:172: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/tty' encoding='UTF-8'>
    test_getPrivateKey ...                                                 [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:318: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py:95: BytesWarning: Comparison between bytes and string
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
    test_getPrivateKeyPassphrase ...                                       [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:318: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py:95: BytesWarning: Comparison between bytes and string
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:1049: DeprecationWarning: encodestring() is a deprecated alias, use encodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:305: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
    test_getPublicKeyAgentFallback ...                                     [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
    test_getPublicKeyBadKeyError ...                                       [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
    test_getPublicKeyFromFile ...                                          [OK]
/Users/crodrigues/twisted_14/twisted/conch/ssh/keys.py:233: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
/Users/crodrigues/twisted_14/twisted/python/usage.py:971: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

Since you are bravely cleaning up all this conch code,
do you want to take a whack at eliminating some of these warnings,
and make it part of your patch?  Changing decodestring() to decodebytes() should be easy.
Fixing the ResourceWarning would be helpful ( if you need to, consider using a context manager
when opening a file, so that it gets closed).
inspect.getargspec() vs. inspect.signature() will require some finesse, since inspect.signature()
is not on Python 2.7.

**Comment by rodrigc** [comment]
@einarfd I submitted a separate ticket for removing the inspect.getargspec() warning:
https://github.com/twisted/twisted/pull/442

so you can leave that one out of your patch.  But if you can fix the other conch related warnings
that get triggered with test_default.py, that would be great.

**Comment by einarfd** [comment]
I'll have a look at that when I get back on Monday.

**Comment by einarfd** [comment]
I've fixed the decodebytes and closing file stream issues, and as far as I know there shouldn't be any outstanding issues.

**Comment by rodrigc** [comment]
I took a look at your branch, and ran the test with the Python unittest framework, since in this
case, it seems to be easier to see the warnings than trial:

```
 python   -bb  -Wall -m unittest twisted.conch.test.test_default
```

I saw a lot of warnings like this:

```
/Users/crodrigues/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py:95: BytesWarning: Comparison between bytes and string
```

I could figure out where in the Twisted code was causing these warnings, so I put an assert on line 94 of decoder.py.
I found the stack came to this line: https://github.com/twisted/twisted/blob/trunk/twisted/conch/ssh/keys.py#L321

It looks like for pyasn1.codec.ber.decoder(), you aren't supposed to pass it
a bytes directly, but are supposed to wrap the bytes in something else such as a univ.OctetString

http://pyasn1.sourceforge.net/codecs.html#2.2

Well anyways, it looks like twisted/twisted/blob/trunk/twisted/conch/ssh/keys.py has
some problems with how it handles bytes vs. strings, and is not 100% Python 3 clean.

However, cleaning that file up looks like a separate job.
I think the changes you have done in this PR are good,
so I will review and test them out some more, and if it looks all good, I'll merge.

I don't know if you have any interest in doing more cleaning of keys.py or other
areas of conch. :)

Thank you for your contributions!

**Comment by rodrigc** [comment]
@einarfd I merged your change, and while it passed travis, it failed on the buildbots, which I did not notice until now: https://buildbot.twistedmatrix.com/builders/fedora22-py2.7/builds/1191

So it turns out that if I execute the test via the command-line, it works.

However, if I execute over SSH, it fails.

Here is what I did.  I created this script  test_it.sh:

```
#!/bin/sh


. ~/venv/bin/activate
cd ~/twisted11/
python -m unittest twisted.conch.test.test_default
```

Then instead of executing the script locally, I did:

```
ssh mybox "sh ./test_it.sh"
```

And I got the same failure as on the buildbot:

```
======================================================================
ERROR: test_getPasswordPrompt (twisted.conch.test.test_default.SSHUserAuthClientTests)
test_getPasswordPrompt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/crodrigues/twisted11/twisted/internet/defer.py", line 149, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/crodrigues/twisted11/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/Users/crodrigues/twisted11/twisted/python/compat.py", line 433, in reraise
    raise exception.with_traceback(traceback)
  File "/Users/crodrigues/twisted11/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/Users/crodrigues/twisted11/twisted/conch/test/test_default.py", line 232, in test_getPasswordPrompt
    d = client.getPassword(prompt)
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 182, in getPassword
    p = self._getPassword(prompt).encode(sys.getdefaultencoding())
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 164, in _getPassword
    with self._replaceStdoutStdin():
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 294, in _replaceStdoutStdin
    sys.stdin, sys.stdout = cls._openTty()
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 278, in _openTty
    stdin = open("/dev/tty", "rb")
OSError: [Errno 6] Device not configured: '/dev/tty'

----------------------------------------------------------------------
```

It turns out that we should not open /dev/tty if we are not in an interactive tty.

Luckily we can check.  If

sys.stdin.isatty()  or sys.stdout.isatty() return False,
then we should skip the test.

If you type this from the command-line:

python -c "import sys; print(sys.stdout.isatty())"

You get:

True

But if you do:

ssh myhost "python -c 'import sys; print(sys.stdout.isatty())'"

you get:

False

**Comment by glyph** [comment]
If this was a bad merge that causes buildbots to fail, we should revert it.  However, I am coming to learn that this is not as trivial as I thought :).

**Comment by glyph** [comment]
OK, I think I figured out reverting with git (odd that the PR doesn't mention the ultimate commit ID generated by the merge?) but 'reopens' is still broken.

**Comment by rodrigc** [comment]
It was not a bad merge, it is just that @einarfd exposed a subtle difference in behavior
between Travis and the buildbots that I missed during my review.

On Travis "sys.stdin.isatty() == True" there,
but when executing the test on the buildbot over ssh, "sys.stdin.isatty() == False".
There were only 4 tests failing on the buildbot,
and I have a fix for them here: 
https://github.com/twisted/twisted/commit/eb53e2ef803b74d66241060a7a4410c3c4dcf301

The buildbots are running here:
https://buildbot.twistedmatrix.com/boxes-supported?branch=8700-einarfd-py3-conch-client-default-3

and Travis is here:
https://travis-ci.org/twisted/twisted/builds/149082901

**Comment by glyph** [comment]
@rodrigc @einarfd -

> It was not a bad merge […]

I guess that was somewhat ambiguous of me - I meant "bad merge" only in the sense that it is a merge that met the qualifications for a revert according to the review policy (there was a missed detail, which caused a test regression). But that's why we have the policy around reverts - we're all only human :).

Although I would very much like to rewrite the doc so the next person who has to do one doesn't spend an hour thrashing around on the command-line like I did; is the left, or "1" parent always the mainline?  I _think_ so, but I'm not quite sure how to tell...

**Comment by einarfd** [comment]
I didn't think that /dev/tty could be missing, but in hindsight it is obvious that it can. 
Should I create a new merge request fixing the problem, or do you @rodrigc have something in the pipeline?

**Comment by rodrigc** [comment]
@einarfd I have a fix for this.  Please review https://github.com/twisted/twisted/pull/454
glyph already performed a review and I am in the process of incorporating his feedback
(primarily cosmetic fixes), but I would appreciate your review as well.

Thanks for your contributions to port conch to Python 3!

**Pull request merged**
