### PR TITLE
Add type annotations to AMP.

### PR DESCRIPTION
**Pull request by jothan**
Follow up to #1417 with only the type annotations.

Sorry @glyph , I could not get overload to work for callRemoteString. I
hit this issue: https://github.com/python/mypy/issues/8656

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10031
* [x] I ran `tox -e black-reformat` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [ ] I ran additional checks listed at [Getting Your Patch Accepted](https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [ ] I have updated the automated tests.
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Comment by glyph** [comment]
This type-checks for me; how did you type it?

```python3

from typing import Optional, Literal, overload

@overload
def a(flag: Literal[True]) -> None:
    ...

@overload
def a(flag: Literal[False]) -> int:
    ...

def a(flag: bool) -> Optional[int]:
    if flag:
        return None
    else:
        return 7


a(False) + 3

```

**Comment by jothan** [comment]
> This type-checks for me; how did you type it?
> 
> ```python
> from typing import Optional, Literal, overload
> 
> @overload
> def a(flag: Literal[True]) -> None:
>     ...
> 
> @overload
> def a(flag: Literal[False]) -> int:
>     ...
> 
> def a(flag: bool) -> Optional[int]:
>     if flag:
>         return None
>     else:
>         return 7
> 
> 
> a(False) + 3
> ```

Can you make it work with a default value for the flag ?

**Comment by glyph** [comment]
Yep, here you go:

```python3

from typing import Optional, Literal, overload

@overload
def a(flag: Literal[True]) -> None:
    ...

@overload
def a(flag: Literal[False]=False) -> int:
    ...


def a(flag: bool = False) -> Optional[int]:
    if flag:
        return None
    else:
        return 7


a() + 3
```

**Comment by jothan** [comment]
> Yep, here you go:
> 
> ```python
> from typing import Optional, Literal, overload
> 
> @overload
> def a(flag: Literal[True]) -> None:
>     ...
> 
> @overload
> def a(flag: Literal[False]=False) -> int:
>     ...
> 
> 
> def a(flag: bool = False) -> Optional[int]:
>     if flag:
>         return None
>     else:
>         return 7
> 
> 
> a() + 3
> ```

Applying the same recipe to callRemoteString:
```python
    @overload
    def callRemoteString(
        self, command: bytes, requiresAnswer: Literal[False], **kw: bytes
    ) -> None:
        ...

    @overload
    def callRemoteString(
        self, command: bytes, requiresAnswer: Literal[True] = True, **kw: bytes
    ) -> Deferred:
        ...

    def callRemoteString(
        self, command: bytes, requiresAnswer: bool = True, **kw: bytes
    ) -> Optional[Deferred]:
```

I get this error:
```
src/twisted/protocols/amp.py:883:5: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]
        def callRemoteString(
```

**Comment by glyph** [comment]
This diff from the tip of your branch:

```diff
1 file changed, 24 insertions(+), 1 deletion(-)
src/twisted/protocols/amp.py | 25 ++++++++++++++++++++++++-

modified   src/twisted/protocols/amp.py
@@ -203,7 +203,18 @@ from io import BytesIO
 from itertools import count
 from struct import pack
 from types import MethodType
-from typing import Any, Callable, Dict, List, Optional, Tuple, Type, Union
+from typing import (
+    Any,
+    Callable,
+    Dict,
+    List,
+    Optional,
+    Tuple,
+    Type,
+    Union,
+    overload,
+    Literal,
+)
 import warnings
 
 from zope.interface import Interface, implementer
@@ -878,6 +889,18 @@ class BoxDispatcher:
 
         return result
 
+    @overload
+    def callRemoteString(
+        self, command: bytes, requiresAnswer: Literal[True] = True, **kw: bytes
+    ) -> Deferred:
+        ...
+
+    @overload
+    def callRemoteString(
+        self, command: bytes, requiresAnswer: Literal[False], **kw: bytes
+    ) -> None:
+        ...
+
     def callRemoteString(
         self, command: bytes, requiresAnswer: bool = True, **kw: bytes
     ) -> Optional[Deferred]:
```

results in this:

```
$ tox --develop -q -e mypy
Success: no issues found in 837 source files
___________________________________________________________ summary ___________________________________________________________
  mypy: commands succeeded
  congratulations :)
```

This version of mypy (or maybe the zope plugin, not sure) is constantly corrupting its own cache though, so I was getting weird errors unless I removed `.tox` after every run.

**Comment by jothan** [comment]
I'm on Python 3.6 so I was doing ```from typing_extension import Literal``` when it should have been ```from typing_extensions import Literal``` (note the added "s").

mypy is now happy. I will add the commit containing the correction in a few minutes.

**Comment by glyph** [comment]
> I'm on Python 3.6 so I was doing `from typing_extension import Literal` when it should have been `from typing_extensions import Literal` (note the added "s").
> 
> mypy is now happy. I will add the commit containing the correction in a few minutes.

woohoo, thanks for figuring that out!

**Comment by mthuurne** [comment]
> I'm on Python 3.6 so I was doing `from typing_extension import Literal` when it should have been `from typing_extensions import Literal` (note the added "s").

This typo wasn't reported by mypy because `ignore_missing_imports = True` exists as a global setting. It would be better to add ignores for specific packages that Twisted needs and that don't have type annotation support (yet). See [`mypy.ini` from pydoctor](https://github.com/twisted/pydoctor/blob/master/mypy.ini) for an example.

**Comment by wiml** [comment]
@jothan This looks good to me with a couple of tweaks:

* Twisted's min python version is 3.6 now, so we've moved to PEP526-style variable type annotations; if you want to run `com2ann` or simply fast-forward-merge [my sub-PR into your branch](https://github.com/zerospam/twisted/pull/1) that will update the annotation style;
* it needs to be merged (or rebased or etc) onto current twisted trunk for a CI check to run (although everything looks good running tox locally)

**Pull request closed without merging**
