### PR TITLE
One new, one renamed test. Updated docstrings post-review

### PR DESCRIPTION
**Pull request by donalm**
Majors:
1. Replaced the test_setLastModified3807 method with two more generically-named test cases
2. Rewrote the docstrings to more accurately describe what the code tests for
3. Rewrote the docstring and added a method to test for the second case

Minors:
1. Rephrased docstrings

Many thanks @adiroiban for the review

### CODE REVIEW

**Comment by rodrigc** [comment]
@donalm is this for http://twistedmatrix.com/trac/ticket/3807 ?

**Comment by donalm** [comment]
Yes - exactly that.

**Comment by rodrigc** [comment]
Alright.  In future, please try to update the Trac ticket with a reference to the PR.
Twisted project is still in transition, so Twisted devs still look at the review queue in Trac.  To save you some time I updated http://twistedmatrix.com/trac/ticket/3807 and put it in **review** state.

**Comment by donalm** [comment]
Aha! Will do - thanks @rodrigc

**Comment by adiroiban** [comment]
Also, GitHub reporting is a mess... I have tons of notifications from Twisted and then other tons for my project ... and if I read a notification there is no way to "un-read" it or to mark it as important so that I can follow up later

For now, Trac review queue report is the best I can have :)

**Pull request merged**
