### PR TITLE
Minor typo fix in _sentence.py

### PR DESCRIPTION
**Pull request by Akasurde**
Fix typo from 'presentAttribues' to 'presentAttributes'

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Review by rodrigc — APPROVED** [review]
Thanks for the fix

**Comment by Akasurde** [comment]
@rodrigc Thanks for review.

**Comment by rodrigc** [comment]
Next time you submit a PR to Twisted, please follow all the steps at: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

you omitted several steps like creating a ticket in Trac.  For now, I did that for you.

**Comment by Akasurde** [comment]
Yes. Sure. I will keep that in my mind.

**Pull request merged**
