### PR TITLE
[9915] fix threading.rst grammar

### PR DESCRIPTION
**Pull request by graingert**
## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9915
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [ ] I have updated the automated tests.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.
```

### CODE REVIEW

**Comment by twm** [comment]
@graingert If you'd add a .misc newsfile I'd be happy to review and merge this.

**Review by twm — APPROVED** [review]

**Comment by wiml** [comment]
`check-manifest` is unhappy with the newsfragment. Anyone know what should change here?

```
lists of files in version control and sdist do not match!
missing from sdist:
  docs/newsfragments/9915.misc
suggested MANIFEST.in rules:
  recursive-include docs *.misc
ERROR: InvocationError for command /home/runner/work/twisted/twisted/.tox/release-prepare/bin/check-manifest  
```

**Comment by twm** [comment]
@wiml It looks like the newsfragment has the path `docs/newsfragments/9915.misc` but `docs/newsfragments` isn't a thing. It should be `src/twisted/newsfragments/9915.misc`.

**Comment by twm** [comment]
I'm going to close this and create a fresh PR that does more thorough copyediting.

**Pull request closed without merging**
