### PR TITLE
#11707 fix `trial -j` / ctrl-c interaction

### LINKED ISSUE #10340: `trial -jN ...` reports a traceback when interrupted with Ctrl+C
|[exarkun's avatar](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#10340|
|Type|enhancement|
|Created|2022-05-03 14:19:54Z|

From 
https://github.com/twisted/twisted/pull/1726#pullrequestreview-959084307

hitting Ctrl+C while disttrial is running:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adi/chevah/twisted/src/twisted/trial/__main__.py", line 9, in <module>
    sys.exit(load_entry_point("Twisted", "console_scripts", "trial")())
  File "/home/adi/chevah/twisted/src/twisted/scripts/trial.py", line 652, in run
    test_result = trialRunner.runUntilFailure(suite)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 454, in runUntilFailure
    return self.run(suite, untilFailure=True)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 436, in run
    if isinstance(result, Failure):
UnboundLocalError: local variable 'result' referenced before assignment
```

It would be nice to exit cleanly with a partial result, instead.

<details><summary>Searchable metadata</summary>

```
trac-id__10340 10340
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1651587594761030 1651587594761030
changetime__1651587594761030 1651587594761030
version__None None
owner__None None

```
</details>

### LINKED ISSUE #11707: `UnboundLocalError` exception when exiting `trial -j` via an interrupt (i.e. ctrl-C)
running `trial --reporter=bwverbose -j 10 twisted.internet.test` for unrelated reasons:

`trial --reporter=bwverbose -j 10 twisted.internet.test`

```
^CTraceback (most recent call last):
  File "/Users/glyph/.virtualenvs/Twisted/bin/trial", line 8, in <module>
    sys.exit(run())
  File "/Users/glyph/Projects/Twisted/src/twisted/scripts/trial.py", line 647, in run
    testResult = trialRunner.run(suite)
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_dist/disttrial.py", line 473, in run
    return self._run(test, untilFailure=False)
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_dist/disttrial.py", line 455, in _run
    if isinstance(result, Failure):
UnboundLocalError: local variable 'result' referenced before assignment
```

### PR DESCRIPTION
**Pull request by glyph**
## Scope and purpose

Fixes #11707

### CODE REVIEW

**Comment by glyph** [comment]
review please

**Comment by adiroiban** [comment]
Hi @glyph 

Thanks for looking into this.

I am not sure what is an acceptable fix for this PR.

I am just doing a "manual test here"

The `UnboundLocalError: local variable 'result' referenced before assignment` error is no longer raised.

And there is a final run report.

I still see tracebacks.

With -j8 I was expecting to see up to 8 errors...but it looks like any tests after Ctrl+C fails.

```

$ git log -1
commit 79771895a959305e8d7c25188fce19380b2f2af6 (HEAD -> 11707-trial-ctrl-c-unbound-local, origin/11707-trial-ctrl-c-unbound-local)
Author: Glyph <code@glyph.im>
Date:   Fri Jul 21 13:21:31 2023 -0700

    simplify / hard-code assumption even further

$ trial -j 8 twisted.conch

PRESS CTRL+C after a few tests were executed

twisted.conch.test.test_window.ScrolledAreaTests.test_parent
twisted.conch.test.test_window.TopWindowTests.test_paintScheduling
-------------------------------------------------------------------------------
Ran 1069 tests in 3.881s

FAILED (skips=1, errors=918, successes=157)
joining disttrial worker #0 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #3 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #4 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #6 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.


```







```

Press Ctrl+C before any tests is executed... just shortly after staring trial -j 8

Ran 1069 tests in 0.201s

FAILED (errors=1069)
joining disttrial worker #0 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #1 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #2 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #3 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #4 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #5 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #6 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

joining disttrial worker #7 failed
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in join
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 142, in <listcomp>
    [Deferred.fromCoroutine(worker.exit()) for worker in self.workers],
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1346, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2154, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1994, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 396, in exit
    raise NotRunning()
twisted.trial._dist.worker.NotRunning: 

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.

Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 2.
```

--------------------

Now, I guess that some tracebacks are expected since I also get a traceback for a single process run

```
$ trial twisted.conch

PRESS CTRL+C after a few tests were executed

  UnimplementedVersionOneServerTests
    test_agentc_REMOVE_ALL_RSA_IDENTITIES ... ^C                          [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/conch/test/test_agent.py", line 60, in setUp
    self.rsaPrivate = keys.Key.fromString(keydata.privateRSA_openssh)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 218, in fromString
    return method(data, passphrase)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 546, in _fromString_PRIVATE_OPENSSH
    return cls._fromPrivateOpenSSH_PEM(data, passphrase)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 508, in _fromPrivateOpenSSH_PEM
    key = load_pem_private_key(data, passphrase, default_backend())
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 24, in load_pem_private_key
    return ossl.load_pem_private_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 957, in load_pem_private_key
    return self._load_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1165, in _load_key
    return self._evp_pkey_to_private_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 665, in _evp_pkey_to_private_key
    return _RSAPrivateKey(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 381, in __init__
    res = backend._lib.RSA_check_key(rsa_cdata)
builtins.KeyboardInterrupt: 

twisted.conch.test.test_agent.UnimplementedVersionOneServerTests.test_agentc_REMOVE_ALL_RSA_IDENTITIES
-------------------------------------------------------------------------------
Ran 19 tests in 0.975s

FAILED (errors=1, successes=18)
```

**Comment by glyph** [comment]
> With -j8 I was expecting to see up to 8 errors...but it looks like any tests after Ctrl+C fails.

Yeah, with the current structure of `trial -j`, this is the "correct" behavior, since the tests are gathered and then executed in separate passes, and so the tests that have already been gathered have to report some status.

**Comment by glyph** [comment]
> I am not sure what is an acceptable fix for this PR.
> 
> I am just doing a "manual test here"
> 
> The `UnboundLocalError: local variable 'result' referenced before assignment` error is no longer raised.
> 
> And there is a final run report.
> 
> I still see tracebacks.

Hmm. Okay, at the very least, the description given in the newsfile is inaccurate.  I'll update that to describe the change in better detail.

However, the scope of this fix really is just to get rid of the `UnboundLocalError` which is just a bug no matter what we want the error-reporting behavior to be upon interruption. There are future enhancements here that could vastly improve the error output but seeing lots of tracebacks is IMHO the preferable option.

**Comment by glyph** [comment]
@adiroiban I've updated the release news to include a better description of the actual behavior change, but I don't think there's more to be done implementation-wise here. I think we should possibly have a whole error-handling pass to deal with hung tests & interruptions in disttrial, but that is a much broader scope of work :)

**Review by adiroiban — APPROVED** [review]
So... #11707 is fixed.

Not sure about #10340 ... there is still a traceback obfuscating the real traceback

I agree that this PR can be merged as it is.

Maybe also rename the title of the PR to

`#11707 Fix trial -j / ctrl-c interaction with bwreporter`


If I apply this diff (which is not a fix)... somethings the final tracebacks go away

So maybe #10340 should be kept open


```diff
diff --git a/src/twisted/trial/_dist/worker.py b/src/twisted/trial/_dist/worker.py
index 04c39fc855..7dd0823566 100644
--- a/src/twisted/trial/_dist/worker.py
+++ b/src/twisted/trial/_dist/worker.py
@@ -330,7 +330,10 @@ class LocalWorkerTransport:
         """
         Forward data to transport.
         """
-        self._transport.writeToChild(_WORKER_AMP_STDIN, data)
+        try:
+            self._transport.writeToChild(_WORKER_AMP_STDIN, data)
+        except KeyError:
+            pass
 
     def writeSequence(self, sequence):
         """
@@ -392,6 +395,7 @@ class LocalWorker(ProcessProtocol):
         """
         Cause the worker process to exit.
         """
+        import time; time.sleep(0.5)
         if self.transport is None:
             raise NotRunning()
```

**Comment by glyph** [comment]
> ```diff
> +        import time; time.sleep(0.5)
> ```

what's going on here? :)

**Comment by glyph** [comment]
> If I apply this diff (which is not a fix)... somethings the final tracebacks go away

OK, let's perhaps open a new sub-issue of #10340 to address some of the new tracebacks once this lands.

**Pull request merged**
