### PR TITLE
Introducing Twisted Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Twisted Guru](https://gurubase.io/g/twisted) to Gurubase. Twisted Guru uses the data from this repo and data from the [docs](https://docs.twisted.org/en/stable/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Twisted Guru", which highlights that Twisted now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Twisted Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by glyph** [comment]
Please disable Twisted on gurubase.

**Comment by adiroiban** [comment]
Thanks for considering adding support for Twisted to your service.

I am -1 on merging the PR as I don't think that Gurubase.io is good enought ... yet.

See my example with creating a SFTP server for Windows... btw. The SFTP server for Linux answer wasn't that bad.

I am happy to reconder this in the future. 



------------

Just asking. Where is the harm in having services like Gurubase.io ?

Not sure under which license we have the content of GitHub issues ... but I guess the MIT licenes allows using the source to train an algorithm.

----------

I tested a few questions and they were hit and miss

For example, this is a big miss https://gurubase.io/g/twisted/create-sftp-server-windows-twisted  ... as Twisted no longer supported Python 3.6 ... and PyCrypto is no longer needed


but sites like StackOverflow are full of outdated answers

**Comment by itamarst** [comment]
StackOverflow has a date on the answer, at least, this will not. Stackoverflow lets you add new answers and say "that other answer is obsolete". Also it has a voting mechanism.

Another example: https://mastodon.social/@mcc/113427090808707362

Also I have gotten made-up APIs out of random Google search results from the AI, I assume this will do the same. It's a recipe for confused users and bad "bug" reports.

**Comment by glyph** [comment]
> Just asking. Where is the harm in having services like Gurubase.io ?

Our documentation is currently quite bad, so it might seem like anything that could help people make sense of it would be helpful. But LLMs cause a whole host of problems. More importantly though, our documentation problems are *our problems* that we are able to solve by updating the docs and directing people to the new versions. LLM training data is going to include old versions, other libraries, and even if it's fine-tuned on the most recent version of the documentation, it is fundamentally *not* under our control, which means it is very discouraging to work on big updates to the documentation even if we have time. To the extent that gurubase can be made better, it is stealing the work of our documentation writers who don't get any credit for having improved it, because it won't cite them; but it can jumble their work together and make it worse too.

**Comment by kursataktas** [comment]
Thank you for the feedback, everyone. I have disabled the Twisted Guru as requested.

I've reviewed some of the issues you raised, and you are correct; there are indeed some hallucinations. We are continuously working to make our system more robust. If you’d like, I would be happy to update you on a new release to give it another chance.

I also noticed a few inconsistencies. For instance, @adiroiban mentioned that Twisted no longer supports Python 3.6, but the current README states that it does.
image

I can also offer you the option to maintain Twisted Guru through a management panel, where you can add or remove data sources. Let me know if this is something you’re interested in.

**Comment by glyph** [comment]
Thanks for your prompt reply @kursataktas . I think LLMs are inherently unsuited to this task. If you can address all the structural problems with license violations and removal of credit, as well as demonstrate clear utility on other projects that do not agree with us here, it is possible that you will eventually convince us to re-enable it. But I am extremely doubtful.

**Pull request closed without merging**
