### PR TITLE
Omit default content-type for responses with no body.

### PR DESCRIPTION
**Pull request by Lukasa**
See: https://twistedmatrix.com/trac/ticket/9191

### CODE REVIEW

**Review by wsanchez — APPROVED** [review]

**Comment by glyph** [comment]
Hmm. Why didn't codecov have an opinion on this?

**Comment by Lukasa** [comment]
Maybe because a builder failed?

**Comment by glyph** [comment]
Wait do *all* the builders have to succeed for coverage to be reported?

**Comment by Lukasa** [comment]
Not sure. It certainly *can* be required.

**Comment by rodrigc** [comment]
I think @adiroiban knows more about this since he set up most of the codecov integration.

For example, I think if a project has 6 submissions to codecov within a short time interval,
and then the next time codecov receives 4 submissions, then codecov will wait until it receives the "missing" codecov submissions before generating the final coverage report.  This isn't always consistent.

**Comment by adiroiban** [comment]
See https://docs.codecov.io/docs/merging-reports#section-how-does-codecov-know-when-to-send-notifications-

From my experience, for projects with big coverage files, the observed behaviour is not the one described in the documentation.

I think that when sending reports of over 3 MB the codecov workers might crash and you will never see a report.

**Comment by glyph** [comment]
I wonder if mentioning @codecov here might help. Really? 3MB coverage reports just crash it?

**Comment by glyph** [comment]
So, `buildbot/` statuses are never reported as "pending", which might explain some of our flakiness in terms of what gets reported.

**Comment by adiroiban** [comment]
Good observation. There might be an older version in use... or some other errors.
I am also using buildbot (latest eight branch) and the pending status is reported as soon as the build starts

**Pull request merged**
