### PR TITLE
[#9093] A few more h2.errors instances in twisted

### PR DESCRIPTION
**Pull request by alexwlchan**
/me gnashes teeth

Okay, I think this is the final bit. Over to @Lukasa for review. Related to #751.

https://twistedmatrix.com/trac/ticket/9093

### CODE REVIEW

**Comment by Lukasa** [comment]
As ticket 9092 is fixed, you'll need to open a new one I'm afraid. :(

**Comment by alexwlchan** [comment]
> As ticket 9092 is fixed, you'll need to open a new one I'm afraid.

Whaaaaaaaat. Such effort. Much hard. Anyway, done.

> Okay, I think this is the final bit.

This time I’ve grepped the entire codebase for "h2.errors" and "h2.settings", rather than just going on the Travis output. I don’t see anywhere else that needs to change.

**Comment by Lukasa** [comment]
Heh, that seems like the best long-term approach. :grin:

**Review by Lukasa — APPROVED** [review]
LGTM. When the builders are green we'll be good to go.

**Pull request merged**
