### PR TITLE
[9217] Build lots of wheels

### PR DESCRIPTION
**Pull request by altendky**
https://twistedmatrix.com/trac/ticket/9217

https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

#### Work to do:
- [ ] ~~Storage for Travis artifacts~~
  - Using Circle for now
- [x] Get `cibuildwheel` working on CircleCI for OSX wheels
- [ ] ~~Learn about how Twisted likes to deploy wheels~~
  - ~~Maybe automate deployment if interested)~~
    - I did do PyPi deployment from Travis for a project
    - [Glyph is interested](https://twistedmatrix.com/pipermail/twisted-python/2018-September/032050.html) but I'd suggest a separate PR
  - Automatic deployment will be addressed separately
- [x] Resolve test failure on `twisted.cred.test.test_strcred.SSHCheckerTests.test_isChecker` (https://github.com/twisted/twisted/pull/1051#issuecomment-416977723)
  - Passing now
- [x] Use a released version of `cibuildwheel` (probably within the week)
- [x] Build 3.7 wheels
  - Some way to not fail the whole build on their failure right now?

### CODE REVIEW

**Comment by altendky** [comment]
Looks like they are building now for Windows and Linux.

[AppVeyor log](https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-5294/job/w1r6kmp26usv2ud9#L892)
[AppVeyor artifacts](https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-5294/job/w1r6kmp26usv2ud9/artifacts)
```
Twisted-18.7.0.dev0-cp27-cp27m-win32.whl
Twisted-18.7.0.dev0-cp27-cp27m-win_amd64.whl
Twisted-18.7.0.dev0-cp34-cp34m-win32.whl
Twisted-18.7.0.dev0-cp34-cp34m-win_amd64.whl
Twisted-18.7.0.dev0-cp35-cp35m-win32.whl
Twisted-18.7.0.dev0-cp35-cp35m-win_amd64.whl
Twisted-18.7.0.dev0-cp36-cp36m-win32.whl
Twisted-18.7.0.dev0-cp36-cp36m-win_amd64.whl
```

[Travis log](https://travis-ci.org/twisted/twisted/jobs/421743219#L1329)
```
Twisted-18.7.0.dev0-cp27-cp27m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp27-cp27m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp27-cp27mu-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp27-cp27mu-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp34-cp34m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp34-cp34m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp35-cp35m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp35-cp35m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp36-cp36m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
```

Aside from making sure they actually work and this is a sensible set of wheels...  the big pieces I have in mind are:

**edit:** merged checklist above

**Comment by altendky** [comment]
And now for OSX...

[CircleCI](https://circleci.com/gh/twisted/twisted/1832#artifacts/containers/0)
```
Twisted-18.7.0.dev0-cp27-cp27m-macosx_10_6_intel.whl
Twisted-18.7.0.dev0-cp34-cp34m-macosx_10_6_intel.whl
Twisted-18.7.0.dev0-cp35-cp35m-macosx_10_6_intel.whl
Twisted-18.7.0.dev0-cp36-cp36m-macosx_10_6_intel.whl
```

**Comment by altendky** [comment]
I tried a wheel on Windows and got help trying out on OSX.  No Linux wheel tests as I don't have artifact storage setup for Travis.  Both in Windows and OSX there's a single test failing.  I should setup a script to improve consistency and traceability of these checks but I have not yet.

https://gist.github.com/altendky/fd9b970c04546ee26a4a8319403b2837
https://gist.githubusercontent.com/nedbat/4259c4ffd791f4e1a97573c11ba9d9ea/raw/02076715994d2d8bb235ac9548126c991b3f5f01/something.txt

```python-traceback
[ERROR]
Traceback (most recent call last):
  File "C:\epc\tw\venv\lib\site-packages\twisted\cred\test\test_strcred.py", line 453, in test_isChecker
    sshChecker = strcred.makeChecker('sshkey')
  File "C:\epc\tw\venv\lib\site-packages\twisted\cred\strcred.py", line 129, in makeChecker
    return findCheckerFactory(authType).generateChecker(argstring)
  File "C:\epc\tw\venv\lib\site-packages\twisted\cred\strcred.py", line 114, in findCheckerFactory
    raise InvalidAuthType(authType)
twisted.cred.strcred.InvalidAuthType: sshkey

twisted.cred.test.test_strcred.SSHCheckerTests.test_isChecker
-------------------------------------------------------------------------------
Ran 11813 tests in 463.266s

FAILED (skips=2726, errors=1, successes=9086)
```

https://github.com/twisted/twisted/blob/2b23b00a86a4282df910f60489d1c4f8927b9784/src/twisted/cred/test/test_strcred.py#L448-L456
https://github.com/twisted/twisted/blob/2b23b00a86a4282df910f60489d1c4f8927b9784/src/twisted/plugins/cred_sshkeys.py#L29-L45

**Comment by altendky** [comment]
And now accessible Linux wheel artifacts thanks to CircleCI providing storage...

### Linux
[Circle](https://circleci.com/gh/twisted/twisted/1913#artifacts/containers/0)
```
Twisted-18.7.0.dev0-cp27-cp27m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp27-cp27m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp27-cp27mu-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp27-cp27mu-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp34-cp34m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp34-cp34m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp35-cp35m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp35-cp35m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp36-cp36m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
```

[Travis](https://travis-ci.org/twisted/twisted/jobs/423976740) (no downloadable artifacts)
```
Twisted-18.7.0.dev0-cp27-cp27m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp27-cp27m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp27-cp27mu-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp27-cp27mu-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp34-cp34m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp34-cp34m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp35-cp35m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp35-cp35m-manylinux1_x86_64.whl
Twisted-18.7.0.dev0-cp36-cp36m-manylinux1_i686.whl
Twisted-18.7.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
```

### Windows

[AppVeyor](https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-5325/job/py8uk93qx5lvdyl0/artifacts)
```
Twisted-18.7.0.dev0-cp27-cp27m-win32.whl
Twisted-18.7.0.dev0-cp27-cp27m-win_amd64.whl
Twisted-18.7.0.dev0-cp34-cp34m-win32.whl
Twisted-18.7.0.dev0-cp34-cp34m-win_amd64.whl
Twisted-18.7.0.dev0-cp35-cp35m-win32.whl
Twisted-18.7.0.dev0-cp35-cp35m-win_amd64.whl
Twisted-18.7.0.dev0-cp36-cp36m-win32.whl
Twisted-18.7.0.dev0-cp36-cp36m-win_amd64.whl
```

### OSX

[Circle](https://circleci.com/gh/twisted/twisted/1914#artifacts/containers/0)
```
Twisted-18.7.0.dev0-cp27-cp27m-macosx_10_6_intel.whl
Twisted-18.7.0.dev0-cp34-cp34m-macosx_10_6_intel.whl
Twisted-18.7.0.dev0-cp35-cp35m-macosx_10_6_intel.whl
Twisted-18.7.0.dev0-cp36-cp36m-macosx_10_6_intel.whl
```

**Comment by altendky** [comment]
Hmm, I'd guess this is not what we'd want.  I'm looking into stopping it.

https://github.com/joerick/cibuildwheel/blame/7c6b331e1555880f2d0b769c5f04fbcfae22b41e/README.md#L354

> Since `cibuildwheel` runs the wheel through delocate or auditwheel, it will automatically bundle library dependencies. This is similar to static linking, so it might have some licence implications. Check the license for any code you're pulling in to make sure that's allowed.

**Comment by altendky** [comment]
I was simply misunderstanding that message.  It is referring to including the compiled C code.

**Comment by altendky** [comment]
Trunk is broken.  I guess I'll update this branch when trunk is ok again.

**Review by glyph — APPROVED** [review]
Let’s do it.

**Pull request merged**
