### PR TITLE
#12301 Add '&' to the set of allowed characters in HTTP tokens

### LINKED ISSUE #12301: Typo in `_istoken` causes valid HTTP requests to be rejected.
# The bug
In f4fd67430494a79fef8727529858681ed14cdf39, a typo was made that causes tokens containing `&` to be incorrectly rejected. This causes, for example, requests with methods containing `&` to be rejected.

The current definition of `_istoken` looks like this:
```python3
def _istoken(b: bytes) -> bool:
    """
    Is the string a token per RFC 9110 section 5.6.2?
    """
    for c in b:
        if c not in (
            b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"  # ALPHA
            b"0123456789"  # DIGIT
            b"!#$%^'*+-.^_`|~"
        ):
            return False
    return b != b""
```
See how `^` is listed twice? The first one of those was probably intended to be a `&`. This would give the same order of characters listed in the `tchar` ABNF rule from the RFC.

### PR DESCRIPTION
**Pull request by kenballus**
## Scope and purpose

Fixes #12301

### CODE REVIEW

**Comment by kenballus** [comment]
please review

**Review by twm — DISMISSED** [review]
Thank you so much for catching this! We do need a test covering this behavior before we merge, though. (I'd add one myself but I can't push to your `trunk` branch.) Could you add an example containing `&` to `src/twisted/web/test/test_abnf.py`?

**Comment by kenballus** [comment]
please review

**Review by glyph — APPROVED** [review]
Test looks good enough!

We can address this post-hoc but is that news fragment fully accurate? I lost track of when `_abnf` was introduced; did the web server ship in this state in 24.7.0? I see that `_abnf` was *extracted* on 2024-08-18, and the release went out on 2024-08-10, but that doesn't tell me for sure that the behavior was correct before.

**Comment by twm** [comment]
When I extracted `_abnf.py` it was blind cut and paste, so [this bug is present in 24.8.0](https://github.com/twisted/twisted/blob/8cb7d2bcf5dd09dd5b98b0da7b9d77d86581016f/src/twisted/web/http.py#L518). However, I don't think it'll have any practical impact, because the function is only used in the HTTP server implementation to [validate HTTP methods](https://github.com/twisted/twisted/blob/8cb7d2bcf5dd09dd5b98b0da7b9d77d86581016f/src/twisted/web/http.py#L276-L277) and [HTTP header names](https://github.com/twisted/twisted/blob/8cb7d2bcf5dd09dd5b98b0da7b9d77d86581016f/src/twisted/web/http.py#L2500-L2500), which don't often contain `&`.

**Comment by glyph** [comment]
> When I extracted `_abnf.py` it was blind cut and paste

Great, thanks for confirming. That's what I thought :)

**Pull request merged**
