### PR TITLE
10267: Upgrade to pydoctor ~= 21.9.0

### PR DESCRIPTION
**Pull request by cjwatson**
## Scope and purpose

This fixes `AttributeError: 'ZopeInterfaceClass' object has no attribute 'append'` exceptions when building narrative documentation.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10267
* [x] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [x] The title of the PR starts with the associated Trac ticket number (without the `#` character).
* [x] I have updated the automated tests and checked that all checks for the PR are green.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.
* [x] The merge commit will use the below format
  The first line is automatically generated by GitHub based on PR ID and branch name.
  The other lines generated by GitHub should be replaced.

```
Merge pull request #123 from twisted/4356-branch-name-with-trac-id

Author: cjwatson
Fixes: ticket:10267

This fixes `AttributeError: 'ZopeInterfaceClass' object has no attribute
'append'` exceptions when building narrative documentation.
```

### CODE REVIEW

**Comment by cjwatson** [comment]
Looking at test failures: ugh.  Maybe we have to use the templating system after all.

**Comment by graingert** [comment]
the failures, (because GHA logs take a while to load)

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/python/test/test_release.py", line 330, in wrapper
    func(*a, **kw)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/python/test/test_release.py", line 482, in test_buildWithPolicy
    self.assertIn(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 487, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: Project name/location not in file contents.

twisted.python.test.test_release.APIBuilderTests.test_buildWithPolicy
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/python/test/test_release.py", line 330, in wrapper
    func(*a, **kw)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/python/test/test_release.py", line 425, in test_build
    self.assertIn(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 487, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: Project name/location not in file contents.

twisted.python.test.test_release.APIBuilderTests.test_build
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/python/test/test_release.py", line 330, in wrapper
    func(*a, **kw)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/python/test/test_release.py", line 568, in test_buildWithDeprecated
    self.assertIn(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 487, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: 'Baz was deprecated in Twisted 14.2.3; please use stuff instead.' not in '<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n          "DTD/xhtml1-strict.dtd">\n<html>\n  \n\n  <head>\n    \n    <title>quux.Baz</title>\n    <meta name="generator" content="pydoctor 21.9.1"> \n        \n    </meta>\n    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=0.75" />\n    <link rel="stylesheet" type="text/css" href="bootstrap.min.css" />\n    <link rel="stylesheet" type="text/css" href="apidocs.css" />\n    <link rel="stylesheet" type="text/css" href="extra.css" />\n</head>\n\n  <body>\n\n    \n\n    <nav class="navbar navbar-default">\n  \n  <div class="container">\n\n    <div class="navbar-header">\n      \n      <div class="navlinks">\n          <span class="navbar-brand">\n            <a href="scheme:project" class="projecthome">Foobar</a> <a href="index.html">API Documentation</a>\n          </span>\n\n          <a href="moduleIndex.html">\n            Modules\n          </a>\n\n          <a href="classIndex.html">\n            Classes\n          </a>\n\n          <a href="nameIndex.html">\n            Names\n          </a>\n      </div>\n\n    </div>\n  </div>\n</nav>\n\n    \n\n    <div class="container">\n\n      <div class="page-header">\n        <h1 class="class"><code><code><a href="quux.html">quux</a></code><wbr></wbr>.<code><a href="quux.Baz.html">Baz</a></code></code></h1>\n        <div id="showPrivate">\n          <button class="btn btn-link" onclick="togglePrivate()">Toggle Private API</button>\n        </div>\n      </div>\n\n      <div class="categoryHeader">\n        class documentation\n      </div>\n\n      <div class="extrasDocstring">\n        <p><code><span class="py-keyword">class</span> <span class="py-defname">Baz</span>: <a href="scheme:source/quux/__init__.py#L11" class="sourceLink">(source)</a></code></p>\n        <p><a href="classIndex.html#quux.Baz">View In Hierarchy</a></p>\n      </div>\n\n      <div class="moduleDocstring">\n        <div><p class="undocumented">Undocumented</p></div>\n      </div>\n\n      <div id="splitTables">\n        \n        \n\n          \n      </div>\n\n      <div id="childList">\n\n        \n\n      </div>\n    </div>\n\n    <footer class="navbar navbar-default">\n  \n  <div class="container">\n    <a href="index.html">API Documentation</a> for <a href="scheme:project" class="projecthome">Foobar</a>,\n  generated by <a href="twisted/pydoctor">pydoctor</a>\n    21.9.1 at 2021-10-12 13:19:35.\n  </div>\n</footer>\n\n    <script src="pydoctor.js" type="text/javascript"></script>\n\n  </body>\n</html>'

twisted.python.test.test_release.APIBuilderTests.test_buildWithDeprecated
```

**Comment by cjwatson** [comment]
Turns out I had to update the templates after all, but this seems workable now.

**Comment by graingert** [comment]
@cjwatson are the docs as you expected? compare https://twisted--1667.org.readthedocs.build/en/1667/api/moduleIndex.html with https://docs.twistedmatrix.com/en/latest/api/moduleIndex.html

**Review by adiroiban — APPROVED** [review]
Great work. Much appreciated.

I think that this can be merged. Using the template dir is a big improvement.


if we found any issues with the new template, we can fix it in a new PR.

I know that @tristanlatr  is working on improving pydoctor ... I hope that at some point we could have a read the docs theme for pydoctor

**Comment by cjwatson** [comment]
> @cjwatson are the docs as you expected? compare https://twisted--1667.org.readthedocs.build/en/1667/api/moduleIndex.html with https://docs.twistedmatrix.com/en/latest/api/moduleIndex.html

I think these are as expected, yes; the main visible differences seem to be in the header and footer bars.  As mentioned on IRC, the JS for going to the latest version probably only works from a published release as it's quite picky about the URL it started from, but that was already the case before this PR.

**Comment by tristanlatr** [comment]
Thanks to have tagged me in this issue @adiroiban. 

> I hope that at some point we could have a read the docs theme for pydoctor

There is already a ReadTheDocs theme that is working with pydoctor 21.9, it can be found here: https://github.com/tristanlatr/pydoctor-theme-readthedocs 

I'll sumbit a PR that integrate this theme to set of standard themes of pydoctor, it will be accessible with option `--theme=readthedocs`. In the meantime, one can use the templates provided in the repo.

**Comment by twm** [comment]
I'll go ahead and merge this per @cjwatson's request in IRC. (I haven't reviewed myself, only skimmed.)

**Pull request merged**
