### PR TITLE
Do not allow travis failures on Python 3.8

### PR DESCRIPTION
**Pull request by rodrigc**
Ticket: http://tm.tl/9798  (twistedmatrix.com seems to be down at the moment)

### CODE REVIEW

**Comment by rodrigc** [comment]
These fixes have gone in for Python 3.8:
- https://github.com/twisted/twisted/pull/1251
- https://github.com/twisted/twisted/pull/1252

So we do not need to allow travis failures on Python 3.8

**Review by altendky — APPROVED** [review]
Looks good.

**Comment by rodrigc** [comment]
@altendky thanks!

**Comment by altendky** [comment]
confusion...  discussion at https://twistedmatrix.com/trac/ticket/9799#comment:9

**Pull request merged**
