### PR TITLE
More file close related fixes

### PR DESCRIPTION
**Pull request by scop**
https://twistedmatrix.com/trac/ticket/8573

Split into three commits for easier review: first adds some closing where it wasn't previously explicitly done at all, second changes more closing to use "with", and third is self explanatory.

### CODE REVIEW

**Comment by scop** [comment]
Trac thinks my reply comment to the related ticket is spam, and when I complete the CAPTCHA, I get an error saying "CAPTCHA failed to handle original request", so I'll just reply here.

https://twistedmatrix.com/trac/ticket/8573#comment:2
Hm, now I'm not sure what "this" in the above comment by @rodrigc refers to, [ticket:8573] or [ticket:8574]. My branch carries the former in the name, and only 8574 has a topfile at the moment. What's the desired way forward?

**Comment by rodrigc** [comment]
The CAPTCHA stuff on Trac is a bit annoying, I agree.  Unfortunately spammers have been a
problem.  If you can get through to it, you should try mentioning it on  [the Twisted mailing list](https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python)

**Comment by rodrigc** [comment]
In this case add a topfile for 8573.

In future, for every pull request you make, create a ticket in Trac as per:
https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

It is a bit annoying, but the current Twisted development process works best that way.

**Comment by scop** [comment]
It's not about the CAPTCHA being annoying (I don't think it actually is), it's that it _does not work_. When I complete the CAPTCHA properly, as said, it gives me an error page saying  "CAPTCHA failed to handle original request" and prompts me to fill another one, rinse, repeat.

Another thing that seems broken is subscribing to the mailing list you mentioned. No matter what I fill in to the subscription form, I get a "CGI Script Error Premature end of script headers" response.

**Comment by rodrigc** [comment]
Yes, I've had similar problems with the CAPTCHA, unfortunately.
Regarding the mailing list, that is another area of big problems, unfortunately, due to attempts to lock it down due to spammers.  If you really want to join, try emailing @glyph directly.
Sorry about all these roadblocks. :(

**Comment by scop** [comment]
I don't actually want to join a mailing list at this point, would have just done it temporarily in order to be able to notify people about the CAPTCHA issue. Filed a website bug about it instead: https://twistedmatrix.com/trac/ticket/8587

**Comment by rodrigc** [comment]
I was given access to the anti-spam control on Trac last week.   I don't know how to fix the problem in 8587, since I don't know much about Trac, but I clicked on a few entries where Trac flagged your access as SPAM and deleted them.  Are you still getting the problem?

The best I can do is alleviate the problem, not fix it. :(

**Comment by scop** [comment]
I'll let you know if I run into it again.

**Comment by rodrigc** [comment]
@scop @markrwilliams Thanks for your submissions.  I am not sure if you have the time or interest to work on more patches for closing open file descriptors, but let me throw this out there for your consideration.

I made this slight patch to tox.ini:

```
--- a/tox.ini
+++ b/tox.ini
@@ -51,7 +51,7 @@ setenv =
    COVERAGE_PROCESS_START = {toxinidir}/.coveragerc

 commands =
-    {tests,nomodules}: python {envbindir}/trial --reactor={env:TWISTED_REACTOR:default} --reporter={env:TRIAL_REPORTER:verbose}  {posargs:twisted}
+    {tests,nomodules}: python -bb -Wall {envbindir}/trial --reactor={env:TWISTED_REACTOR:default} --reporter={env:TRIAL_REPORTER:verbose}  {posargs:twisted}

     coverage: python {toxinidir}/admin/_copy.py {toxinidir}/admin/zz_coverage.pth {envsitepackagesdir}/zz_coverage.pth
```

and ran this command using a Python 3.5 virtual environment:

```
tox -e py35-tests
```

I saw a bunch of ResourceWarnings, such as these:

```
   test_systemCallUninterruptedByChildExit ...                            [32;1m[OK][0m
/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:1023: ResourceWarning: subprocess 5224 is still running
/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:1023: ResourceWarning: subprocess 5225 is still running
/Users/crodrigues/twisted6/build/py35-tests/lib/python3.5/site-packages/twisted/internet/base.py:430: ResourceWarning: unclosed file <_io.BufferedReader name=56>
    test_timelyProcessExited ...                                           [32;1m[OK]
```

```
    test_badContext ...                                                    [32;1m[OK][0m
/Users/crodrigues/twisted6/build/py35-tests/lib/python3.5/site-packages/twisted/internet/endpoints.py:236: ResourceWarning: unclosed <socket.socket fd=62, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 56023)>
/Users/crodrigues/twisted6/build/py35-tests/lib/python3.5/site-packages/twisted/internet/endpoints.py:236: ResourceWarning: unclosed <socket.socket fd=64, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('fe80::1%lo0', 56025, 0, 1)>
/Users/crodrigues/twisted6/build/py35-tests/lib/python3.5/site-packages/twisted/internet/endpoints.py:236: ResourceWarning: unclosed <socket.socket fd=65, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 56027)>
/Users/crodrigues/twisted6/build/py35-tests/lib/python3.5/site-packages/twisted/internet/endpoints.py:236: ResourceWarning: unclosed <socket.socket fd=66, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 56029), raddr=('127.0.0.1', 56030)>
/Users/crodrigues/twisted6/build/py35-tests/lib/python3.5/site-packages/twisted/internet/endpoints.py:236: ResourceWarning: unclosed <socket.socket fd=67, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 56031)>
```

I don't know if you feel like taking a whack at cleaning up some of these.

Thanks for your previous submissions!

**Comment by scop** [comment]
Those look like useful warnings to have. Bunch of low hanging ones fixed in #363

**Comment by rodrigc** [comment]
@scop thanks for your good patches.  I've been pushing them in.
Can you help me by reviewing some of my pull requests: https://github.com/twisted/twisted/pulls/rodrigc

Some of them are simple ones, but I still need a review before I can push it in.
You have demonstrated that you know what you are doing, and can look at stuff and review.

**Pull request closed without merging**
