### PR TITLE
#11652 migrate community doc page rst

### LINKED ISSUE #11652: Migrate twisted community doc page to RST/RTD
Describe any issue with the documentation or typos in the code.

- Currently the Twisted Community page is hosted on the trac-archive-wiki:
https://github.com/twisted/trac-wiki-archive/blob/trunk/TwistedCommunity.mediawiki
- It should be possible to migrate this page to RST and integrate it to the RTD main doc. 

Make sure that you are reporting issues against the [latest](https://docs.twisted.org/en/latest/) version of the documentation.

Note that our changes for our website are handled in the [twisted/twisted.github.io](https://github.com/twisted/twisted.github.io) repository.
- Linking to the RTD page from the website should be possible once the RST migration is done.

### PR DESCRIPTION
**Pull request by JudgeGregg**
## Scope and purpose

Fixes #11652

Add a few words about why this PR is needed and what is its scope.
- Migrate Twisted Community Page to RST from old Trac Wiki.

Add any comments about trade-offs (if any) made in this PR and the reasoning behind them.
- Removed the old IRC channels dev/web and old MLs.

Add mentions of things that are not covered here and are planed to be done in separate PRs.
- Still need to update the twisted.org site to link to the new RTD page.

## Contributor Checklist:

This process applies to *all* pull requests - no matter how small.
Have a look at [our developer documentation](https://docs.twisted.org/en/latest/core/development/dev-process.html) before submitting your Pull Request.

Below is a non-exhaustive list (as a reminder):

* The title of the PR should describe the changes and starts with the associated issue number, like “#1234 Brief description”.
* A release notes news fragment file was create in src/twisted/newsfragments/ (see: [Release notes fragments docs.](https://docs.twisted.org/en/latest/core/development/dev-process.html#release-notes-management))
* The automated tests were updated.
* Once all checks are green, request a review by leaving a comment that contains exactly the string `please review`.
  Our bot will trigger the review process, by applying the pending review label
  and requesting a review from the Twisted dev team.

### CODE REVIEW

**Comment by JudgeGregg** [comment]
please review

**Review by adiroiban — APPROVED** [review]
Thanks. It is a great start.

For reference, the updated page is here

https://twisted--11653.org.readthedocs.build/en/11653/community.html


---------

I think it is worth talking about our Gitter channel

This is the chat that is available in the bottom right corner of our docs

image


----------

Gitter is using Matrix, and Matrix is using Twisted ... so I think this is a nice example of Twisted being used for real world applications

**Comment by JudgeGregg** [comment]
> I think it is worth talking about our Gitter channel

You're right, I should have thought about it myself :).

**Comment by JudgeGregg** [comment]
please review

**Comment by adiroiban** [comment]
Thanks for the update. Happy to see the docs get some attention and at the same time move important info from the wiki over the official docs.

If you have time, please consider doing a followup PR for https://github.com/twisted/twisted.github.io to get the main page link to the new doc page.

For the community info, I think we can link to the "latest" version of the docs - https://docs.twisted.org/en/latest/

No need to go for the "stable" version.

image

**Comment by JudgeGregg** [comment]
Thank you for your patience :)
I'll do the PR for the website.

**Pull request merged**
