### PR TITLE
twisted.python._release.runCommand now uses check_output

### PR DESCRIPTION
**Pull request by markrwilliams**
See https://twistedmatrix.com/trac/ticket/8648

### CODE REVIEW

**Comment by rodrigc** [comment]
@markrwilliams Just go ahead and delete runCommand entirely and replace everywhere with
check_output().  check_output() internally calls the Popen() constructor, and Popen()
internally calls _execute_command(), which can handle arguments which are
bytes or str, the docstring for runCommand isn't accurate.

See:

https://github.com/python/cpython/blob/master/Lib/subprocess.py#L963
https://github.com/python/cpython/blob/master/Lib/subprocess.py#L1212
https://github.com/python/cpython/blob/master/Lib/subprocess.py#L1454

_release.py is an internal module, so deleting runCommand() is OK.

This is good stuff and will facilitate getting this module to run on Python 3.

**Comment by markrwilliams** [comment]
@rodrigc `runCommand`'s original implementation sent the process' stderr to its stdout, so that the byte string returned contained both.  Dropping `runCommand` in favor of `check_output` would require all the places where `runCommand` is called to reassign stderr, e.g. this:

``` python
r = runCommand([b"git", b"diff", b"--name-only", b"origin/trunk..."], cwd=location).strip()
```

would become this:

``` python
r = check_output([b"git", b"diff", b"--name-only", b"origin/trunk..."], stderr=STDOUT, cwd=location).strip()
```

(where `STDOUT` is a special constant imported from subprocess.)

I went ahead and updated the docstring.  What do you think about replacing `runCommand` with a wrapper that only sets stderr to `STDOUT`?

**Comment by rodrigc** [comment]
Having a minimal wrapper around subprocess.check_output() that only sets stderr to STDOUT is OK.  Go for that.  Delete all of the docstring, and just say that
it takes the same arguments as L{subprocess.Popen.**init**}, that way the docs will hyperlink
to that function in the Python docs and you don't have to worry about inaccurate docstring.

**Comment by markrwilliams** [comment]
@rodrigc Good idea.  To make that work, I changed `runCommand` to accept keyword arguments for all its configuration; that way it can always set `stderr` without either conflicting with the user's choice (e.g., `check_output(["someArg0"], 0, "/bin/ls", None, None, subprocess.PIPE, ..., stderr=subprocess.STDOUT`) or copying and pasting default arguments from `Popen.__init__` that differ between Python versions (e.g., `bufsize=0` in Python 2 and `-1` in Python 3).

**Comment by rodrigc** [comment]
Merged in https://github.com/twisted/twisted/pull/396

**Pull request closed without merging**
