### PR TITLE
Install openssh instead of deprecated win32-openssh in appveyor

### PR DESCRIPTION
**Pull request by rodrigc**
http://twistedmatrix.com/trac/ticket/9229

### CODE REVIEW

**Comment by rodrigc** [comment]
@opalmer please code review this.

**Review by opalmer — APPROVED** [review]
:+1:

**Comment by rodrigc** [comment]
@opalmer thanks!

**Comment by rodrigc** [comment]
@opalmer can you modify http://twistedmatrix.com/trac/ticket/9229 by removing the *review* keyword, and assigning the ticket to me so that I can proceed with the commit?
Thanks.

**Comment by opalmer** [comment]
Done! Didn't see the review keyword anywhere on the ticket but I did get it reassigned.

**Pull request merged**
