### PR TITLE
remove conch/ssh/_cryptography_backports.py

### PR DESCRIPTION
**Pull request by ofek**
https://twistedmatrix.com/trac/ticket/9263

Moved from these earlier pull requests:

https://github.com/twisted/twisted/pull/761
https://github.com/twisted/twisted/pull/873

### CODE REVIEW

**Comment by ofek** [comment]
@rodrigc Everything is working, just AppVeyor is having issues.

**Review by rodrigc — COMMENTED** [review]
There is a trick to triggering CI
from GitHub.....just close the PR, and re-open it.
No new commits are required.

But this is OK.

**Review by rodrigc — APPROVED** [review]
This looks OK.

Thanks for working on this.

**Comment by ofek** [comment]
@rodrigc All passing now. Thanks for your guidance!

**Pull request merged**
