### PR TITLE
Fixed reST syntax

### PR DESCRIPTION
**Pull request by alex**
Merge pr/132: Fixed reST syntax

Author: alex

Reviewer: glyph

Fixes: #8416

Fixed some markup to avoid ugly artifacts.

### CODE REVIEW

**Comment by chellygel** [comment]
https://twistedmatrix.com/trac/ticket/8416#ticket

**Comment by ericholscher** [comment]
:+1:

**Comment by rodrigc** [comment]
Can you add a topfile? https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles

The Travis build fails without one: https://travis-ci.org/twisted/twisted/builds/135161249

**Comment by alex** [comment]
@rodrigc done.

**Comment by rodrigc** [comment]
@alex Travis thanks you: https://travis-ci.org/twisted/twisted/builds/135167161 👍

**Pull request merged**
