### PR TITLE
#12385 Expose t.i.endpoints._parse as parseDescription

### LINKED ISSUE #12385: twisted.internet.endpoints._parse() should be public
Twisted does not offer any tools to interact with endpoint description strings. Exposing this would be useful in middleware code that would behave differently depending on what exact description string is.

Example of third-party functionality that currently uses this private API: https://github.com/buildbot/buildbot/pull/8253

### PR DESCRIPTION
**Pull request by p12tic**
## Scope and purpose

Fixes #12385

### CODE REVIEW

**Comment by p12tic** [comment]
please review

**Comment by p12tic** [comment]
please review

**Review by glyph — CHANGES_REQUESTED** [review]
Per my comment on the issue, my current feedback is that this just shouldn't be public in the first place, and buildbot should probably adjust its implementation to express this part of its configuration in some other way.

If it *should* be public, the intermediate parsing representation should probably be something different and more suitable to commit to longer term.

One way to address this might be to write narrative documentation explaining why this is exposed and what type of application should use it, which a finished PR would also need anyway. You'd probably need as much verbiage in the PR and issue comments anyway, so it might be more efficient to express your argument that way :)

**Comment by glyph** [comment]
Oh, and if it's going to be public it also needs a type annotation:)

**Comment by p12tic** [comment]
Closing per comments.

**Pull request closed without merging**
