### PR TITLE
12313 Fix test_manhole.py on Python 3.13rc2

### LINKED ISSUE #12313: test_manhole.py is failing with latest 3.13 pre-release (rc2)
```
[FAIL]
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/conch/test/test_manhole.py", line 237, in finished
    self._assertBuffer(
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/conch/test/test_recvline.py", line 476, in _assertBuffer
    self.assertEqual(receivedLines, expectedLines)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/trial/_synctest.py", line 444, in assertEqual
    super().assertEqual(first, second, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 907, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 1113, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 1095, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [b">>[32 chars]", b'Exception: foo bar baz', b'>>> done', b''[91 chars] b''] != [b">>[32 chars]", b'Traceback (most recent call last):', b'  [164 chars] b'']

First differing element 1:
b'Exception: foo bar baz'
b'Traceback (most recent call last):'

  [b">>> raise Exception('foo bar baz')",
+  b'Traceback (most recent call last):',
+  b'  File "<console>", line 1, in <module>',
   b'Exception: foo bar baz',
   b'>>> done',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
-  b'',
-  b'',
   b'']

twisted.conch.test.test_manhole.ManholeLoopbackSSHTests.test_ExceptionWithCustomExcepthook
twisted.conch.test.test_manhole.ManholeLoopbackSSHTests.test_Exception
twisted.conch.test.test_manhole.ManholeLoopbackStdioTests.test_Exception
twisted.conch.test.test_manhole.ManholeLoopbackStdioTests.test_ExceptionWithCustomExcepthook
twisted.conch.test.test_manhole.ManholeLoopbackTelnetTests.test_Exception
twisted.conch.test.test_manhole.ManholeLoopbackTelnetTests.test_ExceptionWithCustomExcepthook
```

### PR DESCRIPTION
**Pull request by itamarst**
## Scope and purpose

Fixes #12313

I am not sure why this is necessary but it solves it.

### CODE REVIEW

**Comment by alyssais** [comment]
I've been seeing what I think is the same failure since updating to Python 3.12.6.

**Comment by itamarst** [comment]
It's possible this is a regression in CPython. I'll try to reproduce; perhaps a better way to implement it is to inspect the possibly-skipped frame and see if it should be skipped, given it's in a released version. And I guess file a bug report.

**Comment by adiroiban** [comment]
Thanks for the PR

I see that on `trunk`, these tests were not failing  with `3.13.0rc1 (main, Aug 29 2024, 14:16:22) [GCC 11.4.0]`

https://github.com/twisted/twisted/actions/runs/10774970649/job/29878322696#step:10:1079

-------

I did a re-run to get latest `3.13.0rc2 (main, Sep  9 2024, 03:11:37) [GCC 11.4.0]` and I can see that `trunk` tests are failing

https://github.com/twisted/twisted/actions/runs/10774970649/job/30162695096#step:10:1081

**Review by adiroiban — APPROVED** [review]
Thanks for the changes and the fix.

I think that we can merge this, so that we fix `trunk`

It would help to create an upstream bug report and add the link as an inline code comment

**Comment by cjwatson** [comment]
There's a similar failure with Debian's Python 3.12.6, so maybe "less than 3.13" isn't quite the right test?

**Comment by adiroiban** [comment]
Thanks for the feedback

It looks like via `actions/setup-python@v5` we only get `CPython (3.12.5)`

-------

Maybe we need to wait a bit more. I see that 3.12.6 is available via `actions/python-versions` and with a definition of `3.12` , `actions/setup-python` should have picked up the latest release ... so `3.12.6`

https://github.com/actions/python-versions/releases/tag/3.12.6-10765725458

------

The strange thing, is that on the `actions/setup-python` CI, I can see that `3.12` is picked up as `3.12.6`
https://github.com/actions/setup-python/actions/runs/10795247111/job/29941593380#step:3:3

**Comment by cjwatson** [comment]
I bisected Python `v3.12.5..v3.12.6` and got https://github.com/python/cpython/commit/8fe586d27abda29188cac6def55a04bf15242891, i.e. https://github.com/python/cpython/issues/122478.  Does that help with working out the correct fix?

**Comment by adiroiban** [comment]
To replicate this error on 3.12.6 we need

```diff
Run actions/setup-python@v5
  with:
    python-version: 3.12
-    check-latest: false
+    check-latest: true
```

I have pushed a change on this PR to reproduce the error in 3.12.6

**Comment by itamarst** [comment]
I updated the check to be tied to the symptoms, rather than version specific.

**Pull request merged**
