### PR TITLE
Move CircleCI documentation build to GitHub Actions

### PR DESCRIPTION
**Pull request by rodrigc**
## Contributor Checklist:

* [X] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9987
* [ ] I ran `tox -e black-reformat` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [ ] I ran additional checks listed at [Getting Your Patch Accepted](https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted)
* [X] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [ ] I have updated the automated tests.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Review by adiroiban — APPROVED** [review]
The text of the ticket contains : ` It would be good to convert the Circle CI documentation job to GitHub Actions. `

But why it would be good?

-------


I think that is OK and can be merged.

But moving more builds to GitHub Action will consume on the concurrent number of builds that Twisted has.

**Comment by rodrigc** [comment]
> The text of the ticket contains : `It would be good to convert the Circle CI documentation job to GitHub Actions.`
> 
> But why it would be good?

This will help us to consolidate on one CI system, in order to help develop a fully automated release workflow which builds wheels, runs tests, uploads artifacts, and builds documentation.

**Comment by adiroiban** [comment]
> This will help us to consolidate on one CI system, in order to help develop a fully automated release workflow which builds wheels, runs tests, uploads artifacts, and builds documentation.

This is just testing the documentation... but with read the docs, the public documentation build and publish is executed on the Read The Docs servers, and not on GitHub Actions.

So, I think that we should enable Read The docs build when a PR is created, and update the way sphinx documentation is build to also trigger the pydoctor documentation.

See for example: https://github.com/twisted/ldaptor/pull/198 

image

**Comment by adiroiban** [comment]
In summary, to automated the documentation publishing for a release, we should move the whole documentation build to Read The Docs.

I think that right now, only the narrative docs publishing is automated with read the docs - https://twisted.readthedocs.io/en/twisted-20.3.0/

We might want to keep a parallel GitHub Action build , but that will server only for easy debugging and checking the error messages in the case in which the Read The docs build fails.

So, twisted will need a .readthedocs.yml file in the repo, to control how the docs is build.

I think that right now, the documentation on read the docs, is built even if there are warnings

**Comment by adiroiban** [comment]
@rodrigc let me know if you need help with enabling Read The docs PR build, or you want me to push the `.readthedocs.yml` conf file

**Comment by rodrigc** [comment]
> @rodrigc let me know if you need help with enabling Read The docs PR build, or you want me to push the `.readthedocs.yml` conf file

Is this PR: https://github.com/twisted/twisted/pull/1409 what we need for readthedocs.yml or do you have something else in mind?

**Comment by adiroiban** [comment]
Thanks Craig for the  link :) Yes. In that PR we can solve the read the docs build part.

**Comment by rodrigc** [comment]
Thanks for reviewing https://github.com/twisted/twisted/pull/1409 .  Once it is in shape, we can merge it in.
I see that it has a **.misc** newsfragment which is populated with text.  I thought that misc newsfragments were ignored by towncrier?  Or is it ok to have text in a **.misc** newsfragment?

**Comment by adiroiban** [comment]
The misc is ignored for the final release notes.

if someone wants to add a text... that is fine.

We could have a warning when a non-empty misc file is created....but I think that we can live without it.

**Pull request merged**
