### PR TITLE
Use the console_script installed version of trial when running coverage

### PR DESCRIPTION
**Pull request by rodrigc**
https://twistedmatrix.com/trac/ticket/8643

### CODE REVIEW

**Comment by rodrigc** [comment]
@opalmer can you help review this?  This is one step towards getting a working appveyor setup.

**Comment by opalmer** [comment]
Looks like it's having issues finding the script:

```
[...]
py27-coverage-windows runtests: commands[1] | coverage erase
py27-coverage-windows runtests: commands[2] | coverage run -p --rcfile=C:\projects\twisted/.coveragerc C:\projects\twisted\build\py27-coverage-windows\Scripts/trial-script.py --reactor=default --reporter=text twisted
No file to run: 'C:\projects\twisted\build\py27-coverage-windows\Scripts/trial-script.py'
[...]
```

source: https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-189#L32

Looking at where the entrypoints are defined I'd expect that script to be on disk. If it's not then maybe tox is not invoking setup.py properly.  If the script is on disk then there's probably an issue with the path somehow.

Other than that don't see any general issues with the change itself but I would like someone else's opinion, my tox foo is a little rusty.

**Comment by rodrigc** [comment]
@opalmer with my patch, in your c:\projects\twisted, if you type:

```
python -m tox -e py27-windows-coverage
```

What files do you see in `C:\projects\twisted\build\py27-coverage-windows\Scripts` ?

Also what is the output of `python -m pip list`?

**Comment by rodrigc** [comment]
Also, I recommend doing this in a virtual environment.  If you are using Python 2.7:

```
python -m virtualenv myenv
.\myenv\scripts\activate
```

**Comment by hawkowl** [comment]
Wait, why do we have a trial-script???

**Comment by opalmer** [comment]
@hawkowl....my bad, we don't.  I've seen <name>-script.py on a few occasions on other projects and assumed Twisted's setup.py would end up dropping one on disk (that and/or an exe file).  I'm wrong in both cases, Twisted only drops `trial` under the Scripts dir.

@rodrigc.  The trial file should work.  I setup a clean virtualenv locally, sourced it, then ran this which ended up running trial and the tests:

```
coverage run -p --rcfile=.coveragerc %VIRTUAL_ENV%\Scripts\trial twisted
```

So, try submitting a change with this:

```
coverage-windows: coverage run -p --rcfile={toxinidir}/.coveragerc {envbindir}/trial --reactor={env:TWISTED_REACTOR:default} --reporter={env:TRIAL_REPORTER:verbose} {posargs:twisted}
```

**Comment by rodrigc** [comment]
@opalmer can you post the contents of your Scripts dir?  Also, can you create a separate VirtualEnv with Python3, and try it, and list the contents of your Scripts dir there?

**Comment by rodrigc** [comment]
So under Windows with Python 3.5, if I do:

```
tox -e py35-coverage-windows
```

At the end of the run, I have:

```

07/21/2016  06:13 PM    <DIR>          .
07/21/2016  06:13 PM    <DIR>          ..
07/21/2016  06:09 PM             2,235 activate
07/21/2016  06:09 PM               803 activate.bat
07/21/2016  06:09 PM             8,325 activate.ps1
07/21/2016  06:09 PM             1,137 activate_this.py
07/21/2016  06:10 PM            98,184 coverage-3.5.exe
07/21/2016  06:10 PM            98,184 coverage.exe
07/21/2016  06:10 PM            98,184 coverage3.exe
07/21/2016  06:09 PM               508 deactivate.bat
07/21/2016  06:08 PM            98,199 easy_install-3.5.exe
07/21/2016  06:08 PM            98,199 easy_install.exe
07/21/2016  06:09 PM            33,929 miniterm.py
07/21/2016  06:09 PM            30,987 miniterm.pyc
07/21/2016  06:09 PM            98,180 pbr.exe
07/21/2016  06:08 PM            98,171 pip.exe
07/21/2016  06:08 PM            98,171 pip3.5.exe
07/21/2016  06:08 PM            98,171 pip3.exe
07/21/2016  06:08 PM            41,240 python.exe
07/21/2016  06:08 PM         3,926,296 python35.dll
07/21/2016  06:08 PM            41,240 pythonw.exe
07/21/2016  06:09 PM            25,362 pywin32_postinstall.py
07/21/2016  06:09 PM             3,483 pywin32_testall.py
07/21/2016  06:09 PM             1,472 subunit-1to2
07/21/2016  06:09 PM             1,820 subunit-2to1
07/21/2016  06:09 PM             6,671 subunit-filter
07/21/2016  06:09 PM             2,279 subunit-ls
07/21/2016  06:09 PM             1,649 subunit-notify
07/21/2016  06:09 PM               978 subunit-output
07/21/2016  06:09 PM             1,277 subunit-stats
07/21/2016  06:09 PM             1,077 subunit-tags
07/21/2016  06:09 PM             1,121 subunit2csv
07/21/2016  06:09 PM             8,363 subunit2gtk
07/21/2016  06:09 PM             1,364 subunit2junitxml
07/21/2016  06:09 PM             2,402 subunit2pyunit
07/21/2016  06:09 PM             1,093 tap2subunit
07/21/2016  06:13 PM            98,187 trial.exe
07/21/2016  06:13 PM            98,188 twistd.exe
07/21/2016  06:09 PM            98,188 unit2.exe
07/21/2016  06:09 PM            98,178 wheel.exe
07/21/2016  06:10 PM    <DIR>          __pycache__
              38 File(s)      5,423,495 bytes
               3 Dir(s)  63,099,899,904 bytes free
```

In a previous run, I had trial-script.py **and** trial.exe.  Need to figure out why trial-script.py
is not there.

According to https://matthew-brett.github.io/pydagogue/installing_scripts.html#setuptools-and-console-script-entry-points
on Windows, setuptools should lay down trial.exe and trial-script.py in the Scripts directory.
I've seen this before on my own system.  Need to figure out why it didnt happen now.

**Comment by rodrigc** [comment]
I wasn't imagining things, this is the code in setuptools which should be generating trial-script.py:

https://github.com/pypa/setuptools/blob/master/setuptools/command/easy_install.py#L2162

**Comment by opalmer** [comment]
Ok so I setup two virtualenvs, one with Python 2.7 and one Python 3.5.  After that I ran `python setup.py develop` in both the following files were present in `%VIRTUAL_ENV%\Scripts\`:
- trial.exe
- trial-script.py

So, outside of tox and the build the behavior is consistent as we'd expect from setuptools.  Which is good because if it wasn't then that would be different bug entirely.

Now, looking at tox the behavior is also consistent across Python versions:

**Python 3.5**

```
(temp3) opalmer@WIN10-DEV C:\dev\repos\twisted
> python -m tox -e py35-coverage-windows
GLOB sdist-make: C:\dev\repos\twisted\setup.py
py35-coverage-windows create: C:\dev\repos\twisted\build\py35-coverage-windows
py35-coverage-windows installdeps: cryptography >= 0.9, pyopenssl >= 0.13, service_identity, idna >= 0.6, pyserial, python-subunit, pycrypto, appdirs, h2, priority, pypiwin32, coverage
py35-coverage-windows inst: C:\dev\repos\twisted\build\dist\Twisted-16.3.0.zip
py35-coverage-windows installed: appdirs==1.4.0,attrs==16.0.0,cffi==1.7.0,coverage==4.1,cryptography==1.4,extras==1.0.0,fixtures==3.0.0,h2==2.4.0,hpack==2.2.0,hyperframe==4.0.1,idna==2.1,linecache2==1.0.0,pbr==1.10.0,priority==1.1.1,pyasn1==0.1.9,pyasn1-modules==0.0.8,pycparser==2.14,pycrypto==2.6.1,pyOpenSSL==16.0.0,pypiwin32==219,pyserial==3.1.1,python-mimeparse==1.5.2,python-subunit==1.2.0,service-identity==16.0.0,six==1.10.0,testtools==2.2.0,traceback2==1.4.0,Twisted==16.3.0,unittest2==1.1.0,zope.interface==4.2.0
py35-coverage-windows runtests: PYTHONHASHSEED='829'
py35-coverage-windows runtests: commands[0] | python C:\dev\repos\twisted/admin/_copy.py C:\dev\repos\twisted/admin/zz_coverage.pth C:\dev\repos\twisted\build\py35-coverage-windows\Lib\site-packages/zz_coverage.pth
py35-coverage-windows runtests: commands[1] | coverage erase
py35-coverage-windows runtests: commands[2] | coverage run -p --rcfile=C:\dev\repos\twisted/.coveragerc C:\dev\repos\twisted/bin/trial --reactor=default --reporter=verbose twisted
[ ... ]
```

**Python 2.7**

```
(temp2) opalmer@WIN10-DEV C:\dev\repos\twisted
> python -m tox -e py27-windows-coverage
GLOB sdist-make: C:\dev\repos\twisted\setup.py
py27-windows-coverage create: C:\dev\repos\twisted\build\py27-windows-coverage
py27-windows-coverage installdeps: cryptography >= 0.9, pyopenssl >= 0.13, service_identity, idna >= 0.6, pyserial, python-subunit, pycrypto, appdirs, h2, priority, soappy, pypiwin32, coverage
py27-windows-coverage inst: C:\dev\repos\twisted\build\dist\Twisted-16.3.0.zip
py27-windows-coverage installed: apipkg==1.4,appdirs==1.4.0,attrs==16.0.0,autopep8==1.2.4,cffi==1.7.0,colorama==0.3.7,coverage==4.1,cryptography==1.4,defusedxml==0.4.1,enum34==1.1.6,execnet==1.4.1,extras==1.0.0,fixtures==3.0.0,h2==2.4.0,hpack==2.2.0,hyperframe==4.0.1,idna==2.1,ipaddress==1.0.16,linecache2==1.0.0,pbr==1.10.0,pep8==1.7.0,priority==1.1.1,py==1.4.31,pyasn1==0.1.9,pyasn1-modules==0.0.8,pycparser==2.14,pycrypto==2.6.1,pyOpenSSL==16.0.0,pypiwin32==219,pyserial==3.1.1,pytest==2.9.2,pytest-cache==1.0,pytest-cov==2.3.0,pytest-pep8==1.0.6,pytest-timeout==1.0.0,python-mimeparse==1.5.2,python-subunit==1.2.0,service-identity==16.0.0,six==1.10.0,SOAPpy==0.12.22,testtools==2.2.0,traceback2==1.4.0,Twisted==16.3.0,unittest2==1.1.0,wstools==0.4.4,zope.interface==4.2.0
py27-windows-coverage runtests: PYTHONHASHSEED='37'
py27-windows-coverage runtests: commands[0] | python C:\dev\repos\twisted/admin/_copy.py C:\dev\repos\twisted/admin/zz_coverage.pth C:\dev\repos\twisted\build\py27-windows-coverage\Lib\site-packages/zz_coverage.pth
py27-windows-coverage runtests: commands[1] | coverage erase
py27-windows-coverage runtests: commands[2] | coverage run -p --rcfile=C:\dev\repos\twisted/.coveragerc C:\dev\repos\twisted/bin/trial --reactor=default --reporter=verbose twisted
[ ... ]
```

Note that both Python versions ran `coverage run [ ... ] twisted/bin/trial`.  In both Python 2 and Python 3 the tests started to execute shortly after that call to coverage shows up.  This behavior is also replicated on AppVeyor too:

https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-297#L21

So before we dig into this further I'd like to pose the question: Why should trial from within the scripts directory?  It would seem like coverage is executing the tests but it's having issues generating the coverage report after the fact which may point to a problem which can't be solved just by calling trial in a different location.  Figuring out why coverage reporting is broken first might be a better approach to start with before changing the way the tests are executed.

**Comment by rodrigc** [comment]
Closing in favor of https://github.com/twisted/twisted/pull/448

**Pull request closed without merging**
