### PR TITLE
collectWarning: supports arbitrary warning arguments

### PR DESCRIPTION
**Pull request by tardyp**
https://twistedmatrix.com/trac/ticket/9005

mysqlclient library warnings that comes from the server have integer as their
first argument

### CODE REVIEW

**Comment by rodrigc** [comment]
Can you add a topfile news fragment as mentioned here: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch ?

**Comment by tardyp** [comment]
I did add one, but looks like I failed the git commit --am

**Comment by tardyp** [comment]
Now I've uploaded the newsfragment..

**Comment by rodrigc** [comment]
Fixed in https://github.com/twisted/twisted/pull/693

**Pull request closed without merging**
