### PR TITLE
Update pb.py

### PR DESCRIPTION
**Pull request by congzhangzh**
under python3, password will be a str but not bytes which need to be encode before call md5().update

downstream affect like: buildbot/buildbot#3726

### CODE REVIEW

**Comment by jdpipe** [comment]
Not sure whether this change is correct? Perhaps it is better like so?
```python
    if isinstance(password, bytes):
        pbytes = password
    else:
        pbytes = password.encode('ascii')
```

**Comment by congzhangzh** [comment]
Agree wit you!

**Comment by rodrigc** [comment]
Normally the pattern to follow in Twisted code is:

```
from twisted.python.compat import unicode

if isinstance(password, unicode):
    password = password.encode("ascii")
```

**Comment by rodrigc** [comment]
When you submit a pull request to Twisted, the following items are displayed.  You
did not follow any of these steps which were displayed, so Twisted devs will generally not look at your patch:



Please have a look at our developer documentation before submitting your Pull Request.

https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

## Contributor Checklist:

* [ ] There is an associated ticket in Trac. Create a new one at https://twistedmatrix.com/trac/newticket
* [ ] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )

**Comment by angeloudy** [comment]
```
if isinstance(password, bytes):
        pbytes = password
    else:
        pbytes = password.encode('ascii')
```
This worked for me.
Can some one merge this?

**Pull request closed without merging**
