### PR TITLE
#11965 fix cfreactor on Python 3.8 and Python 3.9

### LINKED ISSUE #11965: twisted.internet.cfreactor not importable on Python 3.8
**Describe the incorrect behavior you saw**
fails with:

```
src/twisted/internet/cfreactor.py:474:24: error: X | Y syntax for unions requires Python 3.10  [syntax]
        _currentSimulator: object | None = None
```

```
>>> import twisted.internet.cfreactor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graingert/projects/twisted/src/twisted/internet/cfreactor.py", line 92, in <module>
    class CFReactor(PosixReactorBase):
  File "/home/graingert/projects/twisted/src/twisted/internet/cfreactor.py", line 474, in CFReactor
    _currentSimulator: object | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Describe how to cause this behavior**

import it on Python 3.8 

Preferable a [Short, Self Contained, Correct (Compilable), Example](http://www.sscce.org/) on a branch or on [a gist](https://gist.github.com).

Automated tests that are demonstrating the failure would be awesome.

**Describe the correct behavior you'd like to see**
no import error

**Testing environment**
N/A

### PR DESCRIPTION
**Pull request by graingert**
## Scope and purpose

Fixes #11965 

## Contributor Checklist:

This process applies to *all* pull requests - no matter how small.
Have a look at [our developer documentation](https://docs.twisted.org/en/latest/core/development/dev-process.html) before submitting your Pull Request.

Below is a non-exhaustive list (as a reminder):

* The title of the PR should describe the changes and starts with the associated issue number, like “#1234 Brief description”.
* A release notes news fragment file was create in src/twisted/newsfragments/ (see: [Release notes fragments docs.](https://docs.twisted.org/en/latest/core/development/dev-process.html#release-notes-management))
* The automated tests were updated.
* Once all checks are green, request a review by leaving a comment that contains exactly the string `please review`.
  Our bot will trigger the review process, by applying the pending review label
  and requesting a review from the Twisted dev team.

### CODE REVIEW

**Comment by graingert** [comment]
@adiroiban what do you want to do re the automated tests on this one? the macos tests are only run on 3.11 maybe they should run on 3.8 also?

**Comment by adiroiban** [comment]
Thanks. Enabling them on 3.8 should be ok.

I see that we also run Windows tests on 3.8 and 3.11.
Maybe also update Windows to run on 3.8 and 3.12

so for macOS and Windows we can run on the oldest and newest version that we support.

Do you use Twisted with cfreactor ? If yes, then I think we should run the cfreator tests on any Python version that you use.

**Review by adiroiban — APPROVED** [review]
Thanks. Looks good.

Please also consider enabling  the GHA macOS tests for python 3.8.

With that, this should be  ready to land.

thanks again!

**Comment by graingert** [comment]
> Do you use Twisted with cfreactor ? If yes, then I think we should run the cfreator tests on any Python version that you use.

I do not, I only noticed this by running mypy with 3.8.0

**Comment by graingert** [comment]
I'll enable macos 3.8 tests in a followup

**Pull request merged**
