### PR TITLE
#12257 More HTTP server benchmarks

### LINKED ISSUE #12257: Add some more HTTP server benchmarks
**Is your feature request related to a problem? Please describe.**

It'd be nice to have benchmarks that cover more of the twisted.web HTTP server's surface area.

**Describe the solution you'd like**

Add some benchmarks that cover stuff like:

- Chunked encoding
- Large bodies

### PR DESCRIPTION
**Pull request by twm**
I also yoinked a few benchmarks from #12202.

Also address some deprecation warnings within the benchmark suite.

## Scope and purpose

Fixes #12257.

### CODE REVIEW

**Comment by twm** [comment]
The coverage failure looks like a flake (all of the code this adds has coverage according to the benchmark report), so please review!

**Comment by adiroiban** [comment]
It looks like the gtk test reports were not accounted for


https://app.codecov.io/gh/twisted/twisted/pull/12258/indirect-changes

As a general code cleanup task, we might want to look into increasing the visibility for "indirect changes"

**Comment by adiroiban** [comment]
I can see the reports were uploaded and were received by codecov.io ... but they failed to be processed

https://app.codecov.io/gh/twisted/twisted/commit/c678ea77f853b9d7543e9fc4c764c4e050a882fa


image

**Review by adiroiban — APPROVED** [review]
Thanks for the `tox` update.

I don't know what criteria to use when reviewing the benchmark tests. I don't have much exprience with benchmark tests.

I think that we can have them ... and see how it goes.

Thank again for the update.

**Comment by twm** [comment]
> I don't know what criteria to use when reviewing the benchmark tests. I don't have much exprience with benchmark tests.

Nor do I. I figure just write some code that does stuff and we'll get useful traces out of CodSpeed.

Thank you for the review!

**Pull request merged**
