### PR TITLE
Remove "import _preamble" to eliminate pyflakes warnings

### PR DESCRIPTION
**Pull request by rodrigc**
http://twistedmatrix.com/trac/ticket/9247

### CODE REVIEW

**Comment by rodrigc** [comment]
@glyph @hawkowl please review this.

**Comment by rodrigc** [comment]
Without this fix, Travis is failing like this:
https://travis-ci.org/twisted/twisted/jobs/260805366

**Comment by hawkowl** [comment]
Preamble is used and has side effects, though.

**Comment by hawkowl** [comment]
Turns out _preamble is broken, so removing it isn't a big deal. I document a workaround in the release notes already (because it's broken)

**Comment by rodrigc** [comment]
@hawkowl in this case should we also remove mention of _preamble from https://github.com/twisted/twisted/blame/trunk/docs/core/development/policy/coding-standard.rst#L380

**Comment by rodrigc** [comment]
@hawkowl and maybe remove mention of it from MANIFEST.in: https://github.com/twisted/twisted/blob/trunk/MANIFEST.in#L8

**Comment by hawkowl** [comment]
@rodrigc the coding standard is outdated anyway (no scripts go in bin/ anymore), we should do that in a different ticket

**Comment by rodrigc** [comment]
@hawkowl OK, I've got a patch here which removes references to _preamble.py: ​https://github.com/twisted/twisted/pull/856

**Pull request merged**
