### PR TITLE
Delete useless alias

### PR DESCRIPTION
**Pull request by rememberYou**
* [x] There is an associated ticket in Trac. https://twistedmatrix.com/trac/ticket/9428
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests.

### CODE REVIEW

**Review by adiroiban — CHANGES_REQUESTED** [review]
Thanks for the cleanup.
This is missing a newsfragment and this is needed in order to merge this.

It can be a .misc

I see that you have checked "I have created a newsfragment in src/twisted/newsfragments/ " ... but I don't see the file. Maybe you forgot to add it to git.

Thanks!

**Comment by rememberYou** [comment]
Indeed, I fixed that.

**Comment by wiml** [comment]
@adiroiban I think your feedback is addressed?

**Comment by adiroiban** [comment]
Thanks a lot, @wiml  for the followup! You are a hero :)

**Pull request merged**
