### PR TITLE
Replace sys.maxint (which is gone in Python 3) with sys.maxsize in twisted/test

### PR DESCRIPTION
**Pull request by rodrigc**
See:
https://twistedmatrix.com/trac/ticket/8443

### CODE REVIEW

**Comment by adiroiban** [comment]
you are extreme... from patched with 2000 changes we now have patched with 2 changes ... anything under 200 changes should be easy to review

**Comment by adiroiban** [comment]
and there are 3 PR for 3 different patches, but with the same title

**Comment by rodrigc** [comment]
I wasn't sure, because even though the changes are small, the context of each usage was subtly different.  So,  I erred on the side of caution with different PR's.

**Comment by rodrigc** [comment]
Merged https://github.com/twisted/twisted/commit/c8c591dc36794121e46ec6edb27603796be0e1d1

**Comment by rodrigc** [comment]
Merged https://github.com/twisted/twisted/commit/c8c591dc36794121e46ec6edb27603796be0e1d1

**Pull request closed without merging**
