### PR TITLE
Pull requests without tickets at https://twistedmatrix.com are ignored, please remember to file a ticket

### PR DESCRIPTION
**Pull request by hawkowl**
Github won't let us disable pull requests, so hopefully this stand-in will help some people find out what to do instead.  The fact that it has conflicts in it will avoid anyone accidentally clicking the button to merge it.

Instead, see the [guidelines for filing tickets against Twisted](https://twistedmatrix.com/trac/wiki/ContributingToTwistedLabs) and the [instructions for using Git for doing so](https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch), and if you're interested in helping the project accept pull requests, [the issue for helping us migrate our infrastructure to Git](https://github.com/twisted-infra/braid/issues/163).

### CODE REVIEW

**Comment by rodrigc** [comment]
@hawkowl please change the title of this pull request to:
_Pull requests without tickets at http://twistedmatrix.com are ignored, please remember to file a ticket_

**Comment by adiroiban** [comment]
done

**Comment by rodrigc** [comment]
I suggest closing this PR.  With 62 PR's open, the subject line in this PR is not visible to people submitting new pull requests.  Until Twisted moves to the PR queue fully, I suggest that we just monitor the PR queue, and send a friendly message such as the one I mentioned in: http://twistedmatrix.com/pipermail/twisted-python/2016-June/030433.html

The original idea was mentioned by @itamarst in that e-mail thread

**Comment by adiroiban** [comment]
Why not create a PR template with this message... so that when people create new PRs they will see a message :)

**Comment by glyph** [comment]
The situation is still not as straightforward as "just submit a PR", but I think we can dispense with this horrible workaround now :-).  Hopefully we can come up with something better (a PR template would be ideal) to remind people to poke trac for as long as they still need to.

**Pull request closed without merging**
