### PR TITLE
Fixed a syntax error in a docstring

### PR DESCRIPTION
**Pull request by alex**
## Contributor Checklist:

* [x] There is an associated ticket in Trac. Create a new one at https://twistedmatrix.com/trac/ticket/9727
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests.

### CODE REVIEW

**Comment by alex** [comment]
cc: @markrwilliams who volunteered to do the paperwork on this (and whom I'm grateful to!)

**Comment by glyph** [comment]
@markrwilliams @alex the paperwork appears… incomplete.

**Review by twm — APPROVED** [review]
Okay, paperwork complete.

**Comment by alex** [comment]
Thanks!

**Pull request merged**
