### PR TITLE
relax IReactorProcess.spawnProcess to more accurately reflect impleme…

### LINKED ISSUE #11824: IReactorProcess.spawnProcess is too strict
Every implementation of `spawnProcess` supplies numerous defaults, but the interface specifies that you have to pass values for everything.

This is particularly a problem because many `Optional` arguments are typed as requiring a value, which makes it impossible to say things like "don't change working directory" or "don't try to `setuid`".

### PR DESCRIPTION
**Pull request by glyph**
…ntations

## Scope and purpose

Fixes #11824 

Add a few words about why this PR is needed and what is its scope.
If the associate ticket(s) fully explain the need you can just refer to it/them.

Add any comments about trade-offs (if any) made in this PR and the reasoning behind them.

Add mentions of things that are not covered here and are planed to be done in separate PRs.

## Contributor Checklist:

This process applies to *all* pull requests - no matter how small.
Have a look at [our developer documentation](https://docs.twisted.org/en/latest/core/development/dev-process.html) before submitting your Pull Request.

Below is a non-exhaustive list (as a reminder):

* The title of the PR should describe the changes and starts with the associated issue number, like “#1234 Brief description”.
* A release notes news fragment file was create in src/twisted/newsfragments/ (see: [Release notes fragments docs.](https://docs.twisted.org/en/latest/core/development/dev-process.html#release-notes-management))
* The automated tests were updated.
* Once all checks are green, request a review by leaving a comment that contains exactly the string `please review`.
  Our bot will trigger the review process, by applying the pending review label
  and requesting a review from the Twisted dev team.

### CODE REVIEW

**Comment by glyph** [comment]
please review

**Comment by glyph** [comment]
please review

**Review by twm — APPROVED** [review]
Looks great! This matches my own experience with alternative (test) implementations. Thank you and please merge!

**Comment by glyph** [comment]
Thanks for the review @twm!

**Pull request merged**
