### PR TITLE
[9489] Preliminary 3.7 testing on Travis and AppVeyor with allowed failures

### PR DESCRIPTION
**Pull request by altendky**
https://twistedmatrix.com/trac/ticket/9489

### CODE REVIEW

**Comment by rodrigc** [comment]
This failed on Travis: https://travis-ci.org/twisted/twisted/jobs/424995182
Looks like it tries to download a Python 3.7.0 tarball which doesn't exist.

**Comment by rodrigc** [comment]
Looks like Python 3.7 support on Travis isn't fully there yet.  This is one posted workaround: https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442

but that solution disables running the Travis workers as containers, and instead full VM's, so there is a performance issue with that.

**Comment by rodrigc** [comment]
Appveyor on Python 3.7 works, but the test fails for some reason here: https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-5339/job/v504ksuudy5dsnty#L20038

Looks like a compilation problem with the native code.

**Comment by rodrigc** [comment]
For the travis.yml, can you apply the workaround for Python 3.7 mentioned here:

https://github.com/travis-ci/travis-ci/issues/9815

**Comment by altendky** [comment]
Yeah, I had done the Travis dance recently but forgot as I kicked this out quickly...  And the Windows/AppVeyor side is already [ticketed](https://twistedmatrix.com/trac/ticket/9501) and [PRed](https://github.com/twisted/twisted/pull/1050).

**Review by rodrigc — APPROVED** [review]
Well Python 3.7 ran the tests on Travis with only 3 failures.
You've obviously gone through a lot of pain to get this going.

Great work.

I say let's get this in, and it will make it easier to fix the failures on Python 3.7

**Pull request merged**
