### PR TITLE
[#11857] Run GHA tests with Python 3.12 alpha.

### LINKED ISSUE #11857: Enable python 3.12 rc on GitHub Actions
GHA has 3.12 alpha 

I think that we can give it a try and prepare Twisted for the future Python version.

@hrnciar has already started some cleanup for deprecated and now removed functions.

I think that more will be removed ... crypto / spwd 

List of modules here https://peps.python.org/pep-0594/#deprecated-modules

For 3.12 I think that we are ok, so I expect this to be easy.

3.13 will be more complicated with the removal of `cgi` and `spwd`

### PR DESCRIPTION
**Pull request by adiroiban**
## Scope and purpose

Fixes #11857

Enables 3.12 alpha test run in GitHub Action... and minimal changes to make it green

### CODE REVIEW

**Comment by adiroiban** [comment]
needs-review

**Comment by adiroiban** [comment]
I now see that 3.12 tests are failing... this needs more work

**Comment by adiroiban** [comment]
needs-changes

**Comment by graingert** [comment]
closing in favour of #11910

**Pull request closed without merging**
