### PR TITLE
[#10200] Force using GTK+3 in twisted.internet.gireactor

### LINKED ISSUE #10200: Test failures and hang when GTK+4 is installed in the system
|[mgorny's avatar](https://github.com/mgorny)| @mgorny reported|
|-|-|
|Trac ID|trac#10200|
|Type|defect|
|Created|2021-05-21 22:52:30Z|

I can reproduce the problem with 21.2.0 and git cae365213868e8226a055f6b5e4d2c0c89c9ab3b.

If GTK+4 is installed, the test runner gives the following warning:

```
$ PYTHONPATH=build/lib python3.9 -m twisted.trial -x twisted 
/tmp/twisted/build/lib/twisted/internet/test/test_gireactor.py:28: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```

Then a fair number of tests fail, and the test suite eventually seems to hang on NewFetchTests -> testFetchEnvelope.

If I add `-x` option, the first test failures I get is:
```
[ERROR]
Traceback (most recent call last):
  File "/tmp/twisted/build/lib/twisted/internet/test/test_gireactor.py", line 100, in test_gtkApplicationActivate
    reactor = gtk3reactor.Gtk3Reactor()
  File "/tmp/twisted/build/lib/twisted/internet/gtk3reactor.py", line 35, in __init__
    gireactor.GIReactor.__init__(self, useGtk=True)
  File "/tmp/twisted/build/lib/twisted/internet/gireactor.py", line 73, in __init__
    _glibbase.GlibReactorBase.__init__(self, GLib, _gtk, useGtk=useGtk)
  File "/tmp/twisted/build/lib/twisted/internet/_glibbase.py", line 115, in __init__
    self._pending = self._gtk.events_pending
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
builtins.AttributeError: 'gi.repository.Gtk' object has no attribute 'events_pending'

twisted.internet.test.test_gireactor.GApplicationRegistrationTests.test_gtkApplicationActivate
```

I'm going to try making a patch for it.

<details><summary>Searchable metadata</summary>

```
trac-id__10200 10200
type__defect defect
reporter__mgorny mgorny
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__review review
time__1621637550918891 1621637550918891
changetime__1627536347422898 1627536347422898
version__None None
owner__None None

```
</details>

### PR DESCRIPTION
**Pull request by mgorny**
## Scope and purpose

Fixes #10200

Twisted uses incompatible GTK+4 when installed. This patch forces GTK+3 to avoid the problems.

It does not cover adding GTK+4 compatibility ;-).

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10200
* [x] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [x] The title of the PR starts with the associated Trac ticket number (without the `#` character).
* [ ] I have updated the automated tests and checked that all checks for the PR are green.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.
* [ ] The merge commit will use the below format
  The first line is automatically generated by GitHub based on PR ID and branch name.
  The other lines generated by GitHub should be replaced.

```
Merge pull request #123 from twisted/4356-branch-name-with-trac-id

Author: <github_username>, <github_usernames_if_more_authors>
Reviewer: <github_username>, <github_username_if_more_reviewers>
Fixes: ticket:<trac_ticket_number>, ticket:<another_if_more_in_one_PR>

Long description providing a summary of these changes.
(as long as you wish)
```

### CODE REVIEW

**Comment by mgorny** [comment]
I don't think I can improve the coverage on this, really (or at least not within the scope of this PR).

**Comment by glyph** [comment]
> I don't think I can improve the coverage on this, really (or at least not within the scope of this PR).

It's likely that, particularly with an overflowing review queue, reviewers are likely to skip over this unless it has a passing commit status. If you don't think that coverage on these lines are important, could you put `# pragma: no-cover` lines to make codecov chill out? The reviewer can then see it's intentional and potentially disagree, but the checkmark will be green at least :).  (And you can include a comment next to it explaining why coverage is difficult.)

**Comment by mgorny** [comment]
> > I don't think I can improve the coverage on this, really (or at least not within the scope of this PR).
> 
> It's likely that, particularly with an overflowing review queue, reviewers are likely to skip over this unless it has a passing commit status. If you don't think that coverage on these lines are important, could you put `# pragma: no-cover` lines to make codecov chill out? The reviewer can then see it's intentional and potentially disagree, but the checkmark will be green at least :). (And you can include a comment next to it explaining why coverage is difficult.)

Thanks for the suggestion. However, no matter how hard I try, it doesn't seem to work :-(. Maybe the `no cover` pragma doesn't work for diffs?

**Comment by adiroiban** [comment]
I am updating the branch.

We now run some GTK reactors tests as part of the CI.

**Comment by adiroiban** [comment]
I think that this needs-changes

See https://github.com/twisted/twisted/issues/10200#issuecomment-1240780890 comment from here

There is a report that the code still needs changes

**Comment by glyph** [comment]
I'm working on a fix in #11706 that somewhat obviates the need for this; there is now only one place we import Gtk, and it's in the test suite, which can be controlled with an env var if so desired, but defaulting to 4.0 (which, hey, has actual compatibility guarantees, supposedly!).

We will need some updates in the docs, though, since we still refer to *truly* ancient gtk2-style code in a lot of places.

**Comment by glyph** [comment]
I think that #11705 fixed the underlying problem here.  If Gtk3 systems still need help, please open a new PR.

**Pull request closed without merging**
