### PR TITLE
twisted.web.wsgi supports py3	

### PR DESCRIPTION
**Pull request by alex**
https://twistedmatrix.com/trac/ticket/8276

### CODE REVIEW

**Comment by frewsxcv** [comment]
Relevant issue and patch:

* https://twistedmatrix.com/trac/ticket/8276
* https://twistedmatrix.com/trac/attachment/ticket/8276/wsgi.patch

**Comment by alex** [comment]
Nice catch, I will do the `test_tap.py` pieces as well

**Comment by hawkowl** [comment]
LGTM.

**Comment by frewsxcv** [comment]
Does Twisted have an official policy for often ~~releasing~~ releases happen?

**Pull request merged**
