### PR TITLE
Ported twisted.internet._threadedselect to Py3 

### PR DESCRIPTION
**Pull request by them0ntem**
Ported` twisted.internet._threadedselect` to Py3 with maintaining compatibility to Py2.

https://twistedmatrix.com/trac/ticket/9053

### CODE REVIEW

**Comment by rodrigc** [comment]
Good stuff.
Take out the __future__ import of generators.   According to https://docs.python.org/2/library/__future__.html.  generators became mandatory in Python 2.3.  Right now Python 2.7 is the minimum supported.

**Comment by rodrigc** [comment]
Even though they are commented out, please change the print statements to print functions (leave them commented out) and add a __future__ import statement for print_function at the too of the file.

**Comment by rodrigc** [comment]
Please follow all the steps at https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch , specifically you need a topfiles news fragment.

**Comment by them0ntem** [comment]
open new pull request #717 after following follow all the steps at https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

**Comment by rodrigc** [comment]
Actually on second thought just the delete the commented out print statements.  They are not needed and just clutter the code.

**Comment by them0ntem** [comment]
@rodrigc i have opened new PR with changes #717 after following all right steps.

**Pull request closed without merging**
