### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by scop**
https://twistedmatrix.com/trac/ticket/8630

### CODE REVIEW

**Comment by alex** [comment]
👍  lgtm

**Comment by rodrigc** [comment]
I am amazed that it was possible for you to even find and fix these spelling errors.

**Comment by rodrigc** [comment]
In future, in your branch, when you add a topfile, add it in a separate commit in your branch,
so that in future it is separate from the git log of the different files.

**Comment by rodrigc** [comment]
Also, for the topfile, you created 8630.doc but kept it empty.
According to https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles , only a misc
file can be empty.  All other topfiles need to have a single line in them that will end up in the release notes.

The changes in this branch are trivial so I will just rename your topfile to misc

**Comment by rodrigc** [comment]
Merged in https://github.com/twisted/twisted/pull/364

**Pull request closed without merging**
