### PR TITLE
Add CPython 3.8 to CI

### PR DESCRIPTION
**Pull request by altendky**
https://twistedmatrix.com/trac/ticket/9798

### CODE REVIEW

**Comment by altendky** [comment]
https://github.com/microsoft/azure-pipelines-tasks/issues/9302

**Comment by altendky** [comment]
It would sure be cool if there was some indication on this page of failing allowed failures but it's not obvious how that could be done presently.  At least the CI runs will be there for people that are looking to fix the issues though.  For now you have to go to the actual Travis and Azure pages to see the failure indications.

**Comment by rodrigc** [comment]
@altendky Can you review this: https://github.com/twisted/twisted/pull/1251

I think that fixes a lot of Python 3.8 test failures

**Comment by altendky** [comment]
confusion...  discussion at https://twistedmatrix.com/trac/ticket/9799#comment:9

**Pull request merged**
