### PR TITLE
twisted.conch.telnet now implements End of Record (EOR) command (RFC 885)

### PR DESCRIPTION
**Pull request by NimVek**
## Contributor Checklist:

* [X] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9875
* [X] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [X] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [X] I have updated the automated tests.
* [X] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Review by rodrigc — CHANGES_REQUESTED** [review]
This is an improvement on https://github.com/twisted/twisted/pull/1320 .  Thanks for writing the test.

However, this patch is still failing style checks.  Can you run the `tox` command listed here: 
https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted

and fix the reported style issues?

**Comment by NimVek** [comment]
Have you checked the style issues?
The issues are in the lines around my patches, if i change the lines around my patches i must also change the lines around them and so so. In the end i must reformat the whole file, i thouth its not good if path changes so much.
I would do the formating if you, accept that i must change lines that i never touched with my patch before.

**Comment by rodrigc** [comment]
Yes, it is OK if you format the file, even parts which you did not modify.
Unfortunately, the code in this file was written before some of the automated style-checkers were fully implemented,
so when people modify such a file, the style checker complains even about lines that they did not modify.

But it is OK for you to fix these lines in this file as part of this PR.

**Comment by NimVek** [comment]
Hope its ok, how i formatted the code.

**Review by rodrigc — APPROVED** [review]
This looks good.  I agree, fixing the style issues in lines unrelated to the ones you changed is a bit of a headache, but thanks for doing it.

**Comment by rodrigc** [comment]
Thanks for your contribution.  You should now see your name in: https://twistedmatrix.com/highscores/

**Pull request merged**
