### PR TITLE
PEP 3110 - change exception handling to use new "except ... as ..." syntax

### PR DESCRIPTION
**Pull request by rodrigc**
https://twistedmatrix.com/trac/ticket/8344

### CODE REVIEW

**Comment by rodrigc** [comment]
This command was useful for locating the places that needed to be fixed:

```
2to3 -f except
```

**Comment by adiroiban** [comment]
all good. thanks. will merge

**Comment by rodrigc** [comment]
If you close out a PR, without clicking the "Merge" button, but you did do the merge,
please add to the audit trail of the PR with the changeset where you did the merge.  This makes things easier for folks to follow in the future.  For example:

**Comment by rodrigc** [comment]
Merged: https://github.com/twisted/twisted/commit/cd248d04fea464ad25837155412a47ac3caa6c21

**Comment by adiroiban** [comment]
If I am pulling from your branch, it will detect that this pr is merged and will close it.

see https://github.com/twisted/twisted/pull/68

for this one I has no idea why that auto-close was not working.

**Pull request closed without merging**
