### PR TITLE
[9781] Change some http:// links to https://

### PR DESCRIPTION
**Pull request by twm**
I've tried to keep this purely mechanical to keep it easy to review. I'll follow a follow-up ticket to fix more once this is in.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9781
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests. (N/A)
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Review by rodrigc — CHANGES_REQUESTED** [review]
@twm Can you run `tox -e lint` and fix some of the style errors?

Other than that this looks OK.

**Review by rodrigc — APPROVED** [review]
Lint errors are gone

**Comment by rodrigc** [comment]
@twm can you update this branch to trunk, and merge it?

**Comment by twm** [comment]
@rodrigc I will do so. Thank you for the review!

**Pull request merged**
