### PR TITLE
Run separate Appveyor tests for select and iocp reactor

### PR DESCRIPTION
**Pull request by rodrigc**
https://twistedmatrix.com/trac/ticket/8677

### CODE REVIEW

**Comment by rodrigc** [comment]
This is a replacement for https://github.com/twisted/twisted/pull/412

**Comment by rodrigc** [comment]
@opalmer can you review this?  You can see the appveyor results from this change here: https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-1005

**Comment by opalmer** [comment]
Looks good 👍 .

What would you think about adding build artifacts so the built wheels, coverage, etc can be downloaded after the build is complete?  Does not have to be in this PR of course...

**Comment by rodrigc** [comment]
@opalmer In terms of coverage, this build is running coverage and uploading the coverage results to codecov.io.  In the past, I don't believe that the Twisted project made build artifacts available from the buildbots, so this would be a new thing for the Twisted project.  I think it is a reasonable idea though.

I think the current direction is to see if appveyor can be integrated with the release process,
so that for each release, the wheels for Windows would be generated from appveyor.

**Pull request merged**
