### PR TITLE
Enable the travis cache

### PR DESCRIPTION
**Pull request by alex**
https://twistedmatrix.com/trac/ticket/8420

### CODE REVIEW

**Comment by rodrigc** [comment]
@alex thanks for submitting the patches.  Just an FYI, you need to follow all the steps here: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch
to file a ticket.
The Twisted devs won't look at your pull request without one.  And don't forget the topfile! :)

**Comment by alex** [comment]
@rodrigc Glyph totally told me I could just sent pull requests here at the PyCon sprints :-)

**Comment by rodrigc** [comment]
Oh OK, that's fine then.
But without a topfile, your PR's will show up as Travis build failures due to: https://github.com/twisted/twisted/blob/trunk/tox.ini#L74

You might want to follow up with @glyph about that

**Comment by cyli** [comment]
Awesome, this sped up the elapsed time for tests by about a minute.  Thank you for the fix!

**Pull request merged**
