### PR TITLE
twisted.web.error.UnsupportedMethod makes the allowed methods look like they're unsupported

### PR DESCRIPTION
**Pull request by Julian**
https://twistedmatrix.com/trac/ticket/7744

### CODE REVIEW

**Comment by wsanchez** [comment]
You need to file a Trac ticket that references this if you want it reviewed and merged.

https://twistedmatrix.com/trac/report

**Comment by Julian** [comment]
It's in the title :) and was already reviewed, although maybe too long ago.

**Comment by wsanchez** [comment]
Duh, sorry

**Comment by wsanchez** [comment]
Heh, *I* reviewed it. Updating; will merge if tests still pass.

**Comment by Julian** [comment]
:DDD thanks!

**Pull request merged**
