### PR TITLE
[#9049] Stop hashing random bytes for no particular reason

### PR DESCRIPTION
**Pull request by alex**
crypto-gibberish is bad.

https://twistedmatrix.com/trac/ticket/9049

### CODE REVIEW

**Comment by glyph** [comment]
Thanks alex! Looks good to me. I think that this was originally a timestamp or something? In any case yes cryptogibberish is bad.

sha1 on your mind today for some reason? Just stopping by? 😏

**Comment by alex** [comment]
It was SHA1 gibberish going back at least as far as 2005, I stopped scanning the history at that point.

**Comment by alex** [comment]
The codecov results appear to be nonsense. Can someone do something so the buildbot runs and this can be merged?

**Comment by glyph** [comment]
Thing done.

**Comment by alex** [comment]
👍  thanks! we're all green here.

**Comment by glyph** [comment]
Thanks for the fix, @alex.

**Comment by alex** [comment]
Happy to!

**Pull request merged**
