### PR TITLE
Python3 porting of imap4: make half the tests pass

### PR DESCRIPTION
**Pull request by berdario**
This PR builds on top of https://github.com/twisted/twisted/pull/542

It retains compatibility with Python2, and (together with #541 ) gets closer to Python3 compatibility for the imap module, but plenty of tests still fail

https://twistedmatrix.com/trac/ticket/8830#ticket

### CODE REVIEW

**Review by rodrigc — CHANGES_REQUESTED** [review]
The http change needs to be removed from this pull request.  That is already covered in https://github.com/twisted/twisted/pull/542

**Comment by rodrigc** [comment]
pyflakes test is failing: https://travis-ci.org/twisted/twisted/jobs/160848733#L397

**Comment by berdario** [comment]
Applied the changes and Travis passed... let's see the outcome for Appveyor

**Comment by rodrigc** [comment]
Some of the patches in this PR overlapped with other patches that I had, so I merged them in https://github.com/twisted/twisted/pull/544

**Pull request closed without merging**
