### PR TITLE
6960 cfrunloopsourceinvalidate

### LINKED ISSUE #6960: Use CFRunLoopRemoveSourceInvalidate instead of CFRunLoopRemoveSource in CFReactor
|BobNovas's avatar| BobNovas reported|
|-|-|
|Trac ID|trac#6960|
|Type|defect|
|Created|2014-02-10 18:28:12Z|

If you are using CFReactor, and doing your own IO (in particular, using 
pybonjour and adding your file descriptor to the reactor's reader list
(e.g., reactor.addReader), then, if you close the file descriptor before
you call removeReader, on some platforms (Lion) you will likely wind up
in CFRunLoopRemoveSource in a spinlock waiting on the FD.  The solution is 
either to ensure that you call removeReader before closing the FD, or
CFReactor could solve the problem by using CFRunLoopRemoveSourceInvalidate
instead of CFRunLoopRemoveSource at line 300.

See http://icodeanswer1.appspot.com/post/709526 and attached crash
report.txt file.

Attachments:

* [crashreport.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/708/70875fe7aa9f60b30f01f4a2c8562bc257eed414/0305b3aa7c246fc0949d1996ea3af993ef1af85c.txt) (64261 bytes) - added by BobNovas on 2014-02-10 18:29:26Z - Typical hang showing spinlock in CFRunLoopRemoveSource

<details><summary>Searchable metadata</summary>

```
trac-id__6960 6960
type__defect defect
reporter__BobNovas BobNovas
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__cfreactor__spin_lock__CFRunLoopRemoveSource cfreactor, spin lock, CFRunLoopRemoveSource
time__1392056892000000 1392056892000000
changetime__1392056892000000 1392056892000000
version__None None
owner__ 

```
</details>

### PR DESCRIPTION
**Pull request by glyph**
## Scope and purpose

Fixes #6960 

Not sure if this is going to help that much, but if it's this simple it's worth trying.

### CODE REVIEW

**Comment by glyph** [comment]
Hmm, given that we got the same issue on the first build here, seems that we have not fixed it

**Comment by glyph** [comment]
(I wonder if this is still worth doing on its own merits?)

**Comment by adiroiban** [comment]
Thanks!

As long as we keep only the #6960 newsfragment in this PR, I think that we can still make the change.

**Comment by glyph** [comment]
> As long as we keep only the #6969 newsfragment in this PR, I think that we can still make the change.

Do you mean #6960 ?

**Comment by adiroiban** [comment]
> Do you mean https://github.com/twisted/twisted/issues/6960 ?

Yes. Sorry. It was about #6960

**Comment by glyph** [comment]
I am not totally sure that this is correct and we have found another cause for #11771 so I am going to close this.

**Pull request closed without merging**
