### PR TITLE
Implement ReconnectingClientService for endpoints.

### PR DESCRIPTION
**Pull request by hodgestar**
See https://twistedmatrix.com/trac/ticket/4735.

### CODE REVIEW

**Comment by glyph** [comment]
We don't accept pull requests currently.  I am closing this so that nobody accidentally presses the "merge pull request" button, which we can't turn off and which would break our mirroring scripts if someone were to hit it inadvertently.

**Comment by hodgestar** [comment]
You may wish to update the first paragraph of
http://twistedmatrix.com/trac/wiki/GitMirror#SubmittingPatches in that case.

**Comment by hodgestar** [comment]
You can probably avoid inadvertent PR landing by ensuring that only
the user that is used for the svn mirroring is allowed commit access
to the repo?

**Comment by glyph** [comment]
How can I do that without kicking everyone out of the Twisted org?

**Pull request closed without merging**
