### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### twisted/twisted now has a Chat Room on Gitter

@graingert has just created a chat room. You can visit it here: [https://gitter.im/twisted/twisted](https://gitter.im/twisted/twisted?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/twisted/twisted?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://gitlab.com/gitlab-org/gitter/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by graingert** [comment]
probably we don't want to land this unless the community actually moves here

**Comment by adiroiban** [comment]
I am going to leave it open as a reminder ...and we can badge it later.

There is  not much twisted community these days... and I would prefer not to split it.
At the same time, for new and young contributors, IRC might not be he most friendly  tool.

We need to move the whole twistedmatrix.com server somewhere else ... so maybe we can use gitter to coordinate with that work... as an experiment.

**Review by adiroiban — APPROVED** [review]
I think that we can add gitter to README.
It's a nice service and is federated via matrix.org

I will see how to land this without a newsfragment

**Comment by adiroiban** [comment]
@graingert if you are aproving it, I think that we can bite the bullet and merge it even if it has no newsfragment

the idea of requesting a newsfragment for each PR is to make sure we don't forget new features for the release notes... but I am not sure if gitter usage should be recorded in the NEWS file.

**Pull request merged**
