### PR TITLE
#12015 Replace cgi.escape and cgi.parse_header

### LINKED ISSUE #12015: Replace cgi.escape with html.escape
the idea is to take the non controversial changes from https://github.com/twisted/twisted/issues/11919 and merge them in a separate PR

we can then also merge the controlversial changes... if we need to revert the merge for the controversial change, we can do that

### PR DESCRIPTION
**Pull request by adiroiban**
## Scope and purpose

Fixes #12015

This is the code  done by @graingert in https://github.com/twisted/twisted/pull/11918

but without the multipart parsing.

I think that the multipart part can be done in the separate PR and maybe coordinate with https://github.com/twisted/treq/issues/355

These changes from here are supposed to be non-controversion and be easy to merge.

### CODE REVIEW

**Comment by adiroiban** [comment]
@twm and @graingert  If you have time, please take a look and see if this can be merged.

-------

The only thing left from CGI is multipart parsing.
And basically, this is the same questions as https://github.com/twisted/treq/issues/355

I would say that we can try to use stdlib Message to parse the multipart.

Colin suggested using `multipart` , but at this point, I would prefer to use stdlib and if needed send fixes upstream to Python

I hope we can take a decision as part of https://github.com/twisted/twisted/pull/11918

needs-review

**Comment by nandgator** [comment]
Can someone please link issue #11750.

Closes #11750

**Review by graingert — APPROVED** [review]

**Comment by graingert** [comment]
Lgtm

**Comment by adiroiban** [comment]
Thanks. I have enabled auto-merge for this PR.

**Comment by glyph** [comment]
amazing, thank you @adiroiban and @graingert .  glad we are finally free of this legacy dependency

**Comment by glyph** [comment]
Also, just for posterity: any use of `html.escape` should *eventually* be replaced with `twisted.web.template`.  We have a whole templating system, we should use it :)

**Pull request merged**
