### PR TITLE
#11915 Release 2023.8.0

### LINKED ISSUE #11915: Release 2023.8.0
this is to track the release

### PR DESCRIPTION
**Pull request by adiroiban**
## Scope and purpose

Fixes #11915

This is the release PR for 2023.8.0

Following the info from here https://docs.twisted.org/en/latest/development/release-process.html

To  get the CI green for this PR, I have updated the way we call `towncrier check`
I trie to keep the changes in this PR to a minimum. 
Followup changes at https://github.com/twisted/twisted/pull/11917

### CODE REVIEW

**Review by graingert — APPROVED** [review]

**Comment by adiroiban** [comment]
Many thanks for the review

Release candidate is here https://github.com/twisted/twisted/releases/tag/twisted-23.8.0rc1

GitHub Actions run is here https://github.com/twisted/twisted/actions/runs/5895893160

PyPi https://pypi.org/project/Twisted/23.8.0rc1/

**Comment by adiroiban** [comment]
Thanks for the review.

It looks like there are some flaky tests.
I will wait one week to allow people to test RC1 and then I will push the final release.

Thanks again

**Comment by glyph** [comment]
> It looks like there are some flaky tests.

looking at the build failure here I don't see flaky tests (perhaps they re-ran?) but I do see the towncrier check failing.

Is there a bug on towncrier already open for release branches like this? It's a shame to see a failing status when things are working as designed.

**Comment by adiroiban** [comment]
The RC1 job was green after the 3rd attempt - https://github.com/twisted/twisted/actions/runs/5894966260/job/15990264559 

Preview

image

**Comment by adiroiban** [comment]
There is something strange going on with towncrier here.

The support for release PR check was added in towncrier 22.8 ... and we are already depending on 22.12

On my local system `tox -q -e newsfragment` work just fine... I think we need more debuging for the CI run

I am looking into  this

**Comment by adiroiban** [comment]
It looks like we were using a newer towncrier... but still using our old hack to check for fragments.

I have updated the code to use towncrier own check code

As part of https://github.com/twisted/twisted/issues/11583 I will also remove the script and we can test the checks on a non-release PR.

**Comment by adiroiban** [comment]
I think this is now ready for review.
Release candidate is published.
CI is all green.

needs-review

**Review by graingert — APPROVED** [review]

**Comment by adiroiban** [comment]
I added a few GHA changes to get the test run, even before merge

I think this is ready for a final release

needs-review

**Review by graingert — APPROVED** [review]

**Comment by adiroiban** [comment]
Many thanks for the review.

I have triggered the final release here https://github.com/twisted/twisted/actions/runs/6002680184

Once this is on PyPI I will update with trunk and merge.

**Comment by graingert** [comment]
https://pypi.org/project/Twisted/23.8.0/ is on pypi

**Comment by adiroiban** [comment]
Thanks for your help with the review.
I have enabled auto-merge for this PR.

Hope all tests will be green and this can be merged.

pre-commit was complaining about merge conflict marker... so I have updated the markup for readme.

```
Merge conflict string "=======
" found in README.rst:2
```

**Pull request merged**
