### PR TITLE
#11768 upgrade incremental

### LINKED ISSUE #11768: upgrade incremental
We are currently pinned to trunk but 22.10.0 has the mypy stubs we need.

### PR DESCRIPTION
**Pull request by glyph**
## Scope and purpose

Fixes #11768

Add a few words about why this PR is needed and what is its scope.
If the associate ticket(s) fully explain the need you can just refer to it/them.

Add any comments about trade-offs (if any) made in this PR and the reasoning behind them.

Add mentions of things that are not covered here and are planed to be done in separate PRs.

## Contributor Checklist:

This process applies to *all* pull requests - no matter how small.
Have a look at [our developer documentation](https://docs.twisted.org/en/latest/core/development/dev-process.html) before submitting your Pull Request.

Below is a non-exhaustive list (as a reminder):

* The title of the PR should describe the changes and starts with the associated issue number, like “#1234 Brief description”.
* A release notes news fragment file was create in src/twisted/newsfragments/ (see: [Release notes fragments docs.](https://docs.twisted.org/en/latest/core/development/dev-process.html#release-notes-management))
* The automated tests were updated.
* Once all checks are green, request a review by leaving a comment that contains exactly the string `please review`.
  Our bot will trigger the review process, by applying the pending review label
  and requesting a review from the Twisted dev team.

### CODE REVIEW

**Comment by glyph** [comment]
I have enabled auto-merge so an approving review should merge this.

**Review by meejah — APPROVED** [review]
LGTM!

(I am assuming the macos 12 failures are unrelated..?)

**Comment by exarkun** [comment]
> LGTM!
> 
> (I am assuming the macos 12 failures are unrelated..?)

cfreactor :/ heh heh :/

**Comment by exarkun** [comment]
> > LGTM!
> > (I am assuming the macos 12 failures are unrelated..?)
> 
> cfreactor :/ heh heh :/

Filed https://github.com/twisted/twisted/issues/11771

**Review by exarkun — APPROVED** [review]

**Pull request merged**
