### PR TITLE
#11982 Update pre-commit tools, with the exception of black.

### LINKED ISSUE #11982: Update pre-commit tools
The plan is to update the pre-commit tools, with the exception of `black`.

We can update black as part of https://github.com/twisted/twisted/issues/11961 or https://github.com/twisted/twisted/pull/11962

`black` is a separate beast since updating it will cause 170+ files to also be updated.

### PR DESCRIPTION
**Pull request by adiroiban**
## Scope and purpose

Fixes #11982

This is basically the work done by @graingert  in https://github.com/twisted/twisted/pull/11962 but without the `black` changes.

I hope we can get this merged and then we can focus on the `black` upgrade

### CODE REVIEW

**Comment by adiroiban** [comment]
I think that this is ready for review 

@graingert this is 99% your work.

I went with inline `#noqa`

needs-review

**Comment by adiroiban** [comment]
this needs an update for mypy

```
src/twisted/internet/defer.py:1442:1: error: Name "DeferredList" already defined on line 1439  [no-redef]
src/twisted/internet/defer.py:1444: error: Unused "type: ignore" comment  [unused-ignore]
```

**Review by graingert — APPROVED** [review]

**Comment by adiroiban** [comment]
Many thanks for the  review.

I have moved the inline  comment for mypy ... black was reformating the code.

I have enabled auto-merge. Hope all goes well.

**Comment by glyph** [comment]
Thanks for splitting this stuff out so we can move forward faster and not block on Black! :)

**Pull request merged**
