### PR TITLE
Revert "#8840 re-enable PTY tests on macOS"

### PR DESCRIPTION
**Pull request by glyph**
Reverts twisted/twisted#12165

Reopens #8840

### CODE REVIEW

**Comment by glyph** [comment]
Test failures on #986 suggests that this is still flaky and the kernel issue is not fixed.

**Comment by glyph** [comment]
The newsfragment check is just broken and its failure should be ignored here. https://github.com/twisted/towncrier/issues/598

**Review by adiroiban — APPROVED** [review]
Thanks. Reopens will not work in GitHub... but I will reopen it manually.

This also needs to be "forced merged" as the newsfragment check is mandatory.

**Comment by glyph** [comment]
Thanks!

**Pull request merged**
