### PR TITLE
12225 Optimize the Deferred await benchmark

### LINKED ISSUE #12225: Optimize the Deferred await benchmark
1. `succeed()` can definitely be significantly improved.
2. awaiting may be optimizable too, not sure yet.

### PR DESCRIPTION
**Pull request by itamarst**
## Scope and purpose

Fixes #12225 

* `await` on Deferred is now much faster, by avoiding raising `StopIteration()`, instead using a generator which appears to have a fast path.
* `succeed()` is now much faster (twice as fast?).

Minor backwards incompatibilities, which I think are OK:

* `next(Deferred())` no longer works, likewise `Deferred.send()`. Not sure why anyone would have done that, it was implementation detail. These were technically public APIs. On the other, no tests started failing when I made this change.
* `succeed(Failure())` no longer works. This violated the type annotations and intention of the function, so I would consider it a user bug if someone was doing this.

This is a significant change to implementation of bot async/await support and `succeed()`, so please review carefully! Perhaps more tests? Not sure what to add though.

### CODE REVIEW

**Review by adiroiban — CHANGES_REQUESTED** [review]
Thanks for the review.

The changes looks good.

It looks like for Python 3.13 the traceback is now different, and we have a failing test .

```
[FAIL]
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/nodeps-withcov-posix/lib/python3.13/site-packages/twisted/web/test/test_flatten.py", line 709, in test_asynchronousFlattenError
    self.assertRegex(
  File "/opt/hostedtoolcache/Python/3.13.0-beta.3/x64/lib/python3.13/unittest/case.py", line 1369, in assertRegex
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: Regex didn't match: 'Exception while flattening:\n  \\[<unrenderable>\\]\n  <unrenderable>\n  <Deferred at .* current result: <twisted.python.failure.Failure builtins.RuntimeError: example>>\n  File ".*", line \\d*, in _flattenTree\n    element = await element.*\n[ ^]*\nRuntimeError: example\n' not found in 'Exception while flattening:\n  [<unrenderable>]\n  <unrenderable>\n  <Deferred at 0x7ff4489411d0 current result: <twisted.python.failure.Failure builtins.RuntimeError: example>>\n  File "/home/runner/work/twisted/twisted/.tox/nodeps-withcov-posix/lib/python3.13/site-packages/twisted/web/_flatten.py", line 426, in _flattenTree\n    element = await element\n              ^^^^^^^^^^^^^\n  File "/home/runner/work/twisted/twisted/.tox/nodeps-withcov-posix/lib/python3.13/site-packages/twisted/internet/defer.py", line 1174, in __iter__\n    yield self\nRuntimeError: example\n'

twisted.web.test.test_flatten.FlattenerErrorTests.test_asynchronousFlattenError
```

It might be that we just need a separate test for 3.13

Let me know if you need help with testing.

Thanks!

**Comment by itamarst** [comment]
I'm going to test this code against Tahoe-LAFS to see if it triggers any problems, and if it does will add more tests/fixes accordingly.

**Comment by itamarst** [comment]
Tahoe is fine with this branch.

**Review by adiroiban — APPROVED** [review]
Many thanks for the improvements.

I think that we should merge this.

We have some downstream projects doing tests in `trunk` and then we can see if there are any issues.

**Pull request merged**
