### PR TITLE
10239: epytext again

### PR DESCRIPTION
**Pull request by twm**
## Scope and purpose

Fix syntax errors. Fix cross-references due to move of hyper-h2 docs. Addresses these messages:

```
apidocs run-test: commands[0] | .../twisted/bin/admin/build-apidocs .../twisted/src/ apidocs
Failed to get object inventory from https://hyper-h2.readthedocs.io/en/stable/objects.inv
.../twisted/src/twisted/web/server.py:705: bad docstring: Possible mal-formatted field item.
.../twisted/src/twisted/web/server.py:705: bad docstring: Fields must be the final elements in an epytext string.
.../twisted/src/twisted/protocols/haproxy/_parser.py:32: bad docstring: Bad link target.

L{Mapping[str, str]}
                   ^
.../twisted/src/twisted/web/_http2.py:68: Cannot find link target for "h2.connection.H2Connection" (you can link to external docs with --intersphinx)
.../twisted/src/twisted/web/_http2.py:440: Cannot find link target for "h2.events.RequestReceived" (you can link to external docs with --intersphinx)
.../twisted/src/twisted/web/_http2.py:472: Cannot find link target for "h2.events.DataReceived" (you can link to external docs with --intersphinx)
.../twisted/src/twisted/web/_http2.py:484: Cannot find link target for "h2.events.StreamEnded" (you can link to external docs with --intersphinx)
.../twisted/src/twisted/web/_http2.py:495: Cannot find link target for "h2.events.StreamReset" (you can link to external docs with --intersphinx)
.../twisted/src/twisted/web/_http2.py:509: Cannot find link target for "h2.events.PriorityUpdated" (you can link to external docs with --intersphinx)
.../twisted/src/twisted/web/_http2.py:662: Cannot find link target for "h2.events.WindowUpdated" (you can link to external docs with --intersphinx)
these 2 objects' docstrings contain syntax errors:
    twisted.protocols.haproxy._parser.unparseEndpoint
    twisted.web.server.Session
```

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10239
* [x] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [x] The title of the PR starts with the associated Trac ticket number (without the `#` character).
* [x] I have updated the automated tests and checked that all checks for the PR are green. (N/A, documentation-only change)
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Review by adiroiban — APPROVED** [review]
All good. Thanks! This can be merged.

**Comment by graingert** [comment]
why did coverage decrease so much?

**Comment by adiroiban** [comment]
Is the coverage/coveralls  coverage ... the codecov.io look ok.

I think that this is just a coveralls error... this is only a docstring update and I don't see anything that could possibly reduce the coverage.

**Review by graingert — CHANGES_REQUESTED** [review]
I pushed a commit here that runs apidocs in CI. I think you should cherry pick it across

https://github.com/twisted/twisted/pull/1643

**Comment by adiroiban** [comment]
I would say that this PR is ok and can be merged.

Yes, we have .github/workflows/docs.yaml which is not failing on pydoctor warnings, but I think that should be a separate ticket and it  should not block this PR.

AFAIK, the warnings were ignored on purpose... while we improve pydoctor.

If we are ready to fail on pydoctor warnings, I think that we can call `pydoctor --warnings-as-errors` as part of the docs.yaml

**Review by graingert — APPROVED** [review]

**Comment by twm** [comment]
Thanks for the reviews! I've closed the ticket manually as the commit format was off.

**Pull request merged**
