### PR TITLE
[9954] Fade to black

### PR DESCRIPTION
**Pull request by twm**
Following up on #1380.

@rodrigc I consolidated steps 1 and 2 from [your comment](https://github.com/twisted/twisted/pull/1380#pullrequestreview-487265831) to avoid creating separate tickets and newsfiles for them.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9954
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

### CODE REVIEW

**Comment by rodrigc** [comment]
A whole bunch of CI is failing with this change.  For example:

* **mypy** failure due to reformatting **/home/runner/work/twisted/twisted/src/twisted/words/test/test_irc.py**:  https://github.com/twisted/twisted/pull/1381/checks?check_run_id=1107647491#step:5:21
* **twisted.web.test.test_util.FailureElementTests.test_sourceFragmentElement** failing: https://dev.azure.com/twistedmatrix/twisted/_build/results?buildId=2445&view=logs&j=786d9c93-0d4c-552d-b083-0885e74fd630&t=99d69555-4eea-5a30-cc7d-84ec61f55af8&l=15910

Can those be fixed in this commit somehow?

**Comment by rodrigc** [comment]
Can you add this patch to your branch:

```
diff --git a/src/twisted/web/test/test_util.py b/src/twisted/web/test/test_util.py
index e15413656..593ee583f 100644
--- a/src/twisted/web/test/test_util.py
+++ b/src/twisted/web/test/test_util.py
@@ -180,23 +180,27 @@ class FailureElementTests(TestCase):
         source = [
             " \N{NO-BREAK SPACE} \N{NO-BREAK SPACE}message = " '"This is a problem"',
             " \N{NO-BREAK SPACE} \N{NO-BREAK SPACE}raise Exception(message)",
-            "# Figure out the line number from which the exception will be " "raised.",
+            "",
         ]
         d = flattenString(None, element)
-        stringToCheckFor = "".join(
-            [
-                '<div class="snippet%sLine"><span>%d</span><span>%s</span>'
-                "</div>"
-                % (
+
+        stringToCheckFor = ""
+        for (lineNumber, sourceLine) in enumerate(source):
+            template = '<div class="snippet{}Line"><span>{}</span><span>{}</span></div>'
+            if lineNumber <= 1:
+                stringToCheckFor += template.format(
                     ["", "Highlight"][lineNumber == 1],
                     self.base + lineNumber,
                     (" \N{NO-BREAK SPACE}" * 4 + sourceLine),
                 )
-                for (lineNumber, sourceLine) in enumerate(source)
-            ]
-        ).encode("utf8")
+            else:
+                stringToCheckFor += template.format(
+                    "", self.base + lineNumber, ("" + sourceLine)
+                )
+
+        bytesToCheckFor = stringToCheckFor.encode("utf8")
 
-        d.addCallback(self.assertEqual, stringToCheckFor)
+        d.addCallback(self.assertEqual, bytesToCheckFor)
         return d
 
     def test_frameElementFilename(self):
```

`test_sourceFragmentElement` actually parses `twisted/web/test/test_util.py`, so when that file gets reformatted, this particular test breaks.

**Comment by rodrigc** [comment]
Can you also add this patch to your branch?  This should fix the mypy errors:

```
diff --git a/src/twisted/internet/endpoints.py b/src/twisted/internet/endpoints.py
index ad6bcf3f2..e0da0f200 100644
--- a/src/twisted/internet/endpoints.py
+++ b/src/twisted/internet/endpoints.py
@@ -317,8 +317,8 @@ class _IProcessTransportWithConsumerAndProducer(
 
 
 class _ProcessEndpointTransport(
-    proxyForInterface(
-        _IProcessTransportWithConsumerAndProducer,  # type: ignore[misc]  # noqa
+    proxyForInterface(  # type: ignore[misc]
+        _IProcessTransportWithConsumerAndProducer,
         "_process",
     )
 ):
diff --git a/src/twisted/internet/test/process_cli.py b/src/twisted/internet/test/process_cli.py
index 7e29cdc1e..481c7be1c 100644
--- a/src/twisted/internet/test/process_cli.py
+++ b/src/twisted/internet/test/process_cli.py
@@ -7,9 +7,9 @@ try:
     # the tests.
     import msvcrt
 
-    msvcrt.setmode(
+    msvcrt.setmode(  # type:ignore[attr-defined]
         sys.stdout.fileno(), os.O_BINARY
-    )  # type:ignore[attr-defined]  # noqa
+    )
 except ImportError:
     pass
 
diff --git a/src/twisted/mail/test/test_pop3.py b/src/twisted/mail/test/test_pop3.py
index 529a2cd02..ba9bb3d8e 100644
--- a/src/twisted/mail/test/test_pop3.py
+++ b/src/twisted/mail/test/test_pop3.py
@@ -369,10 +369,8 @@ Someone set up us the bomb!\015
         d = loopback.loopbackAsync(protocol, clientProtocol)
         return d.addCallback(check)
 
-    test_loopback.suppress = [
-        util.suppress(  # type: ignore[attr-defined]
-            message="twisted.mail.pop3.POP3Client is deprecated"
-        )
+    test_loopback.suppress = [  # type: ignore[attr-defined]
+        util.suppress(message="twisted.mail.pop3.POP3Client is deprecated")
     ]
 
     def test_incorrectDomain(self):
diff --git a/src/twisted/python/test/test_runtime.py b/src/twisted/python/test/test_runtime.py
index 4cebdff2a..2d93d4527 100644
--- a/src/twisted/python/test/test_runtime.py
+++ b/src/twisted/python/test/test_runtime.py
@@ -87,9 +87,9 @@ class PlatformTests(SynchronousTestCase):
         if platform.getType() != "win32":
             self.assertFalse(isWinNT)
 
-    test_isWinNT.suppress = [
+    test_isWinNT.suppress = [  # type: ignore[attr-defined]
         SUPRESS(
-            category=DeprecationWarning,  # type: ignore[attr-defined]  # noqa
+            category=DeprecationWarning,
             message=isWinNTDeprecationMessage,
         )
     ]
diff --git a/src/twisted/trial/_asyncrunner.py b/src/twisted/trial/_asyncrunner.py
index bce4869c2..51715ee24 100644
--- a/src/twisted/trial/_asyncrunner.py
+++ b/src/twisted/trial/_asyncrunner.py
@@ -38,8 +38,8 @@ class TestSuite(pyunit.TestSuite):
 
 @implementer(itrial.ITestCase)
 class TestDecorator(
-    components.proxyForInterface(
-        itrial.ITestCase, "_originalTest"  # type: ignore[misc]  # noqa
+    components.proxyForInterface(  # type: ignore[misc]
+        itrial.ITestCase, "_originalTest"
     )
 ):
     """
diff --git a/src/twisted/trial/reporter.py b/src/twisted/trial/reporter.py
index d6ad9d576..03a9c86e1 100644
--- a/src/twisted/trial/reporter.py
+++ b/src/twisted/trial/reporter.py
@@ -223,9 +223,7 @@ class TestResult(pyunit.TestResult):
 
 @implementer(itrial.IReporter)
 class TestResultDecorator(
-    proxyForInterface(
-        itrial.IReporter, "_originalReporter"  # type: ignore[misc]  # noqa
-    )
+    proxyForInterface(itrial.IReporter, "_originalReporter")  # type: ignore[misc]
 ):
     """
     Base class for TestResult decorators.
diff --git a/src/twisted/trial/test/erroneous.py b/src/twisted/trial/test/erroneous.py
index e259e6fb1..2d527bfb8 100644
--- a/src/twisted/trial/test/erroneous.py
+++ b/src/twisted/trial/test/erroneous.py
@@ -162,8 +162,8 @@ class DelayedCall(unittest.TestCase):
         reactor.iterate(0.01)
         self.fail("Deliberate failure to mask the hidden exception")
 
-    testHiddenException.suppress = [
-        util.suppress(  # type: ignore[attr-defined]  # noqa
+    testHiddenException.suppress = [  # type: ignore[attr-defined]
+        util.suppress(
             message=r"reactor\.iterate cannot be used.*", category=DeprecationWarning
         )
     ]
diff --git a/src/twisted/trial/test/test_deferred.py b/src/twisted/trial/test/test_deferred.py
index b4690ff58..5927f7c6f 100644
--- a/src/twisted/trial/test/test_deferred.py
+++ b/src/twisted/trial/test/test_deferred.py
@@ -120,10 +120,8 @@ class DeferredTests(TestTester):
         self.assertEqual(result.testsRun, 1)
         self.assertTrue(detests.DeferredTests.touched)
 
-    test_passGenerated.supress = [
-        util.suppress(  # type: ignore[attr-defined]
-            message="twisted.internet.defer.deferredGenerator is deprecated"
-        )
+    test_passGenerated.supress = [  # type: ignore[attr-defined]
+        util.suppress(message="twisted.internet.defer.deferredGenerator is deprecated")
     ]
 
     def test_passInlineCallbacks(self):
diff --git a/src/twisted/web/test/test_xmlrpc.py b/src/twisted/web/test/test_xmlrpc.py
index 2be3079eb..a452014a8 100644
--- a/src/twisted/web/test/test_xmlrpc.py
+++ b/src/twisted/web/test/test_xmlrpc.py
@@ -114,8 +114,8 @@ class Test(XMLRPC):
         """
         return a + b
 
-    xmlrpc_add.signature = [
-        ["int", "int", "int"],  # type: ignore[attr-defined]
+    xmlrpc_add.signature = [  # type: ignore[attr-defined]
+        ["int", "int", "int"],
         ["double", "double", "double"],
     ]
 
diff --git a/src/twisted/web/xmlrpc.py b/src/twisted/web/xmlrpc.py
index 689314c64..a5f210792 100644
--- a/src/twisted/web/xmlrpc.py
+++ b/src/twisted/web/xmlrpc.py
@@ -307,8 +307,8 @@ class XMLRPCIntrospection(XMLRPC):
         method = self._xmlrpc_parent.lookupProcedure(method)
         return getattr(method, "signature", None) or ""
 
-    xmlrpc_methodSignature.signature = [
-        ["array", "string"],  # type: ignore[attr-defined] # noqa
+    xmlrpc_methodSignature.signature = [  # type: ignore[attr-defined]
+        ["array", "string"],
         ["string", "string"],
     ]
 
```

**Comment by twm** [comment]
@rodrigc I am working through the failures.

I haven't looked at the mypy failure yet, but I'd guess it's because I ran Black with Python 3.6. Perhaps it moved the comments around because they aren't part of the AST until Python 3.8. I'll test that theory tomorrow; I'm headed for bed now.

**Comment by rodrigc** [comment]
Yes the mypy issues are because comments got shifted to a different line.  Python 3.6 vs 3.8 is irrelevant.  See this patch: https://github.com/twisted/twisted/pull/1381#issuecomment-691646196

**Comment by twm** [comment]
Oh sorry, I didn't see your new comments! I'll apply those patches. Thanks for digging in!

**Review by rodrigc — APPROVED** [review]
All the CI now passes.
Before merging, you may want to consider squashing some of the commits in this PR to clean up the history

**Comment by twm** [comment]
Thank you very much @rodrigc! I will merge this and begin the follow-up communications work.

**Comment by rodrigc** [comment]
@twm Nice job!

**Pull request merged**
